### ISSUE TITLE
Identify right private dns zone for azure services for the private endpoint

### ISSUE THREAD

**Issue by gowrisankar22** [Azure/azure-sdk-for-go#14066] opened 2021-01-03 17:41 UTC
Hello All,

After creating a private endpoint for any of the azure services, we need to add the A record for the respective service to the custom Private DNS zone(if I don't select the default option). Consider I am doing this is using Kubernetes operator(using azure golang sdk).

Before creating the A record for any of the supported services, after creating a private endpoint, I need to identify from the serviceid, what would be an equivalent private dns zone for the given serviceid ? Somehow I didn't find the right way to do it instead of having my own inventory something like below for all the private endpoint supported services and use a filter of Subresource and select.

Can you help me to find the right approach?

```
{
"postgres":[
{
"subresource":"Microsoft.DBforPostgreSQL/servers",
"privatednszone":"privatelink.postgres.database.azure.com"
}
]
}

```
 
**Example for postgres** : : **ServiceId**
```
/subscriptions/xx/resourceGroups/rg_privatelink_poc/providers/Microsoft.DBforPostgreSQL/servers/myservergs
```

[1] https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns

**Comment by ArcturusZhang** [comment] 2021-01-07 04:32
Hi @gowrisankar22 thanks for opening this issue!

But this seems like to be duplicate of https://github.com/Azure/azure-sdk-for-go/issues/14065, I am going to close this issue in favor of #14065

**Closed by ArcturusZhang** 2021-01-07 04:32 UTC
Labels: customer-reported, needs-triage, question

**Comment by gowrisankar22** [comment] 2021-01-07 05:15
@ArcturusZhang This is not a duplicate. Both are two different asks. How to identify the right DNS private zone from a serviceid ..
