### ISSUE TITLE
Delay or bad response running ARM AZ commands - Mismatch 

### ISSUE THREAD

**Issue by alftio** [Azure/azure-sdk-for-go#12342] opened 2020-08-25 17:43 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

- What happened?

Current Behavior:
AZ Command is lost requesting to an unkown or far API Endpoint then there are 3 behaviors

a-Null
b-No results
c-Good response with delay

Flow:

1- Request: az vmss list
2- Results:
  a- Null "value":[]
  b- No results
  c- VMSS list after 5-20 minutes

Reproducible on:

azure-sdk-for-go
Azure CLI

- What did you expect or want to happen?

AZ commands request must respond under the expected time intermediately in the first execution.

- How can we reproduce it?

Run the next CLI script

#!/bin/bash

name=$1
location=$2

az group create --name $name --location $location
az aks create -g $name -n $name

for i in {1..200}
do
  START=$(date +%s)
  echo "Try number $i"
  az vmss list --resource-group MC_${name}_${name}_${location} -o table
  END=$(date +%s)
  DIFF=$(( $END - $START ))
  echo "Time elapsed: $DIFF seconds "
  echo "----------------------------"
  sleep 2
done

Usin Azure-SDK-FOR -GO
Use any of the examples and try to list the VMSS or getVMSsClient()
getTestVMSSClientWithRetryAfterReader(armClient). result, rerr := vmssClient.List
https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/master/compute/vm_scale_set_test.go

-Workaround
Specify the API Endpoint region as part of the request instead on going to the general FQDN. This is not a valid Workaround in all the cases neither when using the GO SDK. 

https://westeurope.management.azure.com/subscriptions/#########/resourceGroups/MC_test-api2_test-api2_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2019-12-01

- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment] 2020-08-27 07:55
Hi @alftio thanks for this issue! 

Sorry but I think I did not quite get your point by this issue. Could you please add more details about what is this issue in go SDK?

**Comment by alftio** [comment] 2020-09-03 04:10
Hi @ArcturusZhang ,

Using the azure-sdk-for-go when trying to retrieve the vmss list it fails, there is not any value retrieved.

**Comment by mackrorysd** [comment] 2020-09-03 15:28
This has been a big deal for me. We have an application that spans multiple regions, and have seen delays of up to 2 hours in the VMSS API. Previously this has been caused by system outages, but currently the only answer I have from Azure support is this: specifying the regional endpoint to use and ensuring that's consistent. However that does not appear to be possible in the Go SDK.

**Comment by tombuildsstuff** [comment] 2020-09-03 17:12
@mackrorysd that should be possible with [the NewClientWithBaseUri method](https://github.com/Azure/azure-sdk-for-go/blob/master/services/signalr/mgmt/2020-05-01/signalr/signalr.go#L41) providing `https://westeurope.management.azure.com` as the BaseURI, fwiw?

**Comment by mackrorysd** [comment] 2020-09-09 22:36
That could work - we'll try that out. Thanks @tombuildsstuff!

**Comment by lirenhe** [comment] 2021-12-22 06:02
@mackrorysd, looks there is a solution for the question you ask, so we will close this item and let me know if you have other feedback. Thanks.

**Closed** 2022-01-13 08:02 UTC
Labels: Mgmt, needs-author-feedback, no-recent-activity
