### ISSUE TITLE
Web.CertificatesClient: Tags field has no effect on update and data is not being returned

### ISSUE THREAD

**Issue by AliAllomani** [Azure/azure-sdk-for-go#14700] opened 2021-05-24 15:25 UTC
### Bug Report

- import path of package in question, e.g. `.../services/web/mgmt/2020-12-01/web`
- SDK version `master`

- What happened?
`Tags` field in web.Certificate model is not getting created/updated by `web.CertificatesClient.CreateOrUpdate` or read by `web.CertificatesClient.Get`

related to https://github.com/Azure/azure-rest-api-specs/issues/14529

**Comment by ArcturusZhang** [comment] 2021-05-28 03:41
Hi @AliAllomani thanks for opening this issue!

As you dig out in https://github.com/Azure/azure-rest-api-specs/issues/14529, the root cause of this issue is in the service side, and since we already have an issue about this in the spec repo, I am going to close this one in favor of that.

The service side issue does not need a regeneration of SDK to fix. If the service team fixes this on their side, all the SDKs will be fixed

**Closed by ArcturusZhang** 2021-05-28 03:41 UTC
Labels: customer-reported, needs-triage, question
