### ISSUE TITLE
Azure backend has changed the record type for private hosted dns records

### ISSUE THREAD

**Issue by sidheshdivekar29** [Azure/azure-sdk-for-go#18072] opened 2022-05-17 14:00 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns

- SDK version e.g. `master`, `latest`, `18.1.0`
master

  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
commit 21114a367037e932473f5b1509c3aeea98f93362 (HEAD -> master, origin/master, origin/HEAD)
Author: Azure SDK Bot <53356347+azure-sdk@users.noreply.github.com>
Date:   Fri Apr 9 13:32:52 2021 -0700

- output of `go version`
go version
go version go1.17 darwin/amd64

- What happened?
In this case when we try to delete the record set, we have replace the string "Microsoft.Network/privateDnsZones/" with "" before calling Get, Delete apis for the record set.
- What did you expect or want to happen?
We should be able to pass the record type we receive from azure backend to go sdk apis.
- How can we reproduce it?
Call private dns list api for a given private hosted zone and then pass the record type received to Get/Delete api calls.
- Anything we should know about your environment.

**Comment by navba-MSFT** [comment] 2022-05-26 09:21
Adding the Service Team to look into this issue.

**Comment by navba-MSFT** [comment] 2022-06-29 03:11
@dnssuppgithub Could you please look into this issue and provide an update?

**Comment by RickWinter** [comment] 2023-01-10 17:35
@lirenhe can you review this issue and assign to appropriate owner/team.

**Comment by lirenhe** [comment] 2023-01-11 03:45
@tadelesh, could you help to check whether this issue happens in the latest version of GO SDK?

**Comment by tadelesh** [comment] 2023-01-12 08:43
Though customer is using our previous SDK, it is still existed in our current new version through my test. The type returned by the `List` and the type passed to `Get` are different for the same record. @navba-MSFT Could you help to contact the service team to check whether it is by design?
List:
```
[Jan 12 16:36:54.518020] Response: ==> REQUEST/RESPONSE (Try=1/604.5539ms, OpTime=604.5539ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/xxx/resourceGroups/chenjieshitest/providers/Microsoft.Network/privateDnsZones/chenjietest.com/ALL?api-version=2020-06-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armprivatedns/v1.0.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: private
   Content-Type: application/json; charset=utf-8
   Date: Thu, 12 Jan 2023 08:36:54 GMT
   Server: Microsoft-IIS/10.0
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Aspnet-Version: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Resource-Entities-Read: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: REDACTED
   X-Ms-Request-Id: 2bf0ea96-7af3-46f4-b106-48c49854b5ed
   X-Ms-Routing-Request-Id: REDACTED
   X-Powered-By: REDACTED
   --------------------------------------------------------------------------------
{"value":[{"id":"\/subscriptions\/xxx\/resourceGroups\/chenjieshitest\/providers\/Microsoft.Network\/privateDnsZones\/chenjietest.com\/SOA\/@","name":"@","type":"Microsoft.Network\/privateDnsZones\/SOA","etag":"84c767c6-f7b3-435e-906d-047d51feb843","properties":{"fqdn":"chenjietest.com.","ttl":3600,"soaRecord":{"email":"azureprivatedns-host.microsoft.com","expireTime":2419200,"host":"azureprivatedns.net","minimumTtl":10,"refreshTime":3600,"retryTime":300,"serialNumber":1},"isAutoRegistered":false}},{"id":"\/subscriptions\/xxx\/resourceGroups\/chenjieshitest\/providers\/Microsoft.Network\/privateDnsZones\/chenjietest.com\/A\/test","name":"test","type":"**Microsoft.Network\/privateDnsZones\/A**","etag":"983f7a7d-88cf-4655-b9c7-3c70c7045e15","properties":{"fqdn":"test.chenjietest.com.","ttl":3600,"aRecords":[],"isAutoRegistered":false}}]}
   --------------------------------------------------------------------------------
```
Get
```
[Jan 12 16:37:13.060834] Response: ==> REQUEST/RESPONSE (Try=1/338.634ms, OpTime=339.2084ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/xxx/resourceGroups/chenjieshitest/providers/Microsoft.Network/privateDnsZones/chenjietest.com/**A**/test?api-version=2020-06-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armprivatedns/v1.0.0 (go1.19; Windows_NT)
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: private
   Content-Type: application/json; charset=utf-8
   Date: Thu, 12 Jan 2023 08:37:12 GMT
   Etag: 983f7a7d-88cf-4655-b9c7-3c70c7045e15
   Server: Microsoft-IIS/10.0
   Strict-Transport-Security: REDACTED
   Vary: REDACTED
   X-Aspnet-Version: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: REDACTED
   X-Ms-Request-Id: 852ec4c1-94c2-42cc-b480-c85322225627
   X-Ms-Routing-Request-Id: REDACTED
   X-Powered-By: REDACTED
   --------------------------------------------------------------------------------
{"id":"\/subscriptions\/xxx\/resourceGroups\/chenjieshitest\/providers\/Microsoft.Network\/privateDnsZones\/chenjietest.com\/A\/test","name":"test","type":"Microsoft.Network\/privateDnsZones\/A","etag":"983f7a7d-88cf-4655-b9c7-3c70c7045e15","properties":{"fqdn":"test.chenjietest.com.","ttl":3600,"aRecords":[],"isAutoRegistered":false}}
   --------------------------------------------------------------------------------
```

**Comment by navba-MSFT** [comment] 2023-01-12 10:02
@tadelesh Sent an email to the PM keeping you in the loop.

**Comment by tadelesh** [comment] 2023-12-26 06:27
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.

**Closed by tadelesh** 2023-12-26 06:27 UTC
Labels: question, Network - DNS, Service Attention, Mgmt, customer-reported, needs-team-attention, Previous Versions
