### ISSUE TITLE
arm/keyvault: List returns all resources instead of key vaults

### ISSUE THREAD

**Issue by chessman** [Azure/azure-sdk-for-go#696] opened 2017-07-25 17:29 UTC
`ListPreparer` uses path `"/subscriptions/{subscriptionId}/resources"`. But it should be something like `"/subscriptions/{subscriptionId}/providers/Microsoft.KeyVault/vaults"`.

**Comment by marstr** [comment] 2017-07-25 19:47
I've confirmed the behavior and built out a quick repro that demonstrates the issue, the code can be found here: https://github.com/marstr/issue696

**Comment by marstr** [comment] 2017-07-25 20:33
I did a little more testing, and validated that this bug isn't applicable to the `ListByResourceGroup(string, *int32)` function that is also available on the `keyvault.VaultsClient`. I also found [this issue](https://github.com/Azure/azure-rest-api-specs/issues/389) in the Azure/azure-rest-api-specs repository that suggests this may be a known behavior.

That said, I agree with @chessman that this is at best very confusing behavior, and at worst actively misleading. @amarzavery, do you have any context you can help me out with?

**Comment by marstr** [comment] 2017-07-25 23:06
Alright, there are two futures I could see for this issue:
1. The KeyVault team actively supports this scenario of Listing vaults for an entire subscription. In this case, we'd simply need to update the path used for this operation. It's kinda a breaking change, but falls into the category of "folks should have never been using it this way."
2. The KeyVault team does not support this. In which case, I would argue that Swaggers for future API Versions not include this function what-so-ever.

Either way, the line in question is [here](https://github.com/Azure/azure-rest-api-specs/blob/723d7ee6b699121d01d2f71ccefcc7b2183e6361/specification/keyvault/resource-manager/Microsoft.KeyVault/2016-10-01/keyvault.json#L294). Due to its location, I'm going to transfer this issue to the azure-rest-api-specs repository for further discussion.

**Comment by marstr** [comment] 2017-07-25 23:11
Closing in favor of Azure/azure-rest-api-specs#1464.

**Closed by marstr** 2017-07-25 23:11 UTC
Labels: Investigate
