### ISSUE TITLE
DevTest Labs vms completely ignore resourcegroup

### ISSUE THREAD

**Issue by zlepper** [Azure/azure-sdk-for-go#353] opened 2016-07-04 13:12 UTC
It seems any vms created in the DevTest-Labs using the api completely ignore the assigned resourcegroup, and instead create a new one. 
To confirm my suspision I attached a request inspector to the client. This is what I got:

```
Inspecting Request: PUT https://management.azure.com/subscriptions/f024abe7-####-####-####-e0ea18c47565/resourceGroups/test-lab7/providers/Microsoft.DevTestLab/labs/test-lab7/virtualmachines/test-machine7?api-version=2016-05-15
{"properties":{"size":"Standard_A2","userName":"houseadmin","password":"House123","isAuthenticationWithSshKey":false,"labSubnetName":"Dtltest-lab7Subnet","labVirtualNetworkId":"/subscriptions/f024abe7-####-####-####-e0ea18c47565/resourcegroups/test-lab7/providers/micr
osoft.devtestlab/labs/test-lab7/virtualnetworks/dtltest-lab7","disallowPublicIpAddress":false,"artifacts":[{"artifactId":"/subscriptions/f024abe7-####-####-####-e0ea18c47565/resourceGroups/test-lab7/providers/Microsoft.DevTestLab/labs/test-lab7/artifactSources/DigiZui
te Artifacts/artifacts/octopus"}],"galleryImageReference":{"offer":"WindowsServer","publisher":"MicrosoftWindowsServer","sku":"2012-R2-Datacenter","osType":"Windows","version":"latest"}},"name":"test-machine7","location":"westeurope"}
```

This definetely doesn't seem to be what is intended, but rather the vm should be created in the specified resourcegroup.

**Comment by garimakhulbe** [comment] 2016-07-05 18:07
In which api you are getting this issue? What exactly you were trying to do? I can see resourcegrp name 'test-lab7' in snippet. Can you put more details like RG name you set in request and new name you got and also some code on how you are doing it?

**Comment by zlepper** [comment] 2016-07-05 19:20
The devtest-labs api. 

This is what i'm doing to create the vm itself. 
I call this method with the name of a resourcegroup (resourcename) i have created at another point. However the resourcename is not the resourcename under which the machine is created. 
```go
func CreateVm(resourcename, labname, vmname, location, username, password string, labData *LabData, image *devtestlabs.GalleryImageReference) compute.VirtualMachine {

	client := devtestlabs.NewVirtualMachineClient(helpers.SubscriptionID)
	client.Authorizer = helpers.GetServicePrincipalToken()
	client.RequestInspector = helpers.WithInspection()
	client.ResponseInspector = helpers.ResponseInspector()
	if _, err := client.GetResource(resourcename, labname, vmname); err == nil {
		return resources.GetVm(resourcename, vmname)
	}

	vm := devtestlabs.LabVirtualMachine{
		Location:&location,
		Name:&vmname,
		Properties:&devtestlabs.LabVirtualMachineProperties{
			LabVirtualNetworkID:labData.NetworkId,
			GalleryImageReference:image,
			Size:helpers.String("Standard_A2"),
			UserName:&username,
			Password:&password,
			IsAuthenticationWithSSHKey:helpers.Bool(false),
			LabSubnetName:helpers.String("Dtl" + labname + "Subnet"),
			DisallowPublicIPAddress:helpers.Bool(false),
			Artifacts:&[]devtestlabs.ArtifactInstallProperties{
				devtestlabs.ArtifactInstallProperties{
					ArtifactID:labData.OctopusArtifactId,
				},
			},
		},
	}

	_, err := client.CreateOrUpdateResource(resourcename, labname, vmname, vm, nil)
	if err != nil {
		panic(err)
	}

	return resources.GetVm(resourcename, vmname)
}
```

In the snippet in the op, the resourcegroupname set was 'test-lab7', that is however not what resourcegroup the vm gets when created.

**Comment by ahmetalpbalkan** [comment] 2016-07-06 05:33
@zlepper what's the resource group you are getting instead?

**Comment by zlepper** [comment] 2016-07-06 06:12
Something like this: test-machine71301072542

**Comment by ramankumarlive** [comment] 2016-07-06 23:34
@zlepper Your finding is correct but it is as per design. We wanted to make the developer experience of creating a VM as simple as possible without needing a developer to know about resource groups. But few our customers have already raised their concern about the implementation. We are going to improve the implementation by allowing you to specify RG for your machine at the time of VM creation. Let me know if this helps.

**Comment by zlepper** [comment] 2016-07-07 03:48
That would certainly help. 
Is there any ETA for that change? Or should I just go ahead and implement a workaround for now in our source?

**Comment by ramankumarlive** [comment] 2016-07-07 03:53
Any reason why you want to create all the VMs in same resource group?

**Comment by zlepper** [comment] 2016-07-07 03:57
Yes. After I have created the vms, I need to configure octopus an octopus tentacle, which is installed as an artifact. To configure it I need the dns label of the server, so I can tell my octopus server where to look for the tentacle. 
We then use octopus to manage deployments to the server and to update programs. 

Having it all under one resourcegroup also makes it easier to delete everything when we don't need OT anymore, we simply just nuke the resourcegroup and everything attached to it.

**Comment by zlepper** [comment] 2016-07-07 06:08
Which leads me to the question, how do I move something from one resourcegroup to another? 
I would imagine all the CreateOrUpdate methods would give me a 404 of called with another resourcegroup, instead of actually moving the resource.

**Comment by garimakhulbe** [comment] 2016-08-11 23:12
Seems you find the solution. Closing this.

**Closed by garimakhulbe** 2016-08-11 23:12 UTC
Labels: area/azureresourcemanager

**Comment by junhuac** [comment] 2018-09-13 18:49
It looks like this issue still haven't been resolved yet. When I deployed Selenium Grid in Azure Dev Test Lab using the lab sample script, all VMs have been instructed to be created in same Resource Group, however, the end result is that all of the resources for the VMS have been created in their separate Resource Groups:
https://github.com/Azure/azure-devtestlab/tree/master/Samples/201-dtl-create-lab-with-seleniumgrid

This issue has created huge problems for us. Enterprises are increasingly managing their Azure subscriptions by assigning teams to different Resource Groups. The new Resource Groups created by Azure Dev Test Lab create huge management problems for subscription owners, as they can't determine easily which team owns the newly created Resource Groups.

**Comment by ramankumarlive** [comment] 2018-09-17 22:18
Looping DTL Team.

Regards
Raman Kumar
Senior Program Manager
Azure Storage

**Comment by sindhu-nagesh** [comment] 2018-09-17 22:35
This is by design and there is no issue that we are working on. We do not have an ETA on when we will support user specifying a resource group to create the VMs in.
