### ISSUE TITLE
Filter does not allow to use `not` clause in the `usage` query request of cost-management

### ISSUE THREAD

**Issue by jinxue-w** [Azure/azure-sdk-for-go#8317] opened 2020-04-15 13:01 UTC
# Bug Report

The [usage function](https://github.com/Azure/azure-sdk-for-go/blob/68d483faf640e457e33779443ebc5108b900d3ff/services/costmanagement/mgmt/2019-10-01/costmanagement/query.go#L65) does not support to use `not` in its filter parameter,

Error message:
```
{
  "error": {
    "code": "500",
    "message": "An error occurred during processing this request. Use this request id 'dee23d2e-3831-4321-a775-d32bf08a14dd' for follow-up."
  }
}
```

**Comment by ArcturusZhang** [comment] 2020-04-16 04:00
Hi @jinxue-w thanks for this issue.
Could you please also provide the request or code snippet when you are sending the request? 
Also I have tagged this issue so that the corresponding service team will get noticed and have a look.

**Comment by jinxue-w** [comment] 2020-04-16 13:03
> 您好@ jinxue-w感谢您提供此问题。
> 发送请求时，还可以提供请求或代码段吗？
> 我也标记了此问题，以便相应的服务团队得到注意并进行查看。

{
    "type": "AmortizedCost",
    "timeframe": "Custom",
    "timePeriod": {
        "from": "2020-04-14T00:00:00Z",
        "to": "2020-04-14T00:00:00Z"
    },
    "dataset": {
        "aggregation": {
            "CostUSD": {
                "name": "CostUSD",
                "function": "Sum"
            },
            "UsageQuantity": {
                "name": "UsageQuantity",
                "function": "Sum"
            }
        },
        "filter": {
            "not": {
                "tags": {
                    "name": "testTagName",
                    "operator": "In",
                    "values": [
                        "testTagValue1"
                    ]
                }
            }
        },
        "granularity": "Daily",
        "grouping": [
            {
                "type": "Dimension",
                "name": "ServiceName"
            },
            {
                "type": "Dimension",
                "name": "Meter"
            },
            {
                "type": "Dimension",
                "name": "ResourceLocation"
            },
            {
                "type": "TagKey",
                "name": "testTagName"
            }
        ]
    }
}

你可以看看这个请求body

**Comment by ms-premp** [comment] 2020-05-11 15:44
This is by design at present. Not is not supported on TagKey for filtering. We will be adding new way for handling this scenario by end of this month.

**Comment by ramaganesan-rg** [comment] 2020-05-11 17:10
Closing as per comments from Prem. Thank you for reaching out!

**Closed by ramaganesan-rg** 2020-05-11 17:10 UTC
Labels: Cost Management, Mgmt, Service Attention, customer-reported
