### ISSUE TITLE
v34.0.0 - installs break go-autorest

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-sdk-for-go#5964] opened 2019-10-07 19:40 UTC
### Bug Report

Running a `go build` on the new release has breaking changes for go-autorest.
Missing packages for go-autorest:
```
[[projects]]
  digest = "1:cf0d2e435fd4ce45b789e93ef24b5f08e86be0e9807a16beb3694e2d8c9af965"
  name = "github.com/dimchansky/utfbom"
  packages = ["."]
  pruneopts = "UT"
  revision = "d2133a1ce379ef6fa992b0514a77146c60db9d1c"
  version = "v1.1.0"

[[projects]]
  digest = "1:5d231480e1c64a726869bc4142d270184c419749d34f167646baa21008eb0a79"
  name = "github.com/mitchellh/go-homedir"
  packages = ["."]
  pruneopts = "UT"
  revision = "af06845cf3004701891bf4fdb884bfe4920b3727"
  version = "v1.1.0"

[[projects]]
  branch = "master"
  digest = "1:78102ee4d536347316bc42e818340cc50902e45dbd7fdd524c5a1fc0cb07b588"
  name = "github.com/globalsign/mgo"
  packages = [
    ".",
    "bson",
    "internal/json",
    "internal/sasl",
    "internal/scram",
  ]
  pruneopts = "UT"
  revision = "eeefdecb41b842af6dc652aaea4026e8403e62df"

```

- All installs/tests were running fine until the latest release once those packages were removed. I could not run a gobuild on my file that had imported go-autorest auth. Once in my env (run on azure devops ubuntu) I also installed all dependencies for go-autorest I finally was able to get runs working. In README.md no documentation of setting up install/ and initializing a client changed.

**Comment by ArcturusZhang** [comment] 2019-10-08 02:23
Sorry for the inconvenience, I am investigating this issue and may release a patch version to fix this.

**Comment by ArcturusZhang** [comment] 2019-10-08 02:54
Hi @rebecca-makar 
I wrote a brief sample project trying to reproduce this issue, but it seems fine for me, there is no error reported on my side. 
I must admit that in v34.0.0, these three packages are indeed redundant to the SDK. SDK is not using them but they remained in the `Gopkg.toml`, which will be fixed in the next patch coming in next a few days. But the sample I wrote does not reproduce the problem you are encountering.
Here is the code snippet I am using:
``` go
        if authorizer, err := auth.NewAuthorizerFromCLI(); err != nil {
		panic(err)
	} else {
		client := network.NewInterfacesClient(subsID)
		client.Authorizer = authorizer
		ctx := context.Background()
		parameters := network.Interface{
			InterfacePropertiesFormat: &network.InterfacePropertiesFormat{},
			Location:                  to.StringPtr("eastus2"),
		}
		if future, err := client.CreateOrUpdate(ctx, resourceGroup, "test", parameters); err != nil {
			panic(err)
		} else {
			future.WaitForCompletionRef(ctx, client.Client)
		}
      }
```
And the Gopkg.toml:
```
[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "v34.0.0"

[prune]
  go-tests = true
  unused-packages = true
```
Please note this snippet will panic to error, because I did not fill the interface will enough parameters, but it can build and run.

**Comment by rebecca-makar** [comment] 2019-10-08 13:24
Hm strange. So I do a fresh go install
```
go get -v -u github.com/Azure/azure-sdk-for-go/...
go build
```

and get:
```
../../../../../Azure/go-autorest/autorest/azure/cli/profile.go:25:2: cannot find package "github.com/dimchansky/utfbom" in any of:
	/usr/local/go1.11/src/github.com/dimchansky/utfbom (from $GOROOT)
	/home/vsts/work/1/s/gopath/src/github.com/dimchansky/utfbom (from $GOPATH)
../../../../../Azure/go-autorest/autorest/azure/cli/profile.go:26:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/local/go1.11/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/home/vsts/work/1/s/gopath/src/github.com/mitchellh/go-homedir (from $GOPATH)
../../../../../Azure/go-autorest/autorest/azure/auth/auth.go:36:2: cannot find package "golang.org/x/crypto/pkcs12" in any of:
	/usr/local/go1.11/src/golang.org/x/crypto/pkcs12 (from $GOROOT)
	/home/vsts/work/1/s/gopath/src/golang.org/x/crypto/pkcs12 (from $GOPATH)
```

but if I add this before it works fine (didnt have to do that before):
`    go get -v -u github.com/Azure/go-autorest/...
`

I just wanted to share my experience incase others go through it. Thanks for the help! @ArcturusZhang

**Comment by ArcturusZhang** [comment] 2019-10-10 03:17
> Hm strange. So I do a fresh go install
> then after installed I do:
> 
> ```
> go get -v -u github.com/Azure/azure-sdk-for-go/...
> go build
> ```
> 
> and get:
> 
> ```
> ../../../../../Azure/go-autorest/autorest/azure/cli/profile.go:25:2: cannot find package "github.com/dimchansky/utfbom" in any of:
> 	/usr/local/go1.11/src/github.com/dimchansky/utfbom (from $GOROOT)
> 	/home/vsts/work/1/s/gopath/src/github.com/dimchansky/utfbom (from $GOPATH)
> ../../../../../Azure/go-autorest/autorest/azure/cli/profile.go:26:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
> 	/usr/local/go1.11/src/github.com/mitchellh/go-homedir (from $GOROOT)
> 	/home/vsts/work/1/s/gopath/src/github.com/mitchellh/go-homedir (from $GOPATH)
> ../../../../../Azure/go-autorest/autorest/azure/auth/auth.go:36:2: cannot find package "golang.org/x/crypto/pkcs12" in any of:
> 	/usr/local/go1.11/src/golang.org/x/crypto/pkcs12 (from $GOROOT)
> 	/home/vsts/work/1/s/gopath/src/golang.org/x/crypto/pkcs12 (from $GOPATH)
> ```
> 
> but if I add this before it works fine (didnt have to do that before):
> ` go get -v -u github.com/Azure/go-autorest/...`
> 
> I just wanted to share my experience incase others go through it. Thanks for the help! @ArcturusZhang

This is really strange. `go-autorest` is a dependency of go sdk, so go get sdk will recursively get go-autorest.
After the minor version is released, could you please do another test for this then? Thanks in advance.

**Comment by ArcturusZhang** [comment] 2019-10-11 02:23
Hi @rebecca-makar v34.1.0 is released, please feel free to have a test again

**Comment by rebecca-makar** [comment] 2019-10-11 02:39
@ArcturusZhang I will run it tomorrow morning and send you an update! Thank you

**Comment by rebecca-makar** [comment] 2019-10-11 14:22
@ArcturusZhang it worked! Install of just sdk worked. 
```
go get -v -u github.com/Azure/azure-sdk-for-go/...
```
 I was able to remove 
```
go get -v -u github.com/Azure/go-autorest/...
```

Thank you!!

**Closed** 2019-10-12 09:17 UTC
Labels: Mgmt, customer-reported, customer-response-expected
