### ISSUE TITLE
azblob.Client.UploadStream allows incomplete uploads

### ISSUE THREAD

**Issue by sam701** [Azure/azure-sdk-for-go#21837] opened 2023-10-26 10:40 UTC
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: `1.2.0`
- output of `go version`: `go version go1.21.1 darwin/arm64`

#### What happened?
Call
```go
  _, err = client.UploadStream(context.Background(), "container1", "test1", theReader, nil)
```
returns `err == nil` when `theReader.Read(..)` returns `0, io.ErrUnexpectedEOF`

#### What did you expect or want to happen?
The `err == io.ErrUnexpectedEOF`

#### How can we reproduce it?
```go
package main

import (
	"context"
	"io"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

type fakeReader struct {
	cnt int
}

func (a *fakeReader) Read(bytes []byte) (count int, err error) {
	if a.cnt < 2 {
		var buf [1024]byte
		n := copy(bytes, buf[:])
		a.cnt++
		return n, nil
	}
	return 0, io.ErrUnexpectedEOF
}

func main() {
	credential, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}

	client, err := azblob.NewClient("https://mystorageaccount.blob.core.windows.net", credential, nil)
	if err != nil {
		panic(err)
	}

	r := &fakeReader{}
	_, err = client.UploadStream(context.Background(), "container1", "test/test1", r, nil)
	log.Println("error:", err)
}

```

This [line in azblob](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/chunkwriting.go#L111) treats `io.ErrUnexpectedEOF` as an expected error. 

As an example `http.Request.Body` returns `io.ErrUnexpectedEOF` on connection lost. When I call
```go
  _, err := client.UploadStream(context.Background(), "container1", "test1", req.Body, nil)
```
the returned `err` is `nil` and the container contains a partially uploaded file.

**Comment by souravgupta-msft** [comment] 2023-11-27 10:36
Hi @sam701. Thanks for reaching out. `io.ErrUnexpectedEOF` is an expected error and this is by design.
Consider a case where the reader has closed, and the size of the last chunk being uploaded is less than the [`BlockSize`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/models.go#L320). [This](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/chunkwriting.go#L78) part of the code will then return `io.ErrUnexpectedEOF`, which is an expected error.

**Comment by souravgupta-msft** [comment] 2023-11-27 10:38
For your use case where you are using `req.Body` as the reader, you can copy the data to a buffer or file and use [`UploadBuffer`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L526) or [`UploadFile`](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L541) method instead.

**Comment by sam701** [comment] 2023-11-27 13:55
@souravgupta-msft thanks for the heads up.

> Consider a case where the reader has closed, and the size of the last chunk being uploaded is less than the [BlockSize](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/models.go#L320). [This](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/chunkwriting.go#L78) part of the code will then return io.ErrUnexpectedEOF, which is an expected error.

This is a good example. According to the `Reader` [docs](https://pkg.go.dev/io#Reader), the `io.EOF` is the only expected error. I'd say, it is not correct to use `io.ReadFull` in the code line you mentioned exactly because the last chunk might be smaller than the buffer. The underlying source `Reader` successfully returns `io.EOF` but the wrapping `io.ReadFull` returns `io.UnexpectedEOF`. Maybe using [io.Reader.Read](https://pkg.go.dev/io#Reader) is enough here, i.e. `n, err = src.Read(buffer)?

> For your use case where you are using req.Body as the reader, you can copy the data to a buffer or file and use [UploadBuffer](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L526) or [UploadFile](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L541) method instead.

It is not always an option. Consider large uploads where the entire file being uploaded does not fit into the available memory.

**Comment by souravgupta-msft** [comment] 2023-12-01 11:10
Even if [io.Reader.Read](https://pkg.go.dev/io#Reader) is used here, we will get `io.EOF` error when the connection is lost, which will be treated as an expected error [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/chunkwriting.go#L111) and the blob will be partially uploaded. So, I think you might have to check this on your end.

**Comment by sam701** [comment] 2023-12-01 21:11
My current fix is to wrap the `http.Request.Body` reader into a custom reader that replaces `io.UnexpectedEOF` with a custom error that is is not overwritten by `io.ReadFull` call as discussed above. But it is rather a hack.

**Comment by souravgupta-msft** [comment] 2023-12-04 09:28
This is a good point. Let me discuss this with my team as well.

**Closed** 2023-12-08 04:23 UTC
Labels: Storage, Client, customer-reported, needs-team-attention

**Comment by souravgupta-msft** [comment] 2023-12-08 04:25
The fix has been merged and will be part of the next release.

**Comment by sam701** [comment] 2023-12-08 10:29
@souravgupta-msft  Thank you for implementing!
