### ISSUE TITLE
Request Date Header Too Old - EventHub Subscription

### ISSUE THREAD

**Issue by halspang** [Azure/azure-sdk-for-go#20850] opened 2023-05-12 23:03 UTC
### Bug Report

**What went wrong:**
Error with authentication header being too old while trying to subscribe to an EventHub.

**Error:**
```
{"app_id":"pubsub-workflow","component":"longhaul-eh-glacial (pubsub.azure.eventhubs/v1)","instance":"pubsub-workflow-app-574f464684-lptn2","level":"error","msg":"Error from event processor: GET https://longhaulstorageaccount.blob.core.windows.net/releaselonghaulglacialehcontainer\n--------------------------------------------------------------------------------\nRESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nERROR CODE: AuthenticationFailed\n--------------------------------------------------------------------------------\n﻿\u003c?xml version=\"1.0\" encoding=\"utf-8\"?\u003e\u003cError\u003e\u003cCode\u003eAuthenticationFailed\u003c/Code\u003e\u003cMessage\u003eServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:b19acee0-201e-003a-0f54-846ba5000000\nTime:2023-05-11T22:03:09.8072250Z\u003c/Message\u003e\u003cAuthenticationErrorDetail\u003eRequest date header too old: 'Thu, 11 May 2023 21:46:57 GMT'\u003c/AuthenticationErrorDetail\u003e\u003c/Error\u003e\n--------------------------------------------------------------------------------\n","scope":"dapr.contrib","time":"2023-05-11T22:03:09.827527499Z","type":"log","ver":"1.10.6-rc.1"}
{"app_id":"pubsub-workflow","component":"longhaul-eh-glacial (pubsub.azure.eventhubs/v1)","instance":"pubsub-workflow-app-574f464684-lptn2","level":"error","msg":"Error processing events from partition client: error receiving events: client has been closed by user","scope":"dapr.contrib","time":"2023-05-11T22:03:13.084921537Z","type":"log","ver":"1.10.6-rc.1"}
```

**Relevant imports:**
```go
"github.com/Azure/azure-sdk-for-go/sdk/azcore"
"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
"github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs"
"github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs/checkpoints"
"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/container"
```

**SDK Version:** 
github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs v0.4.0

**Go version:**
1.20

**What I expect:**
In the case of this authentication error, it looks like the header got to be ~15 minutes old. To me, this would imply that we hit some connectivity issue/set of retries that went on for long enough that the header aged out of its bounds. I would expect that the internal retries would generate this header with each request.

**Env/Repro:**
These are apps running on an AKS cluster. It's a test cluster that has a workflow with 4 separate connections to EH. Each of these connections sees a different publish rate.
- Every 10 seconds
- Every 5 minutes
- Every 1 hour
- Every 12 hours

After running continuously for 7 days, the EH which receives events every 12 hours had the above issue and then stopped connecting. Not reconnecting could be our side (investigating) but the retry feels like it should be brought up. 

Please let me know if you need any more information!

**Comment by richardpark-msft** [comment] 2023-05-13 00:56
It looks like the actual error is coming back from azblob, which we use in azeventhubs. 

@chlowell, @jhendrixMSFT: I recall us discussing a failure mode where some headers would not be restored properly on failure. Does this look like a similar case?

(a little reformatting of the error to make it more obvious)
```
(pubsub.azure.eventhubs/v1)","instance":"pubsub-workflow-app-574f464684-lptn2","level":"error","msg":"

Error from event processor: GET https://longhaulstorageaccount.blob.core.windows.net/releaselonghaulglacialehcontainer
\n--------------------------------------------------------------------------------
\n
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n
ERROR CODE: AuthenticationFailed\n
--------------------------------------------------------------------------------\n﻿
\u003c?xml version=\"1.0\" encoding=\"utf-8\"?\u003e\u003cError\u003e\u003cCode\u003eAuthenticationFailed\u003c/Code\u003e\u003cMessage\u003eServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:b19acee0-201e-003a-0f54-846ba5000000\nTime:2023-05-11T22:03:09.8072250Z\u003c/Message\u003e\u003cAuthenticationErrorDetail\u003eRequest date header too old: 'Thu, 11 May 2023 21:46:57 GMT'\u003c/AuthenticationErrorDetail\u003e\u003c/Error\u003e
```

**Comment by richardpark-msft** [comment] 2023-05-13 00:57
BTW, @halspang, what kind of authentication are you using? Is it a TokenCredential, connection string or a shared key credential?

**Comment by jhendrixMSFT** [comment] 2023-05-15 15:23
The missing headers issue is specific to how the key vault challenge policy works, so it isn't applicable here.

**Comment by halspang** [comment] 2023-05-15 16:20
> BTW, @halspang, what kind of authentication are you using? Is it a TokenCredential, connection string or a shared key credential?

@richardpark-msft - This was using a connection string for auth.

**Comment by richardpark-msft** [comment] 2023-05-16 02:17
Hey @halspang , this is a really old version of the library which was vendoring a pre-release version of azblob.

Can you reproduce this using the latest azeventhubs (which has just been made GA)? I'd like to make sure we're not chasing an old ghost.

**Comment by halspang** [comment] 2023-05-18 14:02
@richardpark-msft - We've updated the library and are running our tests again. Last time it took 7 days so we'll see if the error reproduces.

**Comment by richardpark-msft** [comment] 2023-08-23 23:57
@halspang, were you able to repro this with the newer library?

**Comment by halspang** [comment] 2023-08-24 16:58
@richardpark-msft - We were not able to reproduce anything with the newer library. Seems like this is all set then?

**Comment by richardpark-msft** [comment] 2023-08-24 18:10
Closing for now, we can reopen if you see it again.

**Closed by richardpark-msft** 2023-08-24 18:10 UTC
Labels: question, Event Hubs, customer-reported, needs-team-attention
