### ISSUE TITLE
Data Factory Schedule Trigger - Timezone doesn't appear to do anything 

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-sdk-for-go#6244] opened 2019-11-04 04:29 UTC
### Bug Report

- import path of package in question `github.com/Azure/azure-sdk-for-go/services/datafactory/mgmt/2018-06-01/datafactory`
- SDK version e.g. `34.1.0`
- `go version go1.12.5 darwin/amd64`

### Issue

The Data Factory Schedule Trigger has a timezone attribute in `ScheduleTriggerRecurrence` but it doesn't appear to do anything. No matter the value I pass, whether a valid timezone or not, only seems to be stored in the API but never acted upon. 

### Reproduce
Pass any value into the timezone attribute to see that it doesn't affect `end_time` or `start_time`

```
{
	"id": "/subscriptions/xxxx-xxxxx-xxxx-xxxx/resourceGroups/example/providers/Microsoft.DataFactory/factories/example/triggers/example",
	"name": "example",
	"type": "Microsoft.DataFactory/factories/triggers",
	"properties": {
		"type": "ScheduleTrigger",
		"typeProperties": {
			"recurrence": {
				"frequency": "Minute",
				"interval": 1,
				"startTime": "2019-11-04T12:52:55Z", // Want PST but read as UTC 
				"timeZone": "Pacific Standard Time"
			}
		},
		"runtimeState": "Stopped"
	},
	"etag": "xxxxx-xxxx-xxxxx-xxxx"
}
```

**Comment by ankanjan** [comment] 2019-11-26 00:30
As noted in the documentation here https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger, we only support UTC for now. The value of the timezone property does not matter.

"timeZone | The time zone. Currently, only the UTC time zone is supported."

**Comment by ArcturusZhang** [comment] 2019-12-03 07:39
Close this issue since this is by design of the service side.

**Closed by ArcturusZhang** 2019-12-03 07:39 UTC
Labels: Data Factory, Service Attention, customer-reported
