### ISSUE TITLE
Support `skiptoken` and `top` in cost-management

### ISSUE THREAD

**Issue by jinxue-w** [Azure/azure-sdk-for-go#8319] opened 2020-04-15 13:10 UTC
# Feature Request

Support `skiptoken` and `top` in the `Usage` request of cost-management [here](https://github.com/Azure/azure-sdk-for-go/blob/68d483faf640e457e33779443ebc5108b900d3ff/services/costmanagement/mgmt/2019-10-01/costmanagement/query.go#L65)

**Comment by jinxue-w** [comment] 2020-04-16 13:10
我按照https://github.com/jinxue-w/azure-sdk-for-go/commit/5b9efdba372583f738f3f11f7c168c9ebae5ea6b上面添加翻页功能之后，发现翻页统计结果和全量统计结果是不一样的，https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage上面应该是和我自己修改后代码得出的结果是一样的，而且在dataset中添加sorting，得不到想要的结果

**Comment by ms-premp** [comment] 2020-06-03 17:19
$top is supported in query API.
$skiptoken is by design not suppported. This is pretty standard with azure APIs, The response will include nextLink as continuous token, for clients to follow and get the desired page. $skiptoken is not supported.

**Comment by ms-premp** [comment] 2020-06-05 15:04
You can still achieve paging using the skiptoken.

**Comment by ramaganesan-rg** [comment] 2020-06-29 00:36
Closing this issue since its by-design,

**Closed by ramaganesan-rg** 2020-06-29 00:36 UTC
Labels: Cost Management, Mgmt, customer-reported, feature-request
