### ISSUE TITLE
Calling APIs with bad credentials results in call getting stuck

### ISSUE THREAD

**Issue by kirankumarbv** [Azure/azure-sdk-for-go#870] opened 2017-11-21 18:38 UTC
Hi,

I was writing negative tests where I load invalid Client, secret key and subscription id. I did not get any error when I tried to get SP Token. Furthermore when I called vmclient. ListAll() method. Instead of returning error( In my opinion, it should return error at the previous step itself), the call got stuck. I had to manually kill the program.  Please let me know if this is a bug or whether there is something I should take care of before calling API with invalid credentials.

**Comment by marstr** [comment] 2017-11-22 19:23
Howdy, sorry you're running into trouble! This one is totally on us.

There is a known issue with returning multiple channels as the mechanism for supporting LROs. It can cause the behavior you're mentioning. @jhendrixMSFT created a fix, and we're going to be releasing it with v12.0.0-beta. (The current goal is to release that on Monday, the 27th.)

**Comment by jhendrixMSFT** [comment] 2017-11-22 21:32
This is orthogonal to LROs as I hit this yesterday.  Part of the problem is that we don't do any validation of parameters up front so things like passing empty strings can cause the same symptom.  The other part is that our retry logic doesn't properly handle failed authentication which needs to be fixed.

**Comment by kirankumarbv** [comment] 2017-11-22 23:22
Will this fix also going to be released next monday?

**Comment by jhendrixMSFT** [comment] 2017-11-22 23:24
Yeah the fix will be included with the v12 release.

**Comment by kirankumarbv** [comment] 2017-12-02 00:45
What is the updated release of this fix? I believe the v12 version has not been released yet.

**Comment by jhendrixMSFT** [comment] 2017-12-04 16:59
Unfortunately v12 has been delayed.  In the interim I will see if we can release an updated go-autorest for inclusion in a patch bump of the SDK.  Also note that if you "go get" the go-autorest repo you can get this fix now.

**Comment by kirankumarbv** [comment] 2017-12-04 23:48
Hi I see that my latest go-autorest has the below changelog

### Bug Fixes

- Validate parameters when creating credentials.
- Don't retry requests if the returned status is a 401 (http.StatusUnauthorized) as it will never succeed.

However, when I call the API with bad credentials, it is still getting stuck like before. Any idea why this might be happening?

**Comment by jhendrixMSFT** [comment] 2017-12-04 23:57
Sorry no idea without any further information.  Have you tried setting a breakpoint in ServicePrincipalToken.refreshInternal() to see what happens?  The request to refresh the token should fail and return a TokenRefreshError, see https://github.com/Azure/go-autorest/blob/cab8279ba5cd5e165c58201f798712f2ec0f49d6/autorest/adal/token.go#L478.

**Comment by kirankumarbv** [comment] 2017-12-05 18:24
Hi,

From what I have debugged, When we call an API like List or ListAll() etc,  with an invalid credentials, even after the above code returns an error, the code tries to go through delayed retry method.  Highlighted below. 

(dlv) n
> github.com/Azure/go-autorest/autorest.DoRetryForStatusCodes.func1.1() /home/kiranupadya/godep/src/github.com/Azure/go-autorest/autorest/sender.go:231 (PC: 0x6a23a7)
   226:					if err == nil && !ResponseHasStatusCode(resp, codes...) || ResponseHasStatusCode(resp, http.StatusUnauthorized) {
   227:						return resp, err
   228:					}
   **229:					delayed := DelayWithRetryAfter(resp, r.Cancel)**
   230:					if !delayed {
=> 231:						DelayForBackoff(backoff, attempt, r.Cancel)
   232:					}
   233:				}
   234:				return resp, err
   235:			})
   236:		}
(dlv) n
> github.com/Azure/go-autorest/autorest.DoRetryForStatusCodes.func1.1() /home/kiranupadya/godep/src/github.com/Azure/go-autorest/autorest/sender.go:218 (PC: 0x6a23d3)
   213:		return func(s Sender) Sender {
   214:			return SenderFunc(func(r *http.Request) (resp *http.Response, err error) {
   215:				rr := NewRetriableRequest(r)
   216:				// Increment to add the first call (attempts denotes number of retries)
   217:				attempts++
=> 218:				for attempt := 0; attempt < attempts; attempt++ {
   219:					err = rr.Prepare()
   220:					if err != nil {
   221:						return resp, err
   222:					}
   223:					resp, err = s.Do(rr.Request())

This retry is what is causing a hang like behaviour in the case of calling an API with invalid credentials. Does this help?

**Comment by jhendrixMSFT** [comment] 2017-12-05 18:29
On line 226 what is the value for resp.StatusCode?  It should be 401 (http.StatusUnauthorized).

**Comment by kirankumarbv** [comment] 2017-12-05 18:31
resp.StatusCode is some garbage value. 
(dlv) p resp
*net/http.Response {
	Status: "dH�\f%����H�D$�H;A\x10\x0f��\x02\x00\x00H���\x00\x00\x00H��$�\x00\x00\x00H��$�\x00\x00\x00H�T$hH�B\bH�D$pH�J...+842352709868 more",
	**StatusCode: 11696288,**
	Proto: "�`�\x00\x00\x00\x00\x00@Q\" �\x00\x00\x00`i�\x00\x00\x00\x00\x00P�( �\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00XG�\r\x00\x00\x00\x00(.��\x00\x00\x00...+11701326 more",
	ProtoMajor: 6,
	ProtoMinor: 6,
	Header: (unreadable input/output error),
	Body: (unreadable invalid interface type: could not find str field),
	ContentLength: 9748256,
	TransferEncoding: []string len: 10, cap: 842353203008, [(unreadable could not read string at 0x6567412d72657355 due to input/output error),(unreadable could not read string at 0x615e3a5b5d3a6d75 due to input/output error),(unreadable could not read string at 0x5d3a69696373615e due to input/output error),(unreadable could not read string at 0x746e635e3a5b5d3a due to input/output error),...+6 more],

**Comment by jhendrixMSFT** [comment] 2017-12-05 18:34
Hmm I wonder if that's just delve misbehaving.  If you print the value to the console do you see the same thing?

**Comment by kirankumarbv** [comment] 2017-12-05 18:57
Even if delve was misbehaving, if the status code was 401, I believe the execution of the next lines of code would not have happened. It would have returned an error to the caller. 
I did print the resp.StatusCode to the console and I get this.

**2017/12/05 10:54:23 /home/kiranupadya/godep/src/github.com/Azure/go-autorest/autorest/sender.go:226: RESPONSE CODE============== 400**

**Comment by jhendrixMSFT** [comment] 2017-12-05 19:01
Interesting, in my testing I didn't run across a case where the authentication returned a 400.  Can you share your repro program?  I'd like to understand how it works so I can update go-autorest accordingly.

**Comment by kirankumarbv** [comment] 2017-12-05 19:29
Sure.

keys.subscriptionId = "myBadSubscriptionID"
keys.tenantId = "myBadTenantID"
keys.clientId = "myBadClientID"
keys.clientSecret = "myBadClientSecret"

oauthConfig, autherr := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, keys.tenantId)
spt, spterr := adal.NewServicePrincipalToken(*oauthConfig,
                        keys.clientId,
                        keys.clientSecret,
                        azure.PublicCloud.ResourceManagerEndpoint)

acc.vmClient = compute.NewVirtualMachinesClient(keys.subscriptionId)
acc.vmClient.Authorizer = autorest.NewBearerAuthorizer(spt)
resp, err = acc.vmClient.ListAll()

**Comment by jhendrixMSFT** [comment] 2017-12-05 19:56
Thanks I understand it now, I will get this fixed today.

**Comment by jhendrixMSFT** [comment] 2017-12-06 23:12
This is fixed in go-autorest v9.5.0.  Thanks for your help with the investigation.
https://github.com/Azure/go-autorest/releases/tag/v9.5.0

**Closed** 2017-12-07 18:34 UTC

**Comment by kirankumarbv** [comment] 2017-12-07 23:40
Thanks for fixing it.

**Comment by karthiksubraveti** [comment] 2018-06-05 19:03
When i currently attempt using bad credentials in a negative test, i get back the response as invalid request - For example:
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/TEST_AUTH_FAIL/resourcegroups?api-version=2018-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant name 'test_auth_fail' specified is not a valid DNS name and not valid external domain format.
Is this the expected output ? 

Is there any API that i can invoke directly on authorizer to verify if my credentials are valid or not ?

**Comment by jhendrixMSFT** [comment] 2018-06-05 19:14
@karthiksubraveti You can call Refresh() on the ServicePrincipalToken and if err is non-nil it should be an adal.TokenRefreshError.  Here's an example.
```go
func main() {
	tenantID := "bad tenant ID"
	oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)
	if err != nil {
		panic(err)
	}
	clientID := "bad client ID"
	clientSecret := "bad secret"
	spToken, err := adal.NewServicePrincipalToken(*oauthConfig, clientID, clientSecret, azure.PublicCloud.ResourceManagerEndpoint)
	if err != nil {
		panic(err)
	}

	err = spToken.Refresh()
	if err != nil {
		tre := err.(adal.TokenRefreshError)
		fmt.Printf("%+v\n", tre)
	}
}
```

**Comment by karthiksubraveti** [comment] 2018-06-05 20:08
Great. Thanks for the quick response.
