### ISSUE TITLE
recovery service vault configs seem to be in the wrong package?

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#7279] opened 2020-01-31 22:10 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
```
	"github.com/Azure/azure-sdk-for-go/services/recoveryservices/mgmt/2016-06-01/recoveryservices"
	"github.com/Azure/azure-sdk-for-go/services/recoveryservices/mgmt/2019-05-13/backup"
```

- SDK version e.g. `master`, `latest`, `18.1.0`
```
[14:05:36] kt@katbook:~/hashi/tf/azure/azurerm▸kt/recovery-soft-delete$ cat go.mod | egrep "(autorest|Azure)"
	github.com/Azure/azure-sdk-for-go v38.1.0+incompatible
	github.com/Azure/go-autorest/autorest v0.9.3
	github.com/Azure/go-autorest/autorest/date v0.2.0
[14:05:50] kt@katbook:~/hashi/tf/azure/azurerm▸kt/recovery-soft-delete$
```
- output of `go version`
```
[14:05:50] kt@katbook:~/hashi/tf/azure/azurerm▸kt/recovery-soft-delete$ go version
go version go1.13.6 darwin/amd64
```

- What happened?
The vault config client and sdk seem to be in the backup package instead of the recovery services package. (also storage type doesn't seem to work but thats another issue). This seems strange given the vaults client is in the recovery services package.
```
recoveryservices.VaultsClient
backup.ResourceVaultConfigsClient
```
These work on the same resource, so why are they in different packages? they even hit the same path almost:
```
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}"
"/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/backupconfig/vaultconfig"
```

- What did you expect or want to happen?
All the vault operation clients and calls to be in the same logical place:
```
recoveryservices.VaultsClient
recoveryservices.ResourceVaultConfigsClient
```
and arguably `ResourceVaultConfigsClient` should be called `VaultConfigsClient` but that's not as big of deal.

**Comment by ArcturusZhang** [comment] 2020-02-04 02:36
Hi @katbyte thanks for this issue.
Those two resources come from different folder in specs:
* Vaults come from [recoveryservices](https://github.com/Azure/azure-rest-api-specs/blob/b91c2b941d20647ccd41d5857d8a0b8ec020e2a0/specification/recoveryservices/resource-manager/Microsoft.RecoveryServices/stable/2016-06-01/vaults.json#L193)
* BackupConfigs come from [recoveryservicebackup](https://github.com/Azure/azure-rest-api-specs/blob/b91c2b941d20647ccd41d5857d8a0b8ec020e2a0/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2019-05-13/bms.json#L21)
They indeed share the same namespace (`Microsoft.RecoveryServices`) but they are different swagger, and not checked whether they could come together. To avoid any possible collisions, they are put in different package under recoveryservices folder in go SDK.

**Comment by katbyte** [comment] 2020-02-04 03:43
@ArcturusZhang, I understand they are in different areas in the specs, but i think configs is in the wrong place? The configs struct configures more then just soft delete, does enhanced security and storage type? So it seems like it would make more sense to reside in the recoveryservices folder/package?

**Comment by ArcturusZhang** [comment] 2020-02-04 07:48
> @ArcturusZhang, I understand they are in different areas in the specs, but i think configs is in the wrong place? The configs struct configures more then just soft delete, does enhanced security and storage type? So it seems like it would make more sense to reside in the recoveryservices folder/package?

Well, without the changes from the swagger side, we cannot do this. Here is the reason:
When the code generator generates the go SDK from swaggers, it will generate some common files (for example the `client.go` and `model.go` files). One swagger directory has a set of those common files plus some other file with various of the actions (for instance `vaults.go` in `recoveryservices`). The problem is we cannot target two different swagger directory to same folder during generating the SDK. The common files from one directory of swagger will override the other's common files.

Therefore, to do this, we must change the structure of the swagger repo. Or how about we change the package name of `recoveryservicebackup` from `backup` to `recoveryservicebackup`. In this way we can at least see the relation between those two packages.

**Comment by tombuildsstuff** [comment] 2020-02-04 08:03
@ArcturusZhang I think @katbyte's point was that this method probably wants moving in the Swagger since it's related to Recovery Services as a whole, rather than Backup specifically - rather than renaming the directory?

**Comment by katbyte** [comment] 2020-02-04 19:49
yep, it seems like the method has ended up in the wrong package somehow

**Comment by ArcturusZhang** [comment] 2020-02-05 02:09
> @ArcturusZhang I think @katbyte's point was that this method probably wants moving in the Swagger since it's related to Recovery Services as a whole, rather than Backup specifically - rather than renaming the directory?

Well, this is the root cause, but out of my scope. Please let me have a communication with the corresponding service teams about this.

**Comment by ArcturusZhang** [comment] 2020-02-05 11:26
Hi @katbyte and @tombuildsstuff since the root cause of this issue is in the swagger, and out of the scope of go SDK, I have created an [issue](https://github.com/Azure/azure-rest-api-specs/issues/8308) in the rest api specs repo to track this.
Therefore I will close the issue here. Thanks!

**Closed by ArcturusZhang** 2020-02-05 11:26 UTC
Labels: Mgmt, Recovery Services, Recovery Services Backup, customer-reported
