### ISSUE TITLE
GetChatCompletions stop returning PromptTokens and Completion Token data

### ISSUE THREAD

**Issue by rautscode** [Azure/azure-sdk-for-go#22372] opened 2024-02-10 16:24 UTC
### Bug Report

- import path of package in question: [GO AzOpenAI SDK: v0.4.1](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai@v0.4.1)
- SDK version e.g. `v0.4.1)`
- output of `go version 1.21.5`

- What happened?

I've used the sdk for Az Open AI for go for quite a bit. Last night my API was working as expected and on every prompt Az Open AI in azure returned proper data for completion tokens int and prompt tokens int. I didn't make any code changes.  Below is a screenshot with the data in the database. 

![image](https://github.com/Azure/azure-sdk-for-go/assets/124793347/5cd03c31-4012-41c8-846c-ff2169d18bef)

```
These are the options I send: 
	options := azopenai.ChatCompletionsOptions{
		Messages:         messages,
		DeploymentName:   &modelDeploymentID,
		Temperature:      &temp,
		TopP:             &topP,
		FrequencyPenalty: &freqPenalty,
		PresencePenalty:  &presPenalty,
		MaxTokens:        maxTokens,
		Stop:             stop,
	}



	log.Println("getting chat completion from azure open ai api")
	resp, err := client.GetChatCompletions(ctx, options, nil)



```
I also see that there are multiple ways to access child data objects, but none work anymore:

Directly from `.Usage.~` 
![image](https://github.com/Azure/azure-sdk-for-go/assets/124793347/cb0e07ab-901b-43b8-8a85-ec1280d07fa1)

Or `.ChatCompletions.Usage.~`
![image](https://github.com/Azure/azure-sdk-for-go/assets/124793347/cbb9fcc8-f942-4ef2-934d-c4ffcb179e55)

I get back the response but now only the prompt response message, I don't get the usage data back. I wonder if anyone else is experiencing this issue.

**Comment by m-saksena** [comment] 2024-03-13 16:46
Seeing the same on `v0.5.0` - `CompletionsUsage` is nil.

**Comment by richardpark-msft** [comment] 2024-03-14 00:13
(@rautscode, sorry that I didn't get back to you on this.)

@m-saksena, @rautscode, just want to make sure:

- Which model are you using? 
- @m-saksena, are also using ChatCompletions, as @rautscode is, or just Completions?

**Comment by m-saksena** [comment] 2024-03-14 10:13
> * Which model are you using?
> * @m-saksena, are also using ChatCompletions, as @rautscode is, or just Completions?

@richardpark-msft I am using the `gpt-4-1106-preview` model and the `GetChatCompletionsStream` API.

**Comment by pkrauss-prot** [comment] 2024-03-20 13:12
I too can confirm this behaviour in the latest 5.0.0, `GetChatCompletionsStream` no longer returns token metrics, as the property is nil.

**Comment by richardpark-msft** [comment] 2024-03-20 23:31
I missed that both of you (@m-saksena, @pkrauss-prot) are using the streaming APIs. Like OpenAI itself, we don't provide those values since they're not part of the streaming API.  

My understanding is that people will use a package like tiktoken (it appears there are some Go ports for this), to do the token calculation on the client-side.

**Comment by richardpark-msft** [comment] 2024-03-20 23:35
@rautscode, I'm still unable to reproduce your bug with the non-streaming API. 

Looking at the API nothing appears to have changed so this seems like something that's server-related, and not the SDK itself. Your next step should be to file an Azure support request, so they can look at your Azure OpenAI resource and see what is going on.

https://github.com/Azure/azure-sdk-for-go/blob/main/SUPPORT.md#how-to-file-issues-and-get-help

Closing this issue for now, but please re-open if you have any other questions or concerns.

**Comment by richardpark-msft** [comment] 2024-03-20 23:38
> I missed that both of you (@m-saksena, @pkrauss-prot) are using the streaming APIs. Like OpenAI itself, we don't provide those values since they're not part of the streaming API.
> 
> My understanding is that people will use a package like tiktoken (it appears there are some Go ports for this), to do the token calculation on the client-side.

I've filed an issue to track this doc update: https://github.com/Azure/azure-sdk-for-go/issues/22624

**Closed** 2024-03-23 03:00 UTC
Labels: question, customer-reported, needs-team-attention, OpenAI
