### ISSUE TITLE
GetSecretsComplete fails to page on empty first response

### ISSUE THREAD

**Issue by debben** [Azure/azure-sdk-for-go#10711] opened 2020-06-22 21:02 UTC
### Bug Report

- import path of package in question
services\keyvault\v7.0\keyvault

- SDK version e.g. `master`, `latest`, `18.1.0`
Reproduced with v43.3.0, v39.1.0, v19.1.0
- output of `go version`
go version go1.11.4 windows/amd64

- What happened?
When calling client.GetSecretsComplete, some keyvaults will respond to the first request to `/secrets?api-version=7.0` with:
```
{
    "value": [],
    "nextLink": "https://<keyvault name>.vault.azure.net:443/secrets?api-version=7.0&$skiptoken=<some skip token>"
}
```

 the result object returned by GetSecretsComplete shows as there being no secrets when there are in fact still secrets.

## What did you expect or want to happen?
I've looked at the chrome inspector when using the azure portal UI for listing secrets for this same keyvault. Like my app, the response to `/secrets?api-version=7.0` is an empty value array and a nextLink. The next request from the UI is a call to that nextLink in which the response contains a listing of the secrets in the keyvault.

I've also inspected the traffic for keyvault secrets list requests coming from the azure cli for this same keyvault. Again, the first response has an empty array, but then the implementation picks up that there's a nextLink and calls it to get the next page.

##  How can we reproduce it?
Good question. I don't really know why some of the keyvaults I work with respond to initial `/secrets?api-version=7.0 calls` with an empty value array and nextLink that needs to be requested before seeing any secrets. Sometimes a given keyvault will respond to the first request with a populated values array and then revert to the behavior I've described above. 
I've actually submitted Azure support tickets to try and understand why there's a difference in behavior between keyvaults but nonetheless it seems that the azure-sdk-for-go implementation sees secrets pagination as done on first reciept of empty values even when a nextLink is included in the response.

**Comment by ArcturusZhang** [comment] 2020-06-29 06:31
Hi @debben thanks for this issue!

But I have to close this issue because this issue is a duplicate of issue #9510 and I have made a PR to the code generator that tries to fix this. Could you please track this issue in #9510 ? Thanks!

**Closed by ArcturusZhang** 2020-06-29 06:31 UTC
Labels: customer-reported, needs-triage, question
