### ISSUE TITLE
KeyVault Delete Failure

### ISSUE THREAD

**Issue by WTIGER001** [Azure/azure-sdk-for-go#18321] opened 2022-06-06 19:58 UTC
### Bug Report / Question

I am trying to use `BeginDeleteSecret` in the `azsecrets.Client`. My KeyVault does not have Soft Delete turned on. My code is as follows:

My go mod contains

```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.7.1
```

```go
import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets"
)

// ... Create Client and authenticate


_, err := Client.BeginDeleteSecret(ctx, "test", nil)
```

I am always getting an error of: 
```
GET ****
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: NotSupported
--------------------------------------------------------------------------------
{
  "error": {
    "code": "NotSupported",
    "message": "Operation \"get\" is not enabled for this vault."
  }
}
--------------------------------------------------------------------------------
```

I have tracked this down to line 348 of the client.go file

```go
getResp, err := c.kvClient.GetDeletedSecret(ctx, c.vaultUrl, name, nil)
```

The actual API method of `DeleteSecret` works, but it is the `GetDeletedSecret` that does not work. Is that because I do not have soft delete turned on? 

I think I would prefer a direct way of calling 'DeleteSecret' without the polling...

**Comment by navba-MSFT** [comment] 2022-06-08 06:53
@WTIGER001 Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will update this thread once we have more details on this.

**Comment by navba-MSFT** [comment] 2022-06-08 10:27
@WTIGER001 I wasn't able to reproduce the issue. I was able to call the BeginDeleteSecret and delete my secret from KV.

>[BeginDeleteSecret](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets#Client.BeginDeleteSecret) requests Key Vault delete a secret, returning a poller which allows you to wait for the deletion to finish. Waiting is helpful when the vault has [soft-delete](https://docs.microsoft.com/azure/key-vault/general/soft-delete-overview) enabled, and you want to purge (permanently delete) the secret as soon as possible. When [soft-delete](https://docs.microsoft.com/azure/key-vault/general/soft-delete-overview) is disabled, BeginDeleteSecret itself is permanent.

More Info [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets#section-readme).
```
package main

import (
	"context"
	"fmt"
	"log"
	"time"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets"
)

func main() {

	mySecretName := "MySampleKVSecret"
	mySecretValue := "MySecretValue"
	keyVaultName := "MyKVName"
	keyVaultUrl := fmt.Sprintf("https://%s.vault.azure.net/", keyVaultName)

	//Create a credential using the NewDefaultAzureCredential type.
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}

	//Establish a connection to the Key Vault client
	client, err := azsecrets.NewClient(keyVaultUrl, cred, nil)
	if err != nil {
		log.Fatalf("failed to connect to client: %v", err)
	}

	//Create a secret
	_, err = client.SetSecret(context.TODO(), mySecretName, mySecretValue, nil)
	if err != nil {
		log.Fatalf("failed to create a secret: %v", err)
	}

	//Delete a secret 
	respDel, err := client.BeginDeleteSecret(context.TODO(), mySecretName, nil)
        if err != nil {
		panic(err)
	}

         // If you do not care when the secret is deleted, you do not have to
	// call resp.PollUntilDone. If you need to know when it's done use
	// the PollUntilDone method.

	_, err = respDel.PollUntilDone(context.TODO(), time.Second)
	if err != nil {
		log.Fatalf("failed to delete secret: %v", err)
	}

	fmt.Println(mySecretName + " has been deleted\n")
}
```

**Comment by chlowell** [comment] 2022-06-09 20:00
This is a bug. Polling is optional but `BeginDeleteSecret` [always calls `GetDeletedSecret`](https://github.com/Azure/azure-sdk-for-go/blob/sdk/keyvault/azsecrets/v0.7.1/sdk/keyvault/azsecrets/client.go#L348). Your intent is still realized because the client requests the deletion first, but you can't avoid this error when deleting from a vault with soft-delete disabled. This is fixed on our main branch and so won't happen in the next release (coming soon). In the meantime you can work around this by handling the error. For example:
```go
import "github.com/Azure/azure-sdk-for-go/sdk/azcore"

_, err := client.BeginDeleteSecret(ctx, "test", nil)
if err != nil {
	var respErr *azcore.ResponseError
	if !errors.As(err, &respErr) || respErr.StatusCode != 400 {
		// TODO: unexpected error; do something
	}
	// nothing to do, got the expected error
}
```

**Comment by navba-MSFT** [comment] 2022-06-10 02:38
@chlowell Thanks for pointers.

@WTIGER001 Could you please try the [above suggested](https://github.com/Azure/azure-sdk-for-go/issues/18321#issuecomment-1151563277) workaround until the fix is released and let us know if that helps? Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-06-13 04:24
@WTIGER001 Could you please let me know if you have tried the above suggested workaround ? Awaiting your reply.

**Comment by johanburati** [comment] 2022-06-13 08:52
I have the same issue, I tried @navba-MSFT  code with @chlowell's  work around:

```
package main

import (
        "context"
        "fmt"
        "log"
        "time"
        "errors"

        "github.com/Azure/azure-sdk-for-go/sdk/azcore"
        "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
        "github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets"
)

func main() {

        mySecretName := "MySampleKVSecret"
        mySecretValue := "MySecretValue"
	keyVaultName := "MyKVName"
        keyVaultUrl := fmt.Sprintf("https://%s.vault.azure.net/", keyVaultName)

        //Create a credential using the NewDefaultAzureCredential type.
        cred, err := azidentity.NewDefaultAzureCredential(nil)
        if err != nil {
                log.Fatalf("failed to obtain a credential: %v", err)
        }

        //Establish a connection to the Key Vault client
        client, err := azsecrets.NewClient(keyVaultUrl, cred, nil)
        if err != nil {
                log.Fatalf("failed to connect to client: %v", err)
        }

        //Create a secret
        _, err = client.SetSecret(context.TODO(), mySecretName, mySecretValue, nil)
        if err != nil {
                log.Fatalf("failed to create a secret: %v", err)
}

        //Delete a secret
        respDel, err := client.BeginDeleteSecret(context.TODO(), mySecretName, nil)
        if err != nil {
                var respErr *azcore.ResponseError
                if !errors.As(err, &respErr) || respErr.StatusCode != 400 {
                        // TODO: unexpected error; do something
                        log.Fatalf("unexpected error: %v", err)
                }
                // nothing to do, got the expected error
        }

         // If you do not care when the secret is deleted, you do not have to
        // call resp.PollUntilDone. If you need to know when it's done use
        // the PollUntilDone method.

        _, err = respDel.PollUntilDone(context.TODO(), time.Second)
        if err != nil {
                log.Fatalf("failed to delete secret: %v", err)
        }

        fmt.Println(mySecretName + " has been deleted\n")
}
```
If we do not handle the error at the `// nothing to do, got the expected error` line, then we get a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x76fa5b]

goroutine 1 [running]:
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets.(*DeleteSecretPoller).Poll(0x0, {0x8c9228, 0xc000124008})
        /home/job/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azsecrets@v0.7.1/client.go:277 +0xbb
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets.(*DeleteSecretPoller).PollUntilDone(0x0, {0x8c9228, 0xc000124008}, 0xc0001e2168?)
        /home/job/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azsecrets@v0.7.1/client.go:301 +0x85
main.main()
        /home/job/go/secret-test/main.go:55 +0x2b8
exit status 2
```
Am I missing something ?

**Comment by johanburati** [comment] 2022-06-15 03:43
I just enabled soft-delete on my vault and that fixed the issue for me.

**Comment by navba-MSFT** [comment] 2022-06-15 04:17
@WTIGER001 Could you please let us know if you had a chance to try the above suggestion ? Please let us know if you need any further assistance on this or we are good to close this out. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-06-17 10:44
@WTIGER001 The action is currently pending on you to test the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Closed by navba-MSFT** 2022-06-17 10:44 UTC
Labels: bug, KeyVault, Client, customer-reported, needs-author-feedback, CXP Attention

**Comment by WTIGER001** [comment] 2022-06-22 13:31
> This is a bug. Polling is optional but `BeginDeleteSecret` [always calls `GetDeletedSecret`](https://github.com/Azure/azure-sdk-for-go/blob/sdk/keyvault/azsecrets/v0.7.1/sdk/keyvault/azsecrets/client.go#L348). Your intent is still realized because the client requests the deletion first, but you can't avoid this error when deleting from a vault with soft-delete disabled. This is fixed on our main branch and so won't happen in the next release (coming soon). In the meantime you can work around this by handling the error. For example:
> 
> ```go
> import "github.com/Azure/azure-sdk-for-go/sdk/azcore"
> 
> _, err := client.BeginDeleteSecret(ctx, "test", nil)
> if err != nil {
> 	var respErr *azcore.ResponseError
> 	if !errors.As(err, &respErr) || respErr.StatusCode != 400 {
> 		// TODO: unexpected error; do something
> 	}
> 	// nothing to do, got the expected error
> }
> ```

Worked! Sorry it took a while for me to get back to you... Thanks for the help.
