### ISSUE TITLE
SQL Server SDK doesn't validate that user provided a nonempty resource group

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-go#10712] opened 2020-06-23 00:05 UTC
### Bug Report

Go SDK version: `v38.0.0`
Import Path: `"github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/2015-05-01-preview/sql"`

```
serversClient.Get(
		ctx,
		resourceGroupName,
		serverName)
```

Produces the following request:
```
(2020-06-22T16:42:19.8884465-07:00) INFO: REQUEST: GET https://management.azure.com/subscriptions/82acd5bb-4206-47d4-9c12-a65db028483d/resourceGroups//providers/Microsoft.Sql/servers/sqlserver-sample-777?api-version=2015-05-01-preview
User-Agent: Go/go1.14.2 (amd64-linux) go-autorest/v13.0.0 Azure-SDK-For-Go/v38.0.0 sql/2015-05-01-preview azure-service-operator-v1
Authorization: **REDACTED**
```

With the following strange response:
```
(2020-06-22T16:42:20.0761636-07:00) INFO: RESPONSE: 400 https://management.azure.com/subscriptions/82acd5bb-4206-47d4-9c12-a65db028483d/resourceGroups//providers/Microsoft.Sql/servers/sqlserver-sample-777?api-version=2015-05-01-preview
Date: Mon, 22 Jun 2020 23:42:19 GMT
Expires: -1
X-Ms-Failure-Cause: gateway
Content-Type: application/json; charset=utf-8
X-Ms-Request-Id: 221ecaad-526b-47c8-b4d2-3f00e4fbf7fc
X-Ms-Correlation-Request-Id: 221ecaad-526b-47c8-b4d2-3f00e4fbf7fc
X-Ms-Routing-Request-Id: WESTUS:20200622T234220Z:221ecaad-526b-47c8-b4d2-3f00e4fbf7fc
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 561
{"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2015-05-01-preview' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
```

The Azure Storage SDK for Go in contrast has a check that the RG is specified baked into the SDK:
```
if err := validation.Validate([]validation.Validation{
		{TargetValue: resourceGroupName,
			Constraints: []validation.Constraint{{Target: "resourceGroupName", Name: validation.MaxLength, Rule: 90, Chain: nil},
				{Target: "resourceGroupName", Name: validation.MinLength, Rule: 1, Chain: nil},
				{Target: "resourceGroupName", Name: validation.Pattern, Rule: `^[-\w\._\(\)]+$`, Chain: nil}}},
```

**Comment by ArcturusZhang** [comment] 2020-06-29 06:29
Hi @matthchr thanks for this issue!

Our SDKs under the `services` directory is auto-generated using `Autorest` from the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) and so does this SQL package. In some RPs, the service team will add some validations for some of the parameters, but most of them will not and leave the service to panic when received unexpected requests.

Usually there are two cases when the service returns an error message complaining about the api-version:
1. The api-version is indeed wrong. This could hardly happen because the SDK has hard-coded the api-version to the corresponding operations. The only case that thing could go wrong should be something has changed on the service side.
1. The error is not from the api-version, but the values of some path parameters is inappropriate.
A path parameter is a parameter that would go to the request URL, such as `resourceGroupName` and `name`. Sometimes, inappropriate path parameters may change the structure of the URL, when this happens, the service usually returns an `InvalidApiVersionParameter` error. For instance, in your case, resource group name is empty, which makes the URL is missing one segment and may cause the service to recognize `providers` as the resource group name, and because of this the whole URL is messed up. Or sometimes you may could assign name to something with a slash, for instance you put `a/b` as the name, and URL become
```
subscriptions/SUBSID/resourceGroups/group1/providers/Microsoft.Sql/servers/a/b?api-version=2015-05-01-preview
```
which makes the URL has one extra segment. This usually also causes the service to return the `InvalidApiParameter` error.

From the SDK side, we actually cannot do anything to fix this. But I have tagged this issue therefore the corresponding service team may come and have a look at this issue and then they may add some validation rule to the path parameters to avoid this kind of issues.

Thanks!

**Comment by matthchr** [comment] 2020-06-29 17:02
@ArcturusZhang 

> From the SDK side, we actually cannot do anything to fix this. But I have tagged this issue therefore the corresponding service team may come and have a look at this issue and then they may add some validation rule to the path parameters to avoid this kind of issues.

This isn't true.

AutoRest traditionally generates checks automatically for required fields like resourceGroup in most languages - for example [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Generated/ServersOperations.cs#L272) is the autogenerated validation in C#.
[In Python](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_servers_operations.py#L138) (note that the `serializer.url` method throws if the parameter is missing as you can see [here](https://github.com/Azure/msrest-for-python/blob/8f3cd1cb1be0bc2ee9a09f49176fe539d0d4525d/msrest/serialization.py#L723))

So really the question is: Why doesn't the generated go SDK have the same autogenerated validations which other languages have?

**Comment by ArcturusZhang** [comment] 2020-06-30 04:13
Hi @matthchr 
The C# code you referenced only checked if the resource group is null or not, which is a firm requirement of avoiding NPE since the string is a reference type in C#. But it does not check whether it is empty. 
In golang, string is a value type, which could never be nil, therefore we do not to check if it is nil. I assume python SDK should have checked if the parameter is `None` or not but does not check if it is empty.
To confirm this, I wrote this very simple program in python and reproduced this issue:
```
import os
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.compute import ComputeManagementClient

LOCATION = 'westus2'
GROUP_NAME = 'test-python'

subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
credentials = ServicePrincipalCredentials(
        client_id=os.environ['AZURE_CLIENT_ID'],
        secret=os.environ['AZURE_CLIENT_SECRET'],
        tenant=os.environ['AZURE_TENANT_ID']
    )

compute_client = ComputeManagementClient(credentials, subscription_id)

params_create = {
        'location': LOCATION,
        # this does not matter
}

vm_poller = compute_client.virtual_machines.create_or_update(
    '', # assign an empty resource group name
    'test',
    params_create,
)
```
And run this program, you will get similar error message:
```
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidApiVersionParameter
Message: The api-version '2019-12-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```
It is complaining about api-versions since an empty resource group name breaks the structure of the request URL.

As a summary, this is because the swagger does not have the constraint to ensure the input values of the resource group parameter to be non-empty. Therefore all the generated SDK would not have this constraint.

Some of the swaggers have a constraint of regex for its resource name, and, as a result in the corresponding packages, we will validate the input parameter using the same regex which may hopefully avoid this issue.

**Comment by ArcturusZhang** [comment] 2020-06-30 04:19
And finally for your question:
> The Azure Storage SDK for Go in contrast has a check that the RG is specified baked into the SDK

This constraint comes from [here](https://github.com/Azure/azure-rest-api-specs/blob/2e3a8082cbf34602fcf8e544618d57b6d1399d2f/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L3607), and comparing with the same thing in SQL [here](https://github.com/Azure/azure-rest-api-specs/blob/2e3a8082cbf34602fcf8e544618d57b6d1399d2f/specification/sql/resource-manager/Microsoft.Sql/preview/2015-05-01-preview/servers.json#L411) you will notice that this swagger does not have the `pattern`, `maximumLength` or `minimumLength`. Therefore the generated SQL SDK will not have any constraint on this parameter.

Hope this could answer your question.

**Comment by matthchr** [comment] 2020-06-30 04:29
@ArcturusZhang  - thanks, that does answer my question very well!

Agree with your original response then that this is something for the service team - thanks for taking the time to look into the above and explain it to me.

**Comment by lirenhe** [comment] 2021-12-22 08:00
@matthchr, we will close this item and please let us know if you have furthur question related to this.

**Closed** 2022-01-13 08:02 UTC
Labels: SQL, Service Attention, Mgmt, needs-author-feedback, no-recent-activity
