### ISSUE TITLE
Generate GraphClient

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-go#378] opened 2016-08-09 22:56 UTC
See: https://github.com/Azure/azure-sdk-for-go/issues/360

There is a Graph API Swagger, I assume for a subset of the Graph API related to SP/Apps. We should gen the client(s) for this.

**Comment by garimakhulbe** [comment] 2016-09-01 19:04
@mcardosos is looking into this.

**Comment by marstr** [comment] 2017-02-15 23:33
Howdy Cole, there is another issue tracking this one: #456 

Strictly because it has more references to it from PRs, other issues etc, I'm going to close this one. Know in your heart that the other one should have been closed as a duplicate of this one!

**Closed by marstr** 2017-02-15 23:33 UTC
Labels: area/azureresourcemanager
