### ISSUE TITLE
Error in services/preview/sql/mgmt/2015-05-01-preview/sql/models.go

### ISSUE THREAD

**Issue by WilliamMortlMicrosoft** [Azure/azure-sdk-for-go#5598] opened 2019-08-22 21:44 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

services/preview/sql/mgmt/2015-05-01-preview/sql/models.go

in this code:

```
// CreateOrUpdateDB creates or updates a DB in Azure
func (sdk GoSDKClient) CreateOrUpdateDB(properties SQLDatabaseProperties) (result sql.Database, err error) {
	dbClient := getGoCBClient()
	dbProp := SQLDatabasePropertiesToDatabase(properties)

	// check to see if the server exists, if it does then short-circuit
	db, err := dbClient.Get(
		sdk.Ctx,
		sdk.ResourceGroupName,
		sdk.ServerName,
		properties.DatabaseName,
		"serviceTierAdvisors, transparentDataEncryption",
	)
	if err == nil { 
		return db, nil
	}

	future, err := dbClient.CreateOrUpdate(
		sdk.Ctx,
		sdk.ResourceGroupName,
		sdk.ServerName,
		properties.DatabaseName,
		sql.Database{
			Location:           to.StringPtr(sdk.Location),
			DatabaseProperties: &dbProp,
		})
	if err != nil {
		return result, err
	}

	return future.Result(dbClient)
}
```

future.Result *always* returns:

sql.DatabasesCreateOrUpdateFuture#Result: Failure responding to request: StatusCode=404 -- Original Error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}

- What happened?

an error occurs, it seems to be occurring on line 1782 on https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/2015-05-01-preview/sql/models.go

- What did you expect or want to happen?

this error should not be occurring

- How can we reproduce it?

test by calling CreateOrUpdate on a DatabasesClient and then immediately return the future.Result(dbClient) - itll fail

I am aware that it will work if I wait, however when I call CreateOrUpdate on ServersClient for  sql I can return future.Result(serversClient) without any issues

I really dont want to have to block

- Anything we should know about your environment.

**Comment by WilliamMortlMicrosoft** [comment] 2019-08-22 21:53
This code works without issue:

// CreateOrUpdateSQLServer creates a SQL server in Azure
func (sdk GoSDKClient) CreateOrUpdateSQLServer(properties SQLServerProperties) (result sql.Server, err error) {
	serversClient := getGoServersClient()
	serverProp := SQLServerPropertiesToServer(properties)

	// check to see if the server exists, if it does then short-circuit
	server, err := serversClient.Get(
		sdk.Ctx,
		sdk.ResourceGroupName,
		sdk.ServerName,
	)
	if err == nil && *server.State == "Ready" {
		return server, nil
	}

	// issue the creation
	future, err := serversClient.CreateOrUpdate(
		sdk.Ctx,
		sdk.ResourceGroupName,
		sdk.ServerName,
		sql.Server{
			Location:         to.StringPtr(config.Location()),
			ServerProperties: &serverProp,
		})
	if err != nil {
		return future.Result(serversClient)
	}

	return future.Result(serversClient)
}

**Comment by ArcturusZhang** [comment] 2019-09-11 02:56
Hi @WilliamMortlMicrosoft I tried some code on my computer, and I did not reproduce the error you encountered.
The code snippet I use:
```
        client := sql.NewDatabasesClient(subsID)
	authorizer, err := auth.NewAuthorizerFromCLI()
	if err == nil {
		client.Authorizer = authorizer
	}
	ctx := context.Background()
	parameters := sql.Database{
		Location: to.StringPtr(location),
	}
	future, err := client.CreateOrUpdate(ctx, resGroup, serverName, databaseName, parameters)
	if err != nil {
		panic(err)
	}
	if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
		panic(err)
	}
	if result, err := future.Result(client); err == nil {
		fmt.Println(result)
	} else {
		panic(err)
	}
```
Please note that before you use `future.Result(client)` to retrieve the actual result, you must call `future.WaitForCompletionRef(ctx, client.Client)` first to wait for the long-term operation to complete.

**Comment by ArcturusZhang** [comment] 2019-09-26 08:10
Do not get responds, closing

**Closed by ArcturusZhang** 2019-09-26 08:10 UTC
Labels: Mgmt, SQL

**Comment by jananivMS** [comment] 2020-01-29 21:14
@ArcturusZhang  We are hitting this unmarshall error continuously (also in one more case where we call CreateOrUpdate and then a Get). So what is the recommendation if we do not want to do a synchronous call and want the creation to be asynchronous. How do we see that the database is ready without getting this error?

**Comment by ArcturusZhang** [comment] 2020-01-31 02:08
> @ArcturusZhang We are hitting this unmarshall error continuously (also in one more case where we call CreateOrUpdate and then a Get). So what is the recommendation if we do not want to do a synchronous call and want the creation to be asynchronous. How do we see that the database is ready without getting this error?

Well, I believe this issue is caused by skipping the `future.WaitForCompletionRef`. This method must be called before you can call `future.Result`. If you want a asynchronous call, just return the future struct, and use `future.DoneWithContext` to query whether the async operation has completed
