### ISSUE TITLE
Key Management API for Function App

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-sdk-for-go#2397] opened 2018-08-06 00:06 UTC
### Feature Request

For the deployment of the FunctionApp, we frequently use Key Management API. However, there is no interface on the Azure SDK for go. 

For more detail. 
https://github.com/Azure/azure-functions-host/wiki/Key-management-API

it is used to fetch Azure Functions function keys, host keys, system keys. 

I tried to contribute Terraform to enable this feature. The repo owner said that that feature should 
be in this repo. I agree with him. 

https://github.com/terraform-providers/terraform-provider-azurerm/pull/1493

Of course, If you don't afford it, I'm happy to contribute this. However, since that API is not coming from Swagger definition, I'm not sure where should I implement it.

**Comment by joshgav** [comment] 2018-08-06 14:47
Thanks for reporting this @TsuyoshiUshio, we'll look into how we can support Functions APIs. I noticed this one too: https://github.com/Azure/azure-functions-host/wiki/Admin-API, are there others?

Note to readers that this isn't directly related to support for Go functions themselves, but an ask for a Go package for *managing* functions. Please follow #894 if you're interested in Go functions.

cc @asavaritayal @vladbarosan @kirthik

**Comment by tombuildsstuff** [comment] 2018-08-06 17:40
@joshgav admittedly I haven't had time to check it, but at a first glance the API responses look a lot like Kudu, so I'm wondering if that's what's powering this?

**Comment by tombuildsstuff** [comment] 2018-08-07 12:16
@joshgav cool thanks for confirming; we are - but it's not something we need immediately, do you have a rough timeline for this? Thanks!

**Comment by TsuyoshiUshio** [comment] 2018-08-07 23:35
Thank you @joshgav and @tombuildsstuff 

I didn't notice that API too. I'll ask the Azure Function Product team and share with you guys. 

At least, https://github.com/Azure/azure-functions-host/wiki/Key-management-API is frequently used for automation of the deployment for Azure Functions function/host/system keys, Durable Functions status check and so on.  It is also used integration with Event Grid. Since it is not ARM api. ARM api only provide us to give us an access token for the api. Then we need to access it using the access token by our selves. 

e.g. 
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#authorization-keys
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid
* https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api

**Comment by joshgav** [comment] 2018-08-08 17:59
cc @jeffhollan from the Functions team to comment on plans for packages supporting Kudu APIs

**Comment by tombuildsstuff** [comment] 2018-08-30 15:04
ping @jeffhollan :)

**Comment by jeffhollan** [comment] 2018-08-30 18:42
I wouldn't build this out yet with the current APIs that exist. We have work planned for later this year that will surface the APIs in a much more friendly way.  Any work we do in the interim would likely be throwaway.

**Comment by vladbarosan** [comment] 2018-10-04 23:00
@jeffhollan any updates on the new API being available  ?

**Comment by jeffhollan** [comment] 2019-03-27 17:35
Just pinging this thread - the updates aren't out yet but they are on the way so this is likely a good time to look at what the new API surface will be in the coming weeks. @mattchenderson is the point of contact on the API side from our side.

**Comment by seppi91** [comment] 2019-06-12 17:14
@mattchenderson can you give us some update when the new API will be available?

**Comment by mikhailshilkov** [comment] 2019-06-18 07:21
The new API has been deployed and the upstream issue https://github.com/Azure/azure-functions-host/issues/3994 is closed. I suppose the issue isn't blocked anymore.

**Comment by lirenhe** [comment] 2021-09-28 06:24
The issue was last updated about 2 years ago and as described, such APIs already existed.
As the GO SDK is generated from Swagger, I expected the function is also there. Please let me know if you still have issue.

**Closed by lirenhe** 2021-09-28 06:24 UTC
Labels: App Services, Mgmt, feature-request
