### ISSUE TITLE
Consider replacing satori/go.uuid with gofrs/uuid

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#4119] opened 2019-02-21 01:35 UTC
We wish to switch the AzureRM provider over to `gofrs/uuid` but cannot at the moment as the SDK expects UUID types from `satori/go.uuid`.

[satori/go.uuid](https://github.com/satori/go.uuid) does not seem to be maintained anymore as per https://github.com/satori/go.uuid/issues/83 (and mentioned in a few other issues).

It looks like the communities pick is https://github.com/gofrs/uuid, which is a community maintained fork of `satori/go.uuid`. 

Would it be possible to switch the SDK over to a maintained library?

**Comment by jhendrixMSFT** [comment] 2019-02-26 00:26
Closing as a dupe of https://github.com/Azure/azure-sdk-for-go/issues/3158.
I would like to make this change but am worried about breaking changes.  However it might not be so bad, I will discuss with the team and update 3158.

**Closed by jhendrixMSFT** 2019-02-26 00:26 UTC
