### ISSUE TITLE
Azure Core Mocking Support

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19264] opened 2022-10-03 22:43 UTC

**Comment by jhendrixMSFT** [comment] 2022-10-25 18:51
See also https://github.com/Azure/azure-sdk-for-go/issues/16613

**Comment by jhendrixMSFT** [comment] 2023-02-22 19:43
I'm closing as this is a dupe of https://github.com/Azure/azure-sdk-for-go/issues/16613

**Closed by jhendrixMSFT** 2023-02-22 19:43 UTC
Labels: Client, Azure.Core, feature-request
