### ISSUE TITLE
apimanagement client.ListComplete() returned empty list

### ISSUE THREAD

**Issue by shaobovaltix** [Azure/azure-sdk-for-go#6792] opened 2020-01-11 01:02 UTC
### Bug Report

- import path of package in question
"github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-01-01/apimanagement"

- SDK version
v33.4.0

- output of `go version`
go1.13.4 darwin/amd64

- What happened?
I imported the apimanagement package mentioned above, and first got a service client, then used the client to call ListComplete(). However, the API returned me an empty list of api management service.

- What did you expect or want to happen?
I checked my Azure portal, and I had 14 Api management services. The API should have returned me all those. Also I tried the following Azure cli:
az apim list --subscription <subscriptionID> --debug
and look like it called the same API I tried internally, and it returned me the full list of api management services.

- How can we reproduce it?
Please let me know if I need to provide more information. Thanks!

**Comment by ArcturusZhang** [comment] 2020-01-13 08:01
Hi @shaobovaltix would you please share the go code you are using?

**Comment by shaobovaltix** [comment] 2020-01-13 21:25
Hi @ArcturusZhang , thank you for responding to the issue. You mean the go code that calls the apimanagement API?

**Comment by ArcturusZhang** [comment] 2020-01-14 06:01
> Hi @ArcturusZhang Dapeng Zhang FTE , thank you for responding to the issue. You mean the go code that calls the apimanagement API?

Yes, the go code you are using. I had a try yesterday. But I do not have any api management in my subscription, both CLI and go code on my side give me empty results.
You can also export these two environment variables for verbose logging, which may help us diagnose the problem.
```
export AZURE_GO_SDK_LOG_LEVEL=DEBUG
export AZURE_GO_SDK_LOG_FILE=~/go_sdk.log
```

**Comment by shaobovaltix** [comment] 2020-01-14 19:00
Here is part of the code that called the apimanagement API:

```
// GetAPIMgmtClient - get azure api management client
func (s *AzureService) GetAPIMgmtClient() (*apimanagement.ServiceClient, error) {
	client := apimanagement.NewServiceClient(s.subscriptionID)
	authorizer, err := s.GetAuthorizer()
	// error handling
	client.Authorizer = authorizer
	return &client, nil
}

client, err := s.GetAPIMgmtClient()
// error handling
for list, errL := client.ListComplete(context.TODO()); list.NotDone(); errL = list.Next() {
        // error handling

	apim:= list.Value()
        // value processing
}
```
Please let me know if this is what you want.

**Comment by ArcturusZhang** [comment] 2020-01-16 06:46
Hi @shaobovaltix sorry that I did not reproduce this issue. Here is the code I am using:
``` go
func main() {
	if authorizer, err := auth.NewAuthorizerFromCLI(); err != nil {
		panic(err)
	} else {
		listApiManagement(authorizer)
	}
}

func listApiManagement(authorizer autorest.Authorizer) {
	client := apimanagement.NewServiceClient(subsID)
	client.Authorizer = authorizer
	for list, err := client.ListComplete(ctx); list.NotDone(); err = list.NextWithContext(ctx) {
		if err != nil {
			panic(err)
		}
		api := list.Value()
		if b, e := json.MarshalIndent(api, "", "  "); e != nil {
			panic(err)
		} else {
			fmt.Println(string(b))
		}
	}
}
```

Note that I changed your context from TODO to Background, but they are the same. And i also switch to `list.NextWithContext` method other than `Next`, since `Next` is marked as deprecated. BTW, in your way everything also works fine on my side.

Based on this, I suggest you check on your credential or something related. I am personally using `auth.NewAuthorizerFromCLI()` to acquire authorizer from CLI.

**Comment by shaobovaltix** [comment] 2020-01-17 22:12
Hi @ArcturusZhang Thank you for testing this out.
Inside the function `s.GetAuthorizer()` we are calling this function provided by Azure:
```
// Authorizer gets the authorizer from client credentials.
func (ccc ClientCredentialsConfig) Authorizer() (autorest.Authorizer, error) {
	if len(ccc.AuxTenants) == 0 {
		spToken, err := ccc.ServicePrincipalToken()
		if err != nil {
			return nil, fmt.Errorf("failed to get SPT from client credentials: %v", err)
		}
		return autorest.NewBearerAuthorizer(spToken), nil
	}
	mtSPT, err := ccc.MultiTenantServicePrincipalToken()
	if err != nil {
		return nil, fmt.Errorf("failed to get multitenant SPT from client credentials: %v", err)
	}
	return autorest.NewMultiTenantServicePrincipalTokenAuthorizer(mtSPT), nil
}
```

Also, we call other APIs such as groupClient.ListComplete() to list resource groups, roleClient.ListComplete() to list authorization roles, and both calls use the same authorizer mentioned here and both worked. Only apimanagement List call didn't work. I'm not sure whether it was related to the authorizer we used.

**Comment by ArcturusZhang** [comment] 2020-01-18 07:05
@shaobovaltix could you please share a full log of this issue? I have tagged this issue, therefore the service team will have a look at this.

**Comment by shaobovaltix** [comment] 2020-01-27 23:10
@ArcturusZhang Actually I'm afraid I don't have logs with good information. 
```
2020/01/27 08:18:36.634438: list api managements: &{azure1 eastus    RESOURCE_UNKNOWN   0001-01-01 00:00:00 +0000 UTC false false false}
2020/01/27 08:18:37.807363: got api managements: 0, []
```
Between these two lines there were no error logs printed. Please let me know if you need any other information.

**Comment by tadelesh** [comment] 2023-12-26 05:55
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md). If you could still repo this problem, please submit a support ticket in Azure directly.

**Closed by tadelesh** 2023-12-26 05:55 UTC
Labels: bug, API Management, Service Attention, Mgmt, customer-reported, needs-team-attention
