### ISSUE TITLE
Deployment validation and create does not return error

### ISSUE THREAD

**Issue by itavy** [Azure/azure-sdk-for-go#6125] opened 2019-10-23 09:33 UTC
### Bug Report

- import path of package in question: `.../services/resources/mgmt/2018-05-01/resources`
- SDK versio: `v34.2.0`
- output of `go version`:
```
go version go1.13.3 darwin/amd64
```

i followed steps in example sdk to make a deployment 
both `Validate` and `CreateOrUpdate` methods of DeploymentClient return no error, although the site responds  back with 400 status code:
```
...
(2019-10-23T09:49:01.5103070+03:00) INFO: REQUEST: POST https://management.azure.com/subscriptions/xxxxx/resourcegroups/xxxxx/providers/Microsoft.Resources/deployments/xxxxx/validate?api-version=2018-05-01
...

(2019-10-23T09:49:02.7478530+03:00) INFO: RESPONSE: 400 https://management.azure.com/subscriptions/xxxx/resourcegroups/xxxx/providers/Microsoft.Resources/deployments/xxxx/validate?api-version=2018-05-01
.....
{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'var_allowedCallerIpAddresses' is not valid: The language expression property 'cidr' can't be evaluated.. Please see https://aka.ms/arm-template-expressions for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":4613,"path":"properties.template.variables.var_allowedCallerIpAddresses"}}]}}
```

```
(2019-10-23T09:49:02.7491100+03:00) INFO: REQUEST: PUT https://management.azure.com/subscriptions/xxxxxx/resourcegroups/xxxxx/providers/Microsoft.Resources/deployments/xxxxx?api-version=2018-05-01
...

(2019-10-23T09:49:03.5755030+03:00) INFO: RESPONSE: 400 https://management.azure.com/subscriptions/xxxx/resourcegroups/xxxx/providers/Microsoft.Resources/deployments/xxxx?api-version=2018-05-01
...
{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template variable 'var_allowedCallerIpAddresses' is not valid: The language expression property 'cidr' can't be evaluated.. Please see https://aka.ms/arm-template-expressions for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":4613,"path":"properties.template.variables.var_allowedCallerIpAddresses"}}]}}
```
it seems the problem is [this line](https://github.com/Azure/azure-sdk-for-go/blob/v34.2.0/services/resources/mgmt/2018-05-01/resources/deployments.go#L1526)

because it doesn't throw error in case of `Bad request` 

it seems it is related to definition in [Azure Rest Api specs](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L288) and autorest generator which treats all responses defined in api as expected responses and does not throw error

this behaviour is the same in other api versions

Thanks!
Octavian

**Comment by itavy** [comment] 2019-10-25 06:43
as for this [suggestion](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4704#issuecomment-545959014) we can use this workaround although the error returned from the site you cannot be sure it is because of template or because you didn't send proper request

for this it will be clear if the examples are updated to check for response error instead of relying on sdk trigger the error WDYT?

Regards,
Octavian

**Comment by ArcturusZhang** [comment] 2019-10-28 02:26
A fix for this issue (if needed) will need the service team to come in. I have tagged this issue so the right team will see.

**Comment by alex-frankel** [comment] 2019-10-28 16:02
@itavy is the issue that the SDK does not return an error? Or is that you can't distinguish between a poorly authored template and a malformed request because they both return 4xx?

**Comment by itavy** [comment] 2019-10-28 16:18
my issue was the fact i cannot distinguish between 2 cases; but this was not my initial problem, but the actual [example sdk](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/4e95ecd68b1c0969dc8e7b6bf3a3b2f7e5ecdc76/resources/deployment_test.go) that is misleading

so after investigating this a bit more there are 2 issues:
1. misleading documentation
2. no options to distinguish between an invalid template and a malformed request

**Comment by itavy** [comment] 2019-10-28 16:22
btw they return 400 code, not any 4xx code. for any other 4xx request except 400 it will rise an error

**Comment by alex-frankel** [comment] 2019-10-28 18:15
We just had a discussion about this. 

You are right that the issue is in the autorest logic, but to make a change there would be a significant breaking change. Since you have a workaround to parse the error object to see if a 400 is present, we don't feel we need to make a breaking change like that at this time.

We will take an action to update the example sdk that you linked to. We agree it is misleading. Once the example is updated, we will link to that in this issue.

For distinguishing the 400s, that is again something we are not able to change at this time. When you submit a deployment via the API, the template itself is in the PUT body, so if there is something wrong with the template it is correctly being categorized as a bad request. You should be able to base your logic off of the error details that are returned.

Does this all make sense? After your response I will close the issue.

**Comment by itavy** [comment] 2019-10-28 21:08
Hi,

Sorry for the late reply, i agree with your suggestion.
You can close the issue.

Regards,
Octavian

**Closed** 2019-10-29 02:53 UTC
Labels: ARM, Mgmt, Service Attention, customer-reported
