### ISSUE TITLE
scheduler: JobCollectionQuota.MaxJobOccurrence does not seem to do anything.

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1823] opened 2018-05-09 23:58 UTC
Setting this value:
https://github.com/Azure/azure-sdk-for-go/blob/56332fec5b308fbb6615fa1af6117394cdba186d/services/scheduler/mgmt/2016-03-01/scheduler/models.go#L755

does not seem to have any effect, I am unsure about the other packages.

**Comment by jhendrixMSFT** [comment] 2018-06-06 22:59
@pinwang81 can you help route?

**Comment by lirenhe** [comment] 2021-09-28 06:16
This item has been there for 3 years with no action from service team. Close this one and @katbyte, please let us know if the issue is still there and you need a fix for it.

**Closed by lirenhe** 2021-09-28 06:16 UTC
Labels: bug, Scheduler, Service Attention, Mgmt
