### ISSUE TITLE
azblob BlobItem- everything is a pointer, why?

### ISSUE THREAD

**Issue by KastenMike** [Azure/azure-sdk-for-go#21882] opened 2023-11-03 16:40 UTC
Not really a bug but no valid option. Why did you make everything pointers in the latest API? In what situation will `Segment` be nil? Or the `BlobItem` be nil? Or the `blob.Name` be nil? Same with `LastModified` etc...It was not the case in `azblob v0.2.0` but it was changed in `v0.3` and kept since

```
for pager.More() {
    page, err := pager.NextPage(ctx)
    for _, bi := range page.Segment.BlobItems {
        blobName := *bi.Name
```

**Comment by vibhansa-msft** [comment] 2023-11-06 02:33
It's a standard Go practice to take optional parameters as pointers. Also, it helps us differentiate between default values vs not passing any value.

To make things optional its easy if user options are in form of a pointer. If 'nil' is sent then it means user does not want to use these parameters. Assume an integer is an optional value, if user does not want to send anything then it will default to 0 now inside SDK how do we whether user intentionally sent 0 or wanted to ignore it. With pointers if its 'nil' user wanted to ignore it and if its 0 then user explicitly set it to 0. Just makes it clear to understand the semantics.

**Comment by KastenMike** [comment] 2023-11-06 09:18
I'm not talking about optional parameters but about the BlobItem response https://github.com/Azure/azure-sdk-for-go/blob/5b641bb907c837c2b288d7a2e2e9c515edee2eec/sdk/storage/azblob/container/models.go#L42

Since 0.3 everything changed to pointers which seems strange because I can't imagine many fields every being null, e.g. the name or LastModified of the blob. e.g. in this SDK you are not checking for the name being nil https://github.com/Azure/azure-sdk-for-go/blob/5b641bb907c837c2b288d7a2e2e9c515edee2eec/sdk/messaging/azeventhubs/checkpoints/blob_store.go#L132 but it was decided to make the name a pointer along with other common properties I imagine will never be null. Even in the azblob docs, no guarding against NPE is attempted https://github.com/Azure/azure-sdk-for-go/blob/5b641bb907c837c2b288d7a2e2e9c515edee2eec/sdk/storage/azblob/doc.go#L197

**Comment by KastenMike** [comment] 2023-11-12 19:10
Maybe @jhendrixMSFT will know~ I guess it's some change from autorest 53 to 59. Either that or whatever the `azcore` upgrade was as part of `azblob 0.3`

**Comment by jhendrixMSFT** [comment] 2023-11-13 16:31
The internals of `azblob` are generated from swagger, and this is an artifact of that process. For reference, you can find the definition of `BlobItem` [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/data-plane/Microsoft.BlobStorage/preview/2021-12-02/blob.json#L9710-L9754).

We debated using `required` fields to indicate that a field should not be pointer-to-type but it has a few problems. First, a lot of swaggers use the same models for inputs and outputs (e.g. PATCH/GET) so fields that might be required for a GET aren't required for a PATCH, so they end up being point-to-type anyways. Second, and more important, changing the `required` status for a field would be a breaking change which we wanted to avoid. So, we generate all fields as pointer-to-type as it's the common denominator. Note that there is a `// REQUIRED` comment generated for fields marked as `required` which _should_ elide the need for a `nil` check (assuming the swagger is accurate). Third, having fields be pointer-to-type avoids ambiguity when a type's zero-value has meaning.

Early on, we debated using some kind of `Nullable[T]` type instead of pointers but it doesn't really solve the problem and is a little clunky. Plus, pointer-to-type expresses the same thing using built in language constructs.

**Comment by vibhansa-msft** [comment] 2023-11-15 10:03
As this is more of a question and not a bug report, closing this item here. Feel free to post in your comment on this thread.

**Closed by vibhansa-msft** 2023-11-15 10:03 UTC
Labels: question, Storage, customer-reported, needs-team-attention, AzBlob
