### ISSUE TITLE
Eventhub Namespace Network Ruleset vnet rule Subnet ID returns ID with resource group name in lowercase

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#5855] opened 2019-09-23 20:20 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
`"github.com/Azure/azure-sdk-for-go/services/eventhub/mgmt/2017-04-01/eventhub"`

- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
```
[13:18:09] kt@snowbook:~/hashi/tf/azure/azurerm▸eh/firewal$ cat go.mod | egrep azure
module github.com/terraform-providers/terraform-provider-azurerm
	github.com/Azure/azure-sdk-for-go v32.5.0+incompatible
	github.com/hashicorp/go-azure-helpers v0.7.0
	github.com/terraform-providers/terraform-provider-azuread v0.6.0
```
- output of `go version`
go version go1.12.6 darwin/amd64

- What happened?
the api returns the eventhub namespace network ruleset vnet subnet ID with the resource group name in lowercase.
It returned: `/subscriptions/1a6092a6-137e-4025-9a7c-ef77f76f2c02/resourcegroups/acctestrg-190923130446926298/providers/Microsoft.Network/virtualNetworks/acctvn-190923130446926298/subnets/acctsub-190923130446926298`

Instead of `/subscriptions/1a6092a6-137e-4025-9a7c-ef77f76f2c02/resourceGroups/acctestRG-190923130446926298/providers/Microsoft.Network/virtualNetworks/acctvn-190923130446926298/subnets/acctsub-190923130446926298`

- What did you expect or want to happen?
the resource id returned with the correct ID

**Comment by cliffkoh** [comment] 2019-09-23 21:06
test

**Comment by ArcturusZhang** [comment] 2019-09-24 05:42
Hi @katbyte I reproduced this using rest api. and I am tagging this issue for the service team's information

**Comment by jfggdl** [comment] 2019-09-25 18:44
@katbyte, thank you for creating this issue. We are working on identifying the root cause of the problem. You should be hearing from us soon.

**Comment by jfggdl** [comment] 2019-11-06 18:59
@katbyte, we should be releasing a fix for this lowercase issue by the end of the year.

**Comment by katbyte** [comment] 2019-11-07 14:11
Fantastic! thanks for the update @jfggdl

**Comment by samuelkoppes** [comment] 2020-10-27 03:17
Thank you again for reporting this issue. We will confirm that this fix is available and respond by 11/4/2020.

**Comment by RickWinter** [comment] 2022-02-24 20:23
@samuelkoppes Is this issue fixed, can this be closed.

**Closed** 2023-12-26 05:49 UTC
Labels: bug, Event Hubs, Service Attention, Mgmt, customer-reported
