### ISSUE TITLE
Unmarshal error of Future.Result() for network.VirtualNetworkGatewaysGetVpnProfilePackageURL

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-sdk-for-go#9561] opened 2020-05-22 19:39 UTC
### Bug Report

- import path of package in question: **`.../services/network/mgmt/2020-03-01/network`**
- SDK version: **42.1.0**
- output of `go version`: **go version go1.14.2 darwin/amd64**

- What happened?
An unmarshal error upon calling `future.Result(*client)` [(code)](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7048/files#r429136946):
**`network.VirtualNetworkGatewaysGetVpnProfilePackageURLFuture#Result: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go value of type network.String' JSON = '"https://nfvprodsuppdb.blob.core.windows.net/vpnprofileimmutable/xxxxxxxxxxxxxx/vpnprofile/xxxxxxxxxxxxxx/vpnclientconfiguration.zip?sv=2017-04-17&sr=b&sig=xxxxxxxxxxxxxx&st=2020-05-22T07%3A58%3A15Z&se=2020-05-22T08%3A58%3A15Z&sp=r&fileExtension=.zip"'`**
- What did you expect or want to happen?
Go type `network.String` to work with containing `"https://nfvprodsuppdb.blob.core.windows.net/vpnprofileimmutable/xxxxxxxxxxxxxx/vpnprofile/xxxxxxxxxxxxxx/vpnclientconfiguration.zip?sv=2017-04-17&sr=b&sig=xxxxxxxxxxxxxx&st=2020-05-22T07%3A58%3A15Z&se=2020-05-22T08%3A58%3A15Z&sp=r&fileExtension=.zip"`
- How can we reproduce it?
Run `make acctests SERVICE=web TESTARGS='-run=TestAccAzureRMAppServiceVirtualNetworkGatewayConnection_basic'` against my branch and fork of the AzureRM TerraForm Provider/this PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7048
- Anything we should know about your environment.
--

**Comment by aristosvo** [comment] 2020-05-22 19:42
Ah, seems to be a copy of https://github.com/Azure/azure-sdk-for-go/issues/5921, my bad. Needs a fix though!

**Comment by ArcturusZhang** [comment] 2020-05-25 05:44
Hi @aristosvo thanks for this issue!

Last time in internal emails, we have come an agreement with the service team that they would change their format of the response. But apparently they have not made that change yet...

Hi @jhendrixMSFT do you have some recommendation here? Is it valid for us to make some workaround on the code gen?

**Comment by jhendrixMSFT** [comment] 2020-05-26 23:50
@ArcturusZhang the swagger needs to be fixed.  Can you please follow up with the RP about it?

**Comment by aristosvo** [comment] 2020-07-01 08:16
@lilyjma @ArcturusZhang Can you please give me an update on the progress?

**Comment by lilyjma** [comment] 2020-09-03 03:15
@ArcturusZhang: Any updates on swagger change?

**Comment by ArcturusZhang** [comment] 2020-09-03 06:11
@lilyjma sorry some of the comments may not be clear enough - we are expecting the service to return everything in a format of JSON rather than a plain string. But we did not get enough progress with the service team.

Please let me give them another ping on this.

**Comment by jhendrixMSFT** [comment] 2020-09-03 14:33
@ArcturusZhang I might have been wrong about this requirement.  According to spec, `"some string"` is a valid JSON string and we have a lot of other places where this is returned (a lot in the test server).

I think the codegen might be wrong here, i.e. this might be a bug where LROs and operations that return scalar values intersect.  If you look at codegen in the test server for the non-LRO case, we unmarshall into the `Value` field.

https://github.com/Azure/autorest.go/blob/master/test/src/tests/generated/stringgroup/string.go#L87

For network we don't.

```go
autorest.ByUnmarshallingJSON(&result),
```

I think the codegen should unmarshall that into `result.String`.

We appear to have the same issue in track 2.

**Comment by jhendrixMSFT** [comment] 2020-09-03 15:04
Actually, it looks like track 2 does the right thing here.

**Comment by ArcturusZhang** [comment] 2020-09-04 08:39
> @ArcturusZhang I might have been wrong about this requirement. According to spec, `"some string"` is a valid JSON string and we have a lot of other places where this is returned (a lot in the test server).
> 
> I think the codegen might be wrong here, i.e. this might be a bug where LROs and operations that return scalar values intersect. If you look at codegen in the test server for the non-LRO case, we unmarshall into the `Value` field.
> 
> https://github.com/Azure/autorest.go/blob/master/test/src/tests/generated/stringgroup/string.go#L87
> 
> For network we don't.
> 
> ```go
> autorest.ByUnmarshallingJSON(&result),
> ```
> 
> I think the codegen should unmarshall that into `result.String`.
> 
> We appear to have the same issue in track 2.

Good to know. Let me have a look how to fix this in the code gen.

**Comment by aristosvo** [comment] 2020-11-18 11:19
@ArcturusZhang Any news?

**Comment by KarlRanseier** [comment] 2021-07-29 10:18
Any news?

**Comment by jhendrixMSFT** [comment] 2021-08-06 20:44
This is a dupe of https://github.com/Azure/azure-sdk-for-go/issues/5921.  The code generator has been fixed, just waiting for a new release.

**Closed by jhendrixMSFT** 2021-08-06 20:44 UTC
Labels: bug, Mgmt, customer-reported, Network - VPN Gateway, needs-team-attention, needs-team-triage
