### ISSUE TITLE
Add history on changes over http and tls package

### ISSUE THREAD

**Issue by mvanotti** [Azure/azure-sdk-for-go#168] opened 2015-06-11 18:44 UTC
Inside the core folder, there are two folders: http and tls, which are forks of the stdlib packages. It would be really nice to have the initial go version there where it diverged, as well as some comments on what has changed.

How do you plan on keeping those packages up to date?

Maybe adding the initial go version and then reapplying the current changes, so the diff is easier to spot, and also it will be easier to port new changes.

**Comment by ahmetalpbalkan** [comment] 2015-06-11 20:04
@mvanotti Thanks for opening up the discussion. It's a duplicate of #90 and you can see more context over there.

**Closed by ahmetalpbalkan** 2015-06-11 20:04 UTC
