### ISSUE TITLE
CostManagement API: Function QueryResourceGroup returns nil 

### ISSUE THREAD

**Issue by tqtruong95** [Azure/azure-sdk-for-go#3765] opened 2018-12-19 19:58 UTC
Hello,

I am using `github.com/Azure/azure-sdk-for-go/services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement` and wanted to get cost based on resource group. I’ve encountered an issue where I’m unable to get the list of `QueryResult`, instead it returns `nil`. 

Currently using: 
Azure SDK Golang Version:`23.2.0`
Go Version: `go1.11.3 darwin/amd64`

### Here is my code:
```oauthConfig, err := adal.NewOAuthConfig(azure.PublicCloud.ActiveDirectoryEndpoint, tenantID)
    if err != nil {
        fmt.Println("OAuthConfigForTenant failed: %v", err)
    }

    spToken, err := adal.NewServicePrincipalToken(*oauthConfig, clientID, clientSecret, azure.PublicCloud.ResourceManagerEndpoint)
    if err != nil {
        fmt.Println("NewServicePrincipalToken failed: ", err)
    }

    baseClient = costmanagement.New(subscriptionID)
    baseClient.Authorizer = autorest.NewBearerAuthorizer(spToken)

    params := costmanagement.ReportDefinition{
        Type:      to.StringPtr("Usage"),
        Timeframe: costmanagement.MonthToDate,
        Dataset: &costmanagement.ReportDataset{
            Granularity: costmanagement.Daily,
            Aggregation: map[string]*costmanagement.ReportAggregation{
                "totalCost": &costmanagement.ReportAggregation{
                    Name:     to.StringPtr("PreTaxCost"),
                    Function: to.StringPtr("Sum"),
                },
            },
            Grouping: &[]costmanagement.ReportGrouping{
                costmanagement.ReportGrouping{
                    Type: costmanagement.ReportColumnTypeDimension,
                    Name: to.StringPtr(“ResourceType"),
                },
            },
        },
    }

    resp, err := baseClient.QueryResourceGroup(ctx, resourceGroupName, params)
    if err != nil {
        fmt.Println("Error:", err)
    }
    fmt.Println("Success:", resp.Value)
```

However, when I call the API directly using a POST Request via Postman

 `https://management.azure.com/subscriptions/{{subscriptionID}}/resourcegroups/{{resourceGroupName}}/providers/Microsoft.CostManagement/Query?api-version=2018-08-01-preview`

### Request Body JSON:
```{
  "type": "Usage",
  "timeframe": "MonthToDate",
  "dataset": {
    "granularity": "Daily",
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      }
    },
    "grouping": [
      {
        "type": "Dimension",
        "name": "ResourceType"
      }
    ]
  }
}
```

I was able to successfully retrieve a response. 

I have the same issue with `baseClient.QuerySubscription` function as well, where the `QueryResult` returns `nil` but also able to successfully retrieve a response via Postman.

Any thoughts? I’m not sure if I’m passing in the parameters incorrectly on the provided structs from costmanagement or other underlying issues.

**Comment by jhendrixMSFT** [comment] 2018-12-19 22:41
Hello @tqtruong95, could you please provide a sample response body?  I suspect there's a mismatch between what's modeled in the code and what's retrieved on the wire.

**Comment by tqtruong95** [comment] 2018-12-20 00:45
@jhendrixMSFT 

Sure, here are the details

### POST Request URL
https://management.azure.com/subscriptions/{{subscriptionID}}/resourcegroups/{{resourceGroupName}}/providers/Microsoft.CostManagement/Query?api-version=2018-08-01-preview

### Request Body 
```
{
  "type": "Usage",
  "timeframe": "MonthToDate",
  "dataset": {
    "granularity": "Daily",
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      }
    },
    "grouping": [
      {
        "type": "Dimension",
        "name": "ResourceType"
      }
    ]
  }
}
```
### Response
```
{
    "id": "subscriptions/{{my_subscription_id}}/resourcegroups/{{my_resource_group_name}}/providers/Microsoft.CostManagement/query/{{name}}",
    "name": "{{name}}",
    "type": "Microsoft.CostManagement/query",
    "location": null,
    "sku": null,
    "eTag": null,
    "properties": {
        "nextLink": null,
        "columns": [
            {
                "name": "PreTaxCost",
                "type": "Number"
            },
            {
                "name": "UsageDate",
                "type": "Number"
            },
            {
                "name": "ResourceType",
                "type": "String"
            },
            {
                "name": "Currency",
                "type": "String"
            }
        ],
        "rows": [
            [
                1.06884530791789,
                20181204,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                20.730816555381331,
                20181204,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                0.058818144475089,
                20181204,
                "Microsoft.Network/publicIPAddresses",
                "USD"
            ],
            [
                1.1962573313782989,
                20181205,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.5099958867927,
                20181205,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                0.002201748723666,
                20181205,
                "Microsoft.Network/publicIPAddresses",
                "USD"
            ],
            [
                1.1891788856304979,
                20181206,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.503539297577849,
                20181206,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1891788856304979,
                20181207,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.501416529204437,
                20181207,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1891788856304979,
                20181208,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.631528917494844,
                20181208,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1891788856304979,
                20181209,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.501402223253272,
                20181209,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1962573313782989,
                20181210,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.74313414668114,
                20181210,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.366140029325513,
                20181211,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                24.627801378679862,
                20181211,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.359061583577712,
                20181212,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                24.575482690616678,
                20181212,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.359061583577712,
                20181213,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                24.649001420980763,
                20181213,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.2174926686217,
                20181214,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                22.047643572685995,
                20181214,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1891788856304979,
                20181215,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.503542604867633,
                20181215,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                1.1891788856304979,
                20181216,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                21.503527991261606,
                20181216,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ],
            [
                0.990982404692084,
                20181217,
                "Microsoft.Compute/disks",
                "USD"
            ],
            [
                17.008699352192011,
                20181217,
                "Microsoft.Compute/virtualMachines",
                "USD"
            ]
        ]
    }
}
```

**Comment by jhendrixMSFT** [comment] 2018-12-20 17:33
Thanks.  Looks like the service and the swagger don't agree on the response payload format as the swagger states it should be an array (see [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2018-08-01-preview/costmanagement.json#L3381)).
@yaborens can you please take a look?

**Comment by yaborens** [comment] 2018-12-23 11:41
The issue is not under my domain, I forwarded it to the right person

**Comment by jhendrixMSFT** [comment] 2019-01-08 21:09
@yaborens I've ported the issue to the specs repo, see https://github.com/Azure/azure-rest-api-specs/issues/5005.  Can you please let me know the correct person I should assign this to?

**Comment by jhendrixMSFT** [comment] 2019-01-08 21:21
Closing in favor of https://github.com/Azure/azure-rest-api-specs/issues/5005

**Closed by jhendrixMSFT** 2019-01-08 21:21 UTC
Labels: customer
