### ISSUE TITLE
Guidance on using ETAGs / Conditional requests

### ISSUE THREAD

**Issue by CecileRobertMichon** [Azure/azure-sdk-for-go#8917] opened 2020-05-06 19:17 UTC
### Feature Request

I saw https://azure.github.io/azure-sdk/general_design.html#conditional-requests was recently added in the Azure SDK general design guidelines. Are there any plans to include this mechanism in the Azure SDK for Go? 

We have a [use case](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/578) where two different components of a Kubernetes cluster are updating the same Azure resource (NSG) and we would like to conditionally update it, ie. CreateOrUpdate with condition`onlyIfUnchanged` such that "I’ve modified the cached value I’m holding, but don’t update the service version unless it has the same copy I’ve got". 

Right now, `parameters.Etag` gets set to nil in `CreateOrUpdatePreparer` (example https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2020-03-01/network/securitygroups.go#L75-L97). I assume the only way to achieve something like the above is to call `CreateOrUpdatePreparer` directly instead of calling `CreateOrUpdate` and then modify the http request returned to add a header with the etag (see https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/592#discussion_r421031405).  Is that the recommended way?

**Comment by ArcturusZhang** [comment] 2020-05-07 08:18
Hi @CecileRobertMichon I believe the design doc you posted should be for track 2 SDK.

Hi @jhendrixMSFT do you have any insight on this?

**Comment by jhendrixMSFT** [comment] 2020-05-07 15:18
Presumably it's set to nil because the field is marked as read-only in the swagger.  @ArcturusZhang can you check?

Support for conditional updates is something that has to come from the RP and exposed in the swagger.

**Comment by ArcturusZhang** [comment] 2020-05-08 04:05
@jhendrixMSFT indeed it is read-only (https://github.com/Azure/azure-rest-api-specs/blob/e5c2528f173640be3d9dcaf9f7a5bafb64f6ff47/specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/networkSecurityGroup.json#L929)

**Comment by CecileRobertMichon** [comment] 2020-05-11 17:13
> Support for conditional updates is something that has to come from the RP and exposed in the swagger.

I used the example of network security group but this issue exists for all services that support etags from what I've seen.

**Comment by RickWinter** [comment] 2021-09-13 20:01
@lirenhe Can you review and ensure this is addressed in your latest management SDKs

**Comment by lirenhe** [comment] 2021-09-17 06:33
@RickWinter, it seems the problem is not addressed in track 2. Will you consider to handle that in future releases?

**Comment by jhendrixMSFT** [comment] 2021-09-17 15:22
Also, for track 2, should we be using the `azcore.ETag` type in code generation?

**Comment by MartinForReal** [comment] 2023-11-13 12:10
In track2 sdk, the only way to set etag in request is to recreate client with policy https://github.com/Azure/azure-sdk-for-go/blob/16d371ccbfb808e01013a45b8da8253db3422868/sdk/azcore/runtime/policy_http_header.go.

**Comment by MartinForReal** [comment] 2023-11-13 12:17
I think it is a good idea because util functions (compare value) can be reused. 

> Also, for track 2, should we be using the `azcore.ETag` type in code generation?

**Comment by jhendrixMSFT** [comment] 2023-11-13 16:03
This has come up before. If a service supports conditional operations via ETags then it should update the swagger including them so they're properly modeled.

CC @JeffreyRichter

**Comment by JeffreyRichter** [comment] 2023-11-15 23:22
Yes, Joel is correct. Having them in swagger is also how they documented so that customers know which operations support the conditional requests and how they get exposd to customers using our SDKs..

**Closed** 2024-01-17 01:29 UTC
Labels: Network, Mgmt, needs-author-feedback, feature-request, no-recent-activity
