### ISSUE TITLE
Support password credentials flow for federated users

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#17615] opened 2022-04-15 19:20 UTC
Ported from https://github.com/Azure/go-autorest/issues/378

**Comment by chlowell** [comment] 2022-04-19 16:35
Closing this as a duplicate of #14405. Current status is that we're waiting on MSAL to support federated user authentication.

**Closed by chlowell** 2022-04-19 16:35 UTC
Labels: Client, Azure.Identity, feature-request
