### ISSUE TITLE
Expand the returned VMs' fields from VM List Call

### ISSUE THREAD

**Issue by xqi-aviatrix** [Azure/azure-sdk-for-go#18565] opened 2022-07-08 17:57 UTC
As the title asks.
Some VM fields (e.g., vm.Properties.InstanceView.OSName; vm.Properties.InstanceView.OSVersion; vm.Properties.NetworkProfile; vm.Tags) are nil when they are returned from this list call. I have to fetch the missing field values through a Get call for each single VM. 
The list option does not have `expand` field for us neither.

https://github.com/Azure/azure-sdk-for-go/blob/9adda3e39ec3fea73c0a66390ae88f13ec7e6859/sdk/resourcemanager/compute/armcompute/zz_generated_virtualmachines_client.go#L764

**Comment by lirenhe** [comment] 2022-07-11 02:09
@tadelesh, could you help to follow up on this? Thanks.

**Comment by tadelesh** [comment] 2022-07-11 06:04
@xqi-aviatrix Thanks for your feedback. According to my test, at least `Tags` of the virtual machine can be both returned by `list` and `get` method. Could you please paste the HTTP log for the two options? You could refer this [doc](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#logging) to config log options.

**Comment by xqi-aviatrix** [comment] 2022-07-11 16:50
Thanks for testing it locally. I can confirm that when I remove the list option `StatusOnly: to.Ptr("statusOnly")` from my list call. Then I can get non-nil tags.

But the vm.Properties.InstanceView related fields (like OSName, OSVersion, NetworkProfile, Statuses) are still nil. It would be helpful to have a list option to expand instance view.

I have not issue with the get method.

**Comment by xqi-aviatrix** [comment] 2022-07-11 16:58
I would like to provide http log. I made the calls from visual code, are there any instructions to get the http logs from visual code?

**Comment by tadelesh** [comment] 2022-07-12 02:00
I'll let service team to have a look.

**Comment by navba-MSFT** [comment] 2022-07-13 04:53
@xqi-aviatrix Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-07-14 05:00
@xqi-aviatrix I am yet to look into this. But before that I wanted to check if you have tested using the below sample and confirm if that helps ?

```
package main

import (
	"context"
	"log"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
)

var (
	subscriptionID    string
	server            string
	location          = "MyLocation"
	resourceGroupName = "myRgName"
	apiVersion        = "2021-02-01"
	vmName            = "myVMName"
)

func main() {
	subscriptionID = "b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f"
	if len(subscriptionID) == 0 {
		log.Fatal("AZURE_SUBSCRIPTION_ID is not set.")
	}
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		// handle error
	}
	client, err := armcompute.NewVirtualMachinesClient(subscriptionID, cred, nil)
	if err != nil {
		// handle error
	}
	ctx := context.Background()
	res, err := client.Get(ctx,
		resourceGroupName,
		vmName,
		nil)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf(*res.VirtualMachine.Properties.InstanceView.OSName)
	log.Printf(*res.VirtualMachine.Properties.InstanceView.OSVersion)
	log.Printf(*res.VirtualMachine.Properties.InstanceView.VMHealth.Status.DisplayStatus)
}
```
Awaiting your reply.

**Comment by xqi-aviatrix** [comment] 2022-07-14 16:24
Thanks @navba-MSFT.

The issue I face is to reduce the number of calls to azure. The lack of expand option in the vm list call that forces me to use the vm get call you wrote above to fetch vm instanceview for each vmId returned from the vm list call.

suppose I have 200 vms under a subscription and vm list call returns 100 vms per page. I need 202 calls  (2 list calls + 200 get calls) to get all the info I need. If there are necessary expand option for the list call, I would just need 2 list calls

**Comment by navba-MSFT** [comment] 2022-07-15 03:19
@xqi-aviatrix Thanks for your reply. I am adding the Service Team to look into this issue.

**Comment by jaylabell** [comment] 2022-07-21 19:44
@Drewm3 can you please look into this VM issue?

**Comment by Drewm3** [comment] 2022-08-01 22:46
This is by design currently. The reason is that the instance view for a machine changes minute-by-minute which means that each instance must be queried directly to get the current status. We therefore require a query per instance to make this check. We are moving to a pub/sub model internally that will enable more instance status details in a single API call like this, but we are not ready to roll-out this functionality yet.

**Comment by Drewm3** [comment] 2022-08-04 19:50
Reopening and closing for this to pickup in the MSFT tracking system.

**Closed** 2022-08-04 19:50 UTC
Labels: Compute - VM, Service Attention, Mgmt, customer-reported, needs-team-attention, feature-request
