### ISSUE TITLE
`containerregistry` `2021-08-01-preview`: AgentPool's `Delete` method returns too early

### ISSUE THREAD

**Issue by favoretti** [Azure/azure-sdk-for-go#15042] opened 2021-07-13 16:01 UTC
When trying to delete a containerregistry's agentpool, the API call returns completion too early, underlying VMSS ip configuration still stays for a few.

Trying to implement support for it in azure provider [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/12440).

Destruction during acceptance test fails with:
```
------- Stdout: -------
=== RUN   TestAccContainerRegistryAgentPool_complete
=== PAUSE TestAccContainerRegistryAgentPool_complete
=== CONT  TestAccContainerRegistryAgentPool_complete
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctestvirtnet210713115141799144" / Resource Group "acctestRG-acragent_pool-210713115141799144"): network.SubnetsClient#Delete: Failure sending request: StatusCode=0 -- 
Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/f9954d5e-6e81-4951-b504-56c712bcfe31/resourceGroups/ap-testacccr210713115141799144-ap210713115141744-394/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|testacccr210713115141799144-ap210713115141744-394-0|virtualMachines|0|networkInterfaces|ap-testacccr210713115141799144-ap210713115141744-394-0-nic/ipConfigurations/ap-testacccr210713115141799144-ap210713115141744-394-0-ipconfig and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
--- FAIL: TestAccContainerRegistryAgentPool_complete (750.65s)
```

Deleting subnet from portal after 3-5 minutes succeeds without any issues.

**Comment by akning-ms** [comment] 2021-07-14 02:42
guess assigned to wrong person. reassign to dapeng for triage

**Comment by favoretti** [comment] 2021-07-20 20:11
@ArcturusZhang Hey, could you have a look pls?

**Comment by ArcturusZhang** [comment] 2021-07-23 00:28
I heard that in some cases, the subnet has some delay to disjoint with other resources after it was successfully deleted.
Defer to the corresponding service team to get a confirmation.

**Comment by favoretti** [comment] 2021-08-09 09:32
@ArcturusZhang any updates here by any chance? :)

**Comment by ArcturusZhang** [comment] 2021-08-24 04:24
Hi @toddysm do we have some updates on this?

**Comment by favoretti** [comment] 2021-09-24 08:56
@toddysm still running into the same issue. Any updates?

**Comment by lirenhe** [comment] 2021-12-21 06:08
@favoretti, could you create a support ticket as this is a service issue and there is no much work on the SDK side.

**Comment by favoretti** [comment] 2022-01-04 14:13
Re-tested this on `2021-08-01-preview` behavior is still the same, will open up a support request to work with someone on MSFT side.

**Comment by favoretti** [comment] 2022-01-04 14:16
```
=== CONT  TestAccContainerRegistryAgentPool_complete
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1

        Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctestvirtnet220104144721404156" / Resource Group "acctestRG-acragent_pool-220104144721404156"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/f9954d5e-6e81-4951-b504-56c712bcfe31/resourceGroups/ap-testacccr220104144721404156-ap220104144721456-00d/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|testacccr220104144721404156-ap220104144721456-00d-0|virtualMachines|0|networkInterfaces|ap-testacccr220104144721404156-ap220104144721456-00d-0-nic/ipConfigurations/ap-testacccr220104144721404156-ap220104144721456-00d-0-ipconfig and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

--- FAIL: TestAccContainerRegistryAgentPool_complete (542.71s)
```

**Comment by juliusl** [comment] 2022-01-04 20:53
@ArcturusZhang Hello, I am from the ACR Service team, I took a look at the sdk code and I noticed a couple of things. 

First for clarification, I notice that the client code has a Responder but does not use it in the either the Create/Delete methods, is this intentional? 

Second, in ARM Delete is an async operation, meaning the client code needs to poll for the operation status before returning. This is not handled on the service side, so the sdk needs to do this here: 

https://github.com/Azure/azure-sdk-for-go/blob/6264636169251df0ea48912167b417c2a9c108ce/services/preview/containerregistry/mgmt/2021-08-01-preview/containerregistry/agentpools.go#L168-L174

before returning to the caller.

For example, you can see in the python sdk we do the polling here:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/agentpool.py#L99

How are changes like this handled in the go sdk?

**Comment by ArcturusZhang** [comment] 2022-01-05 03:45
> @ArcturusZhang Hello, I am from the ACR Service team, I took a look at the sdk code and I noticed a couple of things.
> 
> First for clarification, I notice that the client code has a Responder but does not use it in the either the Create/Delete methods, is this intentional?
> 
> Second, in ARM Delete is an async operation, meaning the client code needs to poll for the operation status before returning. This is not handled on the service side, so the sdk needs to do this here:
> 
> https://github.com/Azure/azure-sdk-for-go/blob/6264636169251df0ea48912167b417c2a9c108ce/services/preview/containerregistry/mgmt/2021-08-01-preview/containerregistry/agentpools.go#L168-L174
> 
> before returning to the caller.
> 
> For example, you can see in the python sdk we do the polling here:
> 
> https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/agentpool.py#L99
> 
> How are changes like this handled in the go sdk?

[This function](https://github.com/Azure/azure-sdk-for-go/blob/a979cf7de738a563a4675ca5e6ef9a04871df64d/services/preview/containerregistry/mgmt/2021-08-01-preview/containerregistry/agentpools.go#L137) returns a future which indicates this is a long-running operation.
If an operation is a LRO, the caller should call its `WaitForCompletionRef` method in which the SDK will do the polling as python SDK is doing.

The polling logic is not implemented in the SDK but in another library `go-autorest` which is why you did not see the polling logic in the SDK (it is [here](https://github.com/Azure/go-autorest/blob/2e1acb24564e501ac2a0eb509116231bf0080b7e/autorest/azure/async.go#L130) if you are interested).

The reason why  the Responder of this operation is not called is by-design. This operation does not have a response, therefore the SDK does not use the Responder, because it is not needed. If an LRO is returning a schema (like PUT), the responder will be invoked (example [here](https://github.com/Azure/azure-sdk-for-go/blob/a979cf7de738a563a4675ca5e6ef9a04871df64d/services/preview/containerregistry/mgmt/2021-08-01-preview/containerregistry/models.go#L403))

The function `WaitForCompletionRef` will not return unless it gets the `success` from the LRO polling. Therefore in this case, if you could confirm you called `WaitForCompletionRef` in your code @favoretti , the root cause is not in the SDK.
The service should not return success in an LRO if not everything is done. This happens occasionally in some APIs, their LRO might return success when they are done things in their own RP, and things from other RPs are still in progress (like in this case, the subnet from NRP is detaching but not finished, the API returns success) @juliusl please double confirm this.

**Comment by favoretti** [comment] 2022-01-05 07:21
@ArcturusZhang Yep, I am calling `WaitForCompletionRef` indeed: https://github.com/hashicorp/terraform-provider-azurerm/pull/14790/files#diff-f6764132d0fc067d88469fea293e2010a129184291d121243d34695fe39c2e77R252

**Comment by juliusl** [comment] 2022-01-06 02:41
Also, I double checked our code and the response includes a RetryAfter and Location header, so it should have everything needed for LRO polling.

**Comment by favoretti** [comment] 2022-01-10 09:00
@ArcturusZhang any thoughts on what @juliusl provided above?

**Comment by ArcturusZhang** [comment] 2022-01-10 10:14
The discussions here raise the concerns from me of the no-responder thing.
@jhendrixMSFT do you have some insights on this particular issue? And how is that implemented in track 2?

**Comment by tombuildsstuff** [comment] 2022-01-10 13:05
@juliusl from what I can see this appears to be a Swagger issue rather than a Go SDK issue - most other API's define both `x-ms-long-running-operation` and `x-ms-long-running-operation-options`, however it appears that this API only defines `x-ms-long-running-operation` for LRO's?

https://github.com/Azure/azure-rest-api-specs/blob/d8242e83bad59e45d5bb1dad769a185504f5fde3/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2021-08-01-preview/containerregistry.json#L214

When other API's define LRO's as:

```json
 "x-ms-long-running-operation": true,
 "x-ms-long-running-operation-options": {
   "final-state-via": "azure-async-operation"
 }
```

Hopefully that helps track this down anyway.

**Comment by juliusl** [comment] 2022-01-11 02:02
@tombuildsstuff I don't see that defined for any other api in that document. Is delete supposed to be a special case?

**Comment by juliusl** [comment] 2022-01-11 02:43
So I noticed for example, vmms has the same type of definition in their swagger spec, 

https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json#L5445

and then in the corresponding go sdk model, 

https://github.com/Azure/azure-sdk-for-go/blob/ec2ed6d8450ad53978efa96822bf9c9431a63ab4/services/compute/mgmt/2021-04-01/compute/models.go#L19840

They also do not need to use a responder. They also do not have the "x-ms-long-running-operation-options" but they do define `"x-ms-long-running-operation": true`. 

Are the VMSS apis in the sdk running into the same issue for delete?

**Comment by favoretti** [comment] 2022-01-11 09:23
@juliusl from what I can see VMSS tests are passing successfully, so deletes are good there.

**Comment by favoretti** [comment] 2022-01-11 09:26
Or actually... nevermind, it does fail as well:
```
Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctestnw-220111040147236257" / Resource Group "acctestRG-220111040147236257"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/*******/resourceGroups/acctestRG-220111040147236257/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|acctvm22|virtualMachines|0|networkInterfaces|example/ipConfigurations/internal and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
--- FAIL: TestAccWindowsVirtualMachineScaleSet_extensionAutomaticUpgradeEnabled (308.41s)
```

**Comment by juliusl** [comment] 2022-01-13 00:43
@tombuildsstuff @ArcturusZhang So it looks like this is a problem for any team that doesn't have that property. 

Would it make sense for the sdk to default to a `x-ms-long-running-operation-options` during auto generation?

**Comment by jhendrixMSFT** [comment] 2022-01-13 23:23
Setting env var `AZURE_GO_SDK_LOG_LEVEL` to `debug` is the best way to debug LROs as you can see all the HTTP requests and responses.

@juliusl it looks to me that the behavior for delete here is non-conformant.

Here's the last successful poll on the Location header (I've omitted some content for brevity).

```
(2022-01-13T14:54:38.9749705-08:00) INFO: REQUEST: GET https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview
User-Agent: Go/go1.17 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v61.1.0 containerregistry/2021-08-01-preview
Authorization: **REDACTED**
(2022-01-13T14:54:39.0253957-08:00) INFO: RESPONSE: 202 https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview
Retry-After: 10
Location: https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview
{"status":"Deleting"}
(2022-01-13T14:54:39.0260859-08:00) INFO: DelayForBackoffWithCap: sleeping for 10s
```

Note that the LRO status is non-terminal `Deleting`.  Now we poll again.

```
(2022-01-13T14:54:49.0310997-08:00) INFO: REQUEST: GET https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview
User-Agent: Go/go1.17 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v61.1.0 containerregistry/2021-08-01-preview
Authorization: **REDACTED**
(2022-01-13T14:54:49.0705737-08:00) INFO: RESPONSE: 404 https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1' under resource group 'jhendrixtest1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
(2022-01-13T14:54:49.0710431-08:00) ERROR: WaitForCompletionRef: Code="ResourceNotFound" Message="The Resource 'Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1' under resource group 'jhendrixtest1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
(2022-01-13T14:54:49.0717104-08:00) INFO: DelayForBackoffWithCap: sleeping for 30s
...
```

Looks like the polling URL has been deleted.  If the LRO has reached a successful terminal state, it should either return a 200 with a successful terminal state (e.g. `Succeeded`) or a 204.

**Comment by juliusl** [comment] 2022-01-21 06:07
@jhendrixMSFT That 404 that is coming from ARM itself. If you notice the Location URL is: 

` https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1/operationResults/92110f9b-3ad7-4132-a6ae-164c77a8e178?api-version=2019-06-01-preview` 

which is under 

`https://management.azure.com/subscriptions/6d3860f6-8a11-431d-b3fa-1b3c4a8b888a/resourceGroups/jhendrixtest1/providers/Microsoft.ContainerRegistry/registries/jhendrixacr2/agentPools/jhendrixpool1` 

Since the resource has been deleted, ARM isn't able to proxy request to us. In our case the limitation is that we host this API underneath the the resource scope.  

`Location URI under subscription scope is preferred. If operationResults is exposed under resource scope, then for long running operations like delete, operationResults resource will not be accessible when the resource gets deleted.`

Which is why I'm recommending the SDK add logic for it as the python sdk did, https://github.com/Azure/azure-cli/blob/35d12aee56c88dc8673ddce0f9e79b4de0bb33f8/src/azure-cli/azure/cli/command_modules/acr/agentpool.py#L99. 

Although, that is definitely conflicting with the other part of the documentation that states: 

`If the DELETE completes successfully, the URL that was returned in the Location header MUST now return a 200 OK or 204 NoContent to indicate success and the resource MUST disappear.` 

source: https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#delete-resource-asynchronously

cc: @northtyphoon, any thoughts on the above? We could move the operation results under the registry scope, so `{RegistryName}/agentPools/operationResults/{id}`

**Comment by juliusl** [comment] 2022-01-21 06:42
@jhendrixMSFT One thing that still doesn't make sense, from your logs you're getting a 404, and from @favoretti's code he's calling `response.WasNotFound` on the error that's coming back from WaitForCompletionRef. 

https://github.com/hashicorp/terraform-provider-azurerm/pull/14790/files#diff-f6764132d0fc067d88469fea293e2010a129184291d121243d34695fe39c2e77R253

Which specifically is checking the error code, and in this case it's checking for a 404. 

https://github.com/hashicorp/go-azure-helpers/blob/main/lang/response/response.go#L14

If WaitForCompletionRef is returning a 404, then @favoretti's code should return nil and handle it as a success.

Ok, so the original issue that @favoretti is getting was:  
``` 
Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctestvirtnet210713115141799144" / Resource Group "acctestRG-acragent_pool-210713115141799144"): network.SubnetsClient#Delete: Failure sending request: StatusCode=0 -- 
Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/f9954d5e-6e81-4951-b504-56c712bcfe31/resourceGroups/ap-testacccr210713115141799144-ap210713115141744-394/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|testacccr210713115141799144-ap210713115141744-394-0|virtualMachines|0|networkInterfaces|ap-testacccr210713115141799144-ap210713115141744-394-0-nic/ipConfigurations/ap-testacccr210713115141799144-ap210713115141744-394-0-ipconfig and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
--- FAIL: TestAccContainerRegistryAgentPool_complete (750.65s)
``` 
But that seems to be a different error than what @jhendrixMSFT got, 

@jhendrixMSFT are you using a different build per chance? @favoretti does the above error come from another line?

**Comment by juliusl** [comment] 2022-01-24 21:15
@favoretti got it, so that's probably why jhendrix might've not run into the error.

Well in any case, from my side I'm currently in the process of adding a new api to our RP for the operation result polling. It will take a bit to deploy, but it should fix the 404. I'm crossing my fingers that it will address your issue as well. 

For now, have you considered adding a 5-min grace period whenever that code runs into an error deleting the subnet? I know it's a hack but it should unblock you for now. 

I'll keep updating this issue with my status. Just so you are aware, service changes typically take a while to make it downstream.

**Comment by favoretti** [comment] 2022-01-24 22:00
Thanks! I'll try adding a sleep to see if that helps. Not ideal of course.

**Comment by juliusl** [comment] 2022-01-24 22:48
@favoretti Another thing I thought of, I could try testing my changes w/ Terraform but I'm not too familiar with Terraform. Is it pretty straightforward to run the conformance tests on my own?

**Comment by favoretti** [comment] 2022-01-24 22:58
Not too difficult. Clone provider, check out my PR branch, set a few env vars and run a command. I am not at my computer now, but I can add a set of commands for you tomorrow?

**Comment by juliusl** [comment] 2022-01-24 23:08
@favoretti That would be much appreciated thanks 🙏

**Comment by magodo** [comment] 2022-02-07 02:07
@juliusl We've also noticed that updating the `agentCount` (e.g.) from 2 to 1 sometimes finished quickly, but sometimes didn't even finish in one hour, which results into timeout in the client side. Then a later deletion on this agent pool failed with:

> Code="RegistryStatusConflict" Message="Cannot perform the operation as the resource 'acctestacrap22020291' is in 'Queued' state."

**Comment by magodo** [comment] 2022-02-10 03:11
@juliusl I've reproduced it just now. The `x-ms-correlation-request-id` is 72f9c7e5-29b1-6b6f-2575-63fc54c16d74.

From my side, the API sequence is as below:

- A `GET` on the agent pool shows it has `count: 2`.
- A `PATCH` with following payload sent and returned 201:
  
  ```json
  { "properties": { "count": 1 } }
  ```
- Keeps polling on the long-running operation URL returned via above `PATCH`, until timeout (1 hr).
- A `DELETE` operation on the agent pool shows following error:

   ```
  {
    "error": {
      "code": "RegistryStatusConflict",
      "message": "Cannot perform the operation as the resource 'acctestacrap22021081' is in 'Queued' 
  state.",
      "target": "request"
    }
  }
   ```

**Comment by juliusl** [comment] 2022-03-03 01:39
@magodo Thanks for the repro, I should be able to take a deeper dive, 

Also a status update from our side that should be able to address some of these issues, cc: @favoretti 

We're in the process of rolling out a new operation status api to our resource provider that internally should allow for a better polling experience. Last week we merged the change and so now it's just a matter of enabling things in production. This process will take a bit of time to roll out but I'm optimistic we should be able to wrap things up in about a month or two.

**Comment by juliusl** [comment] 2022-03-03 20:44
@magodo so good news, we were able to track your issue down on our side and we're working on a fix

**Comment by juliusl** [comment] 2022-04-01 21:39
@favoretti  Good news, finally was able to test the change and it looks like it's working, 

```
1 ❯ TF_ACC=1 go test -v ./internal/services/containers -timeout=1000m -run=TestAccContainerRegistryAgentPool_complete
=== RUN   TestAccContainerRegistryAgentPool_complete
=== PAUSE TestAccContainerRegistryAgentPool_complete
=== CONT  TestAccContainerRegistryAgentPool_complete
--- PASS: TestAccContainerRegistryAgentPool_complete (488.55s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    488.560s
```

This change should start rolling out next week and should be complete the week after.

**Comment by favoretti** [comment] 2022-04-01 22:36
@juliusl awesome! Thanks a bunch, will happily rebase my PR and hopefully get it into a release once the fix is rolled out.

**Comment by juliusl** [comment] 2022-04-04 20:59
@favoretti np, just curious is there a flag I can set to see what the ACC tests are doing?

**Comment by favoretti** [comment] 2022-04-04 21:01
API-wise? TF_LOG=trace will spit out a LOT. TF_LOG_PATH=sometime will save it to a file you can inspect post-factum.

**Comment by juliusl** [comment] 2022-04-04 22:00
@favoretti I think I found a bug,
https://github.com/favoretti/terraform-provider-azurerm/blob/bdd4e8e706968b2cae9dfe876c2b5ba46c01dece/internal/services/containers/container_registry_agentpool_resource.go#L231
```
	client := meta.(*clients.Client).Containers.AgentPoolsClient
```

Shouldn't this be,

```
	client := meta.(*clients.Client).Containers.ContainerRegistryAgentPoolsClient
```

**Comment by favoretti** [comment] 2022-04-04 23:45
@juliusl I'll check tomorrow. The PR is old, so some stuff might have been renamed in new SDKs. I will rebase it tomorrow on the latest master and it will probably look a bit different :)

**Comment by favoretti** [comment] 2022-04-05 01:02
@juliusl just looked at the code.. facepalmed myself with a keyboard. Thanks!

**Comment by juliusl** [comment] 2022-04-05 03:10
@favoretti  cool beans! So I've tested this now in Canary Production,
```
--- PASS: TestAccContainerRegistryAgentPool_complete (821.59s)PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    821.601s 
```

The rollout should reach all regions sometime next week. I'll ping this thread again when it's complete :D

**Comment by favoretti** [comment] 2022-04-05 12:33
@juliusl Fresh code: https://github.com/hashicorp/terraform-provider-azurerm/pull/16258

**Comment by juliusl** [comment] 2022-04-11 20:53
@favoretti So this change has been deployed to all regions in the public cloud. I'm wasn't able to get your new branch to compile,

```
# github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning
internal/services/machinelearning/machine_learning_inference_cluster_resource.go:178:42: cannot use &aks (value of type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedCluster) as type *"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".ManagedCluster in argument to expandAksComputeProperties
# github.com/hashicorp/terraform-provider-azurerm/internal/services/containers
internal/services/containers/kubernetes_cluster_data_source.go:925:69: cannot use props.AddonProfiles (variable of type map[string]*"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterAddonProfile) as type map[string]*"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".ManagedClusterAddonProfile in argument to flattenKubernetesClusterDataSourceAddonProfiles
internal/services/containers/kubernetes_cluster_data_source.go:931:54: cannot use props.AddonProfiles (variable of type map[string]*"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterAddonProfile) as type map[string]*"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".ManagedClusterAddonProfile in argument to flattenKubernetesClusterDataSourceAddOns
internal/services/containers/kubernetes_cluster_data_source.go:941:76: cannot use props.AgentPoolProfiles (variable of type *[]"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterAgentPoolProfile) as type *[]"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".ManagedClusterAgentPoolProfile in argument to flattenKubernetesClusterDataSourceAgentPoolProfiles
internal/services/containers/kubernetes_cluster_data_source.go:946:77: cannot use props.IdentityProfile (variable of type map[string]*"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".UserAssignedIdentity) as type map[string]*"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".UserAssignedIdentity in argument to flattenKubernetesClusterDataSourceIdentityProfile
internal/services/containers/kubernetes_cluster_data_source.go:954:66: cannot use props.LinuxProfile (variable of type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".LinuxProfile) as type *"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".LinuxProfile in argument to flattenKubernetesClusterDataSourceLinuxProfile
internal/services/containers/kubernetes_cluster_data_source.go:959:70: cannot use props.WindowsProfile (variable of type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterWindowsProfile) as type *"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".ManagedClusterWindowsProfile in argument to flattenKubernetesClusterDataSourceWindowsProfile
internal/services/containers/kubernetes_cluster_data_source.go:964:70: cannot use props.NetworkProfile (variable of type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".NetworkProfile) as type *"github.com/Azure/azure-sdk-for-go/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice".NetworkProfile in argument to flattenKubernetesClusterDataSourceNetworkProfile
internal/services/containers/kubernetes_cluster_data_source.go:971:12: props.OidcIssuerProfile undefined (type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterProperties has no field or method OidcIssuerProfile)
internal/services/containers/kubernetes_cluster_data_source.go:972:13: props.OidcIssuerProfile undefined (type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterProperties has no field or method OidcIssuerProfile)
internal/services/containers/kubernetes_cluster_data_source.go:973:32: props.OidcIssuerProfile undefined (type *"github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-08-01/containerservice".ManagedClusterProperties has no field or method OidcIssuerProfile)
internal/services/containers/kubernetes_cluster_data_source.go:973:32: too many errors
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/containers [build failed]
```
Looks like some module conflicts, but you should be able to re-run your testing again.

**Comment by favoretti** [comment] 2022-04-11 20:56
@juliusl we released a rebased version this week, it seems it works! Thank you very much.

**Comment by juliusl** [comment] 2022-04-11 21:05
@favoretti Awesome! Glad it is working.

**Comment by juliusl** [comment] 2022-04-12 01:20
@ArcturusZhang I think we can close this issue now

**Closed** 2023-12-26 06:09 UTC
Labels: question, Container Registry, Service Attention, Mgmt, customer-reported, Network - Virtual Network, needs-team-attention
