### ISSUE TITLE
insights.ActivityLogsClient.ListComplete handling pagination incorrectly and gets 500 ISE on the 3rd page

### ISSUE THREAD

**Issue by grzn** [Azure/azure-sdk-for-go#15108] opened 2021-07-21 11:24 UTC
The following happens with azure-sdk-for-go v55.0.0, import path is _github.com/Azure/azure-sdk-for-go/profiles/2020-09-01/monitor/mgmt/insight_.

We noticed that there's an issue with the pagination in ListtComplete.
Consider the following iteration loop on the results:
```
for eventsSubList, err := client.ListComplete(ctx, filter, ""); err != nil || eventsSubList.NotDone(); err = eventsSubList.NextWithContext(ctx) {
	...
}
```

Where _filter_ is _"eventTimestamp ge %s and eventTimestamp le %s and resourceId eq '%s'"_ and resourceId is a storage account in our case.

When iterating to the 3rd page, the client receives 500 ISE from the server.

The first response from the server includes the following NextLink:
```
"https://management.azure.com/subscriptions/subscriptionId/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-04-22T08%3A52%3A32.894533268Z+and+eventTimestamp+le+2021-07-21T07%3A52%3A32.894533268Z+and+resourceId+eq+%27%2Fsubscriptions%2FsubscriptionId%2Fresourcegroups%2FresourceGroupName%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2FstorageAccountName%27&api-version=2015-04-01&$skipToken=EU1:-1:FFFFFFFF;US1:0637592029774418052:d5291b61;AS1:-1:FFFFFFFF"
```

The following API call returns this as the next link:
```
https://management.azure.com/subscriptions/subscriptionId/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-04-22T08%3A52%3A32.894533268Z+and+eventTimestamp+le+2021-07-21T07%3A52%3A32.894533268Z+and+resourceId+eq+%27%2Fsubscriptions%2FsubscriptionId%2Fresourcegroups%2FresourceGroupName%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2FstorageAccountName%27&%24skipToken=EU1%3A-1%3AFFFFFFFF&AS1%3A-1%3AFFFFFFFF=&US1%3A0637592029774418052%3Ad5291b61=&api-version=2015-04-01&$skipToken=EU1:-1:FFFFFFFF;US1:0637592029774418052:d5291b61;AS1:-1:FFFFFFFF
```

The client gets 500 ISE when attempting to fetch the next page.

Using a debugger, I see that the actual request being sent is
```
https://management.azure.com/subscriptions/subscriptionId/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-04-22T08%3A52%3A32.894533268Z+and+eventTimestamp+le+2021-07-21T07%3A52%3A32.894533268Z+and+resourceId+eq+%27%2Fsubscriptions%2FsubscriptionId%2Fresourcegroups%2FresourceGroupName%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2FstorageAccountName%27&%24skipToken=EU1%3A-1%3AFFFFFFFF&%24skipToken=EU1%3A-1%3AFFFFFFFF&AS1%3A-1%3AFFFFFFFF=&AS1%3A-1%3AFFFFFFFF=&US1%3A0637592029774418052%3Ad5291b61=&US1%3A0637592029774418052%3Ad5291b61=&api-version=2015-04-01
```
Doing the same with _az rest_ fails the same.

It looks like both client and server don't handle the $skipToken well, as the client sends two versions of it, one encoded and one that is not; the server doesn't handle that either.

**Comment by ArcturusZhang** [comment] 2021-08-03 07:53
Hi @grzn Thanks for this issue!

@jhendrixMSFT could you please help on this issue?

**Comment by grzn** [comment] 2021-09-09 11:22
any updates?

**Comment by lirenhe** [comment] 2021-09-10 07:45
@jhendrixMSFT , could you help to take a look?   Is this issue fixed in track2?

**Comment by AdallomRoy** [comment] 2021-11-08 15:23
@jhendrixMSFT @lirenhe Any updates?

**Comment by jhendrixMSFT** [comment] 2021-11-08 18:47
Sorry for the delay.

I'm trying to piece this together.  In your example, is the first `nextLink` value you provided (the one without any URL-encoded query params) the "raw" value that's sent from the service endpoint when attempting to iterate to the third page?

**Comment by grzn** [comment] 2021-11-08 18:53
Yes, it is

**Comment by jhendrixMSFT** [comment] 2021-11-08 19:11
What API is returning the second URL that you provided?  In my condensed repro, the returned URL without encoded query params fails to parse in the call to `NextWithContext`.  I'm probably missing something in my repro though.

**Comment by grzn** [comment] 2021-11-08 19:22
This is how we call it
```
	for eventsSubList, eventsErr := s.activityLogsClient.ListComplete(ctx, filter, ""); eventsErr != nil || eventsSubList.NotDone(); eventsErr = eventsSubList.NextWithContext(ctx) {
...
```

Where
```
filter is "eventTimestamp ge %s and eventTimestamp le %s and resourceId eq '%s'"
```
and resourceId is a storage account id

**Comment by jhendrixMSFT** [comment] 2021-11-08 20:31
I get that part.  Unfortunately I don't have any resources in my test subscription with enough events to get that far, so I'm trying to construct a targeted repro.  In my repro, I return a fake `EventDataCollection` with its `NextLink` field set to the value you provided.  However, when I call `NextWithContext` it fails when parsing the query parameters [here](https://github.com/Azure/go-autorest/blob/master/autorest/preparer.go#L244-L246).  Clearly my repro is incomplete, so I'm trying to understand where you observed the second URL provided.

**Comment by jhendrixMSFT** [comment] 2021-11-08 20:32
Also might help if you enable debug logging via `$env:AZURE_GO_SDK_LOG_LEVEL="debug"` and provide the spew.

**Comment by grzn** [comment] 2021-11-08 20:42
I ran it with dlv and took out the url from there. 

I’ll run it tomorrow with the debug env var tomorrow and paste here the output.

**Comment by grzn** [comment] 2021-11-09 10:17
Here's the debug output, I just deleted the values from the response body as its huge and I don't think you need it.
```
(2021-11-09T10:04:18.6047993Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-09T10:04:19.1260354Z) INFO: RESPONSE: 200 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11922
Strict-Transport-Security: max-age=31536000; includeSubDomains
Server: Microsoft-IIS/10.0
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211109T100419Z:0c61374f-4483-4e68-92df-f2cc8a75a1bc
Vary: Accept-Encoding,Accept-Encoding
X-Ms-Correlation-Request-Id: 0c61374f-4483-4e68-92df-f2cc8a75a1bc
Expires: -1
X-Ms-Request-Id: WestEurope_0424f78669494040a3d2ace528c9cb85_637720490590524087
Date: Tue, 09 Nov 2021 10:04:18 GMT
{"nextLink":"https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01&$skipToken=US1:0637720028736481134:ad5b2d5b;AS1:-1:FFFFFFFF","value":[]}

(2021-11-09T10:07:32.1881778Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720028736481134%3Aad5b2d5b&AS1%3A-1%3AFFFFFFFF=&api-version=2015-04-01
Content-Type: application/json
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-09T10:07:32.8154001Z) INFO: RESPONSE: 200 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720028736481134%3Aad5b2d5b&AS1%3A-1%3AFFFFFFFF=&api-version=2015-04-01
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211109T100732Z:e1e8c759-37b8-4cb0-afdb-5be827be3dc2
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Ms-Request-Id: WestEurope_24fb640a1d574f028a772834cc162090_637720492527593518
Server: Microsoft-IIS/10.0
X-Ms-Correlation-Request-Id: e1e8c759-37b8-4cb0-afdb-5be827be3dc2
Date: Tue, 09 Nov 2021 10:07:31 GMT
Cache-Control: no-cache
Pragma: no-cache
Vary: Accept-Encoding,Accept-Encoding
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11982
{"nextLink":"https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720028736481134%3Aad5b2d5b&AS1%3A-1%3AFFFFFFFF=&api-version=2015-04-01&$skipToken=US1:0637719567571793140:e72f7e4d;AS1:-1:FFFFFFFF","value":[]}

(2021-11-09T10:07:32.8745201Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720028736481134%3Aad5b2d5b&%24skipToken=US1%3A0637719567571793140%3Ae72f7e4d&AS1%3A-1%3AFFFFFFFF=&AS1%3A-1%3AFFFFFFFF=&api-version=2015-04-01
Content-Type: application/json
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-09T10:07:32.9995793Z) INFO: RESPONSE: 500 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-11T11%3A05%3A08.873274985Z+and+eventTimestamp+le+2021-11-09T10%3A05%3A08.873274985Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720028736481134%3Aad5b2d5b&%24skipToken=US1%3A0637719567571793140%3Ae72f7e4d&AS1%3A-1%3AFFFFFFFF=&AS1%3A-1%3AFFFFFFFF=&api-version=2015-04-01
Server: Microsoft-IIS/10.0
X-Ms-Correlation-Request-Id: f5c4353e-ef60-48b0-9e05-fd552b5be290
Content-Type: application/json; charset=utf-8
X-Ms-Failure-Cause: service
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11981
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 43
X-Ms-Request-Id: WestEurope_b934292d8a574dff9705f83542388ae6_637720492529624566
X-Content-Type-Options: nosniff
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211109T100732Z:f5c4353e-ef60-48b0-9e05-fd552b5be290
Date: Tue, 09 Nov 2021 10:07:32 GMT
{"code":"InternalServerError","message":""}

```

**Comment by jhendrixMSFT** [comment] 2021-11-09 18:28
Thanks this was helpful.

There are a few issues at play here.

- The server shouldn't be returning a non-encoded semicolon in the query parameter as it's a reserved character.
- Starting with Go 1.17, query parameters that contain a semicolon are now rejected by `url.ParseQuery` which is why I couldn't repro this (see [release notes](https://golang.org/doc/go1.17#semicolons)).

I think we can work around this by URL-encoding any semicolons in the query parameters until the service team can fix their responses.  I will follow up with the service team about that.

**Comment by jhendrixMSFT** [comment] 2021-11-09 19:04
Would you be able to test the fix to ensure there's no other things lurking?  Simply add the following `replace` directive to your go.mod file.
```
replace github.com/Azure/go-autorest/autorest => github.com/jhendrixMSFT/go-autorest/autorest v0.1.1-0.20211109183739-9e9c5cd5c1e5
```

**Comment by grzn** [comment] 2021-11-09 22:15
Thanks for the quick response.
I'll test it in the morning and will update.

**Comment by grzn** [comment] 2021-11-10 08:42
Same result:
```
(2021-11-10T08:36:45.8613631Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-10T08:36:46.3745639Z) INFO: RESPONSE: 200 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Vary: Accept-Encoding,Accept-Encoding
X-Ms-Request-Id: WestEurope_420c5cd7c5e444c0ab29d4e1cd239e4a_637721302062863524
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11938
X-Ms-Correlation-Request-Id: da7c0569-ecd1-4d66-a45d-49206403a7e7
Server: Microsoft-IIS/10.0
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211110T083646Z:da7c0569-ecd1-4d66-a45d-49206403a7e7
Date: Wed, 10 Nov 2021 08:36:46 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
{"nextLink":"https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&api-version=2015-04-01&$skipToken=US1:0637720799095698976:658258b0","value":[]}
(2021-11-10T08:36:46.4275493Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720799095698976%3A658258b0&api-version=2015-04-01
Content-Type: application/json
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-10T08:36:46.8477913Z) INFO: RESPONSE: 200 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720799095698976%3A658258b0&api-version=2015-04-01
Date: Wed, 10 Nov 2021 08:36:46 GMT
Pragma: no-cache
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211110T083646Z:41f2668c-1d69-4cd5-9cd0-6a7c2d88275c
X-Content-Type-Options: nosniff
Server: Microsoft-IIS/10.0
Expires: -1
X-Ms-Correlation-Request-Id: 41f2668c-1d69-4cd5-9cd0-6a7c2d88275c
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding,Accept-Encoding
X-Ms-Request-Id: WestEurope_a4dbfb297c9749c28b3ef939642c4c68_637721302067881931
Cache-Control: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11937
{"nextLink":"https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720799095698976%3A658258b0&api-version=2015-04-01&$skipToken=US1:0637720300240650534:a59d6c3d;AS1:-1:FFFFFFFF","value":[]}
(2021-11-10T08:36:46.8985577Z) INFO: REQUEST: GET https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720799095698976%3A658258b0&%24skipToken=US1%3A0637720300240650534%3Aa59d6c3d%3BAS1%3A-1%3AFFFFFFFF&api-version=2015-04-01
Content-Type: application/json
User-Agent: Go/go1.16.8 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.0.0 insights/2019-06-01
Authorization: **REDACTED**
(2021-11-10T08:36:47.0084641Z) INFO: RESPONSE: 500 https://management.azure.com/subscriptions/74bf2795-8375-49d1-ab43-e6656f93e94e/providers/microsoft.insights/eventtypes/management/values?%24filter=eventTimestamp+ge+2021-08-12T09%3A37%3A17.413306342Z+and+eventTimestamp+le+2021-11-10T08%3A37%3A17.413306342Z+and+resourceId+eq+%27%2Fsubscriptions%2F74bf2795-8375-49d1-ab43-e6656f93e94e%2Fresourcegroups%2Fdefaultresourcegroup-cus%2Fproviders%2Fmicrosoft.storage%2Fstorageaccounts%2Fstorageforit%27&%24skipToken=US1%3A0637720799095698976%3A658258b0&%24skipToken=US1%3A0637720300240650534%3Aa59d6c3d%3BAS1%3A-1%3AFFFFFFFF&api-version=2015-04-01
Server: Microsoft-IIS/10.0
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11936
Pragma: no-cache
Content-Length: 43
X-Ms-Request-Id: WestEurope_4e52deffc61f483f80371547daac427d_637721302069848250
X-Ms-Correlation-Request-Id: d0230b66-c6ca-4b82-a5bb-b75d6cc2c594
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Expires: -1
Date: Wed, 10 Nov 2021 08:36:46 GMT
Cache-Control: no-cache
X-Ms-Failure-Cause: service
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Ms-Routing-Request-Id: SWEDENCENTRAL:20211110T083646Z:d0230b66-c6ca-4b82-a5bb-b75d6cc2c594
{"code":"InternalServerError","message":""}
(2021-11-10T08:36:47.0085376Z) INFO: DelayForBackoffWithCap: sleeping for 30s
```

**Comment by jhendrixMSFT** [comment] 2021-11-10 15:29
Thanks for the info, at least we know it's not due to unencoded query params.  I'll follow up with the service team about this as it's pretty clear at this point the issue is on their side.

**Comment by grzn** [comment] 2021-11-10 23:16
Great. 
Id there a public issue tracker for that we can follow or should we expect updates from you on this thread?

**Comment by jhendrixMSFT** [comment] 2021-11-11 16:14
I will post back here as I have more info.

**Comment by grzn** [comment] 2021-12-03 12:55
Hi @jhendrixMSFT  do you have an update on this?

**Comment by jhendrixMSFT** [comment] 2021-12-14 02:05
Sorry for the delay.  I've had a hard time tracking down the owner of this API.  Still looking.

**Comment by AdallomRoy** [comment] 2021-12-29 17:15
@jhendrixMSFT any news?

**Comment by jhendrixMSFT** [comment] 2022-01-03 21:07
Now that I'm back from vacation, I believe I found an owner.  Will post an update when I have more info.

**Comment by grzn** [comment] 2022-01-20 19:25
Hi @jhendrixMSFT , do you have an updated on this for us?

**Comment by jhendrixMSFT** [comment] 2022-03-30 16:03
Ping @azmonapplicationinsights

**Comment by AdallomRoy** [comment] 2022-05-30 07:24
Any news on this? Almost a year now, very embarrassing bug... quite disappointing...

**Comment by tadelesh** [comment] 2023-12-26 06:11
We have retired support for Azure SDK for Golang libraries which do not conform to our [current Azure SDK guidelines](https://azure.github.io/azure-sdk/general_introduction.html) (see [announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/)). Please migrate to the latest version according to the [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/profile-migration-guide.md). If you could still repo this problem, please submit a support ticket in Azure directly.

**Closed by tadelesh** 2023-12-26 06:11 UTC
Labels: bug, Service Attention, Mgmt, customer-reported, Monitor - ApplicationInsights
