### ISSUE TITLE
unexpected fault address -SIGBUS: bus error code=0x2

### ISSUE THREAD

**Issue by rajdhandus** [Azure/azure-sdk-for-go#14489] opened 2021-04-04 14:45 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
github.com/Azure/azure-storage-blob-go/azblob
- SDK version e.g. `master`, `latest`, `18.1.0`
github.com/Azure/azure-sdk-for-go v43.1.0+incompatible
github.com/Azure/azure-storage-blob-go v0.9.0
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`
golang:1.15

- What happened?
Program crashed while copying
- What did you expect or want to happen?
Program to no crash
- How can we reproduce it?
- Anything we should know about your environment.

Stacktrace:

unexpected fault address 0x7fe538591f80
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fe538591f80 pc=0x46ce65]

goroutine 653 [running]:
runtime.throw(0x7d8c89, 0x5)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0004bb910 sp=0xc0004bb8e0 pc=0x437032
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:717 +0x485 fp=0xc0004bb940 sp=0xc0004bb910 pc=0x44c9e5
runtime.memmove(0xc0002b6000, 0x7fe53858a000, 0x8000)
        /usr/local/go/src/runtime/memmove_amd64.s:332 +0x3c5 fp=0xc0004bb948 sp=0xc0004bb940 pc=0x46ce65
bytes.(*Reader).Read(0xc000064240, 0xc0002b6000, 0x8000, 0x8000, 0x7fe563fa47d0, 0x0, 0x0)
        /usr/local/go/src/bytes/reader.go:45 +0xb1 fp=0xc0004bb978 sp=0xc0004bb948 pc=0x4a9af1
github.com/Azure/azure-pipeline-go/pipeline.(*retryableRequestBody).Read(0xc000a78220, 0xc0002b6000, 0x8000, 0x8000, 0x75e880, 0xc0004bba01, 0xc0002b6000)
        /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/request.go:129 +0x51 fp=0xc0004bb9c0 sp=0xc0004bb978 pc=0x6df791
io.(*LimitedReader).Read(0xc0003987a0, 0xc0002b6000, 0x8000, 0x8000, 0x0, 0x4d0900, 0x8)
        /usr/local/go/src/io/io.go:455 +0x63 fp=0xc0004bba08 sp=0xc0004bb9c0 pc=0x4a0643
io.copyBuffer(0x7fe53979df68, 0xc0003b3500, 0x84e1e0, 0xc0003987a0, 0xc0002b6000, 0x8000, 0x8000, 0x792e00, 0xc00051a801, 0x7fe53979df48)
        /usr/local/go/src/io/io.go:409 +0x12c fp=0xc0004bba80 sp=0xc0004bba08 pc=0x4a036c
io.Copy(...)
        /usr/local/go/src/io/io.go:368
net/http.persistConnWriter.ReadFrom(0xc0004eb8c0, 0x84e1e0, 0xc0003987a0, 0x7fe53979df48, 0xc0004eb8c0, 0x1)
        /usr/local/go/src/net/http/transport.go:1733 +0x85 fp=0xc0004bbae0 sp=0xc0004bba80 pc=0x665985bufio.(*Writer).ReadFrom(0xc0006c1800, 0x84e1e0, 0xc0003987a0, 0x7fe53978e0a0, 0xc0006c1800, 0x1)
        /usr/local/go/src/bufio/bufio.go:730 +0x370 fp=0xc0004bbb68 sp=0xc0004bbae0 pc=0x537230
io.copyBuffer(0x84db80, 0xc0006c1800, 0x84e1e0, 0xc0003987a0, 0x0, 0x0, 0x0, 0xc0004bbc48, 0x40f838, 0x20)
        /usr/local/go/src/io/io.go:395 +0x2ff fp=0xc0004bbbe0 sp=0xc0004bbb68 pc=0x4a053f
io.Copy(...)
        /usr/local/go/src/io/io.go:368
net/http.(*transferWriter).doBodyCopy(0xc00012a960, 0x84db80, 0xc0006c1800, 0x84e1e0, 0xc0003987a0, 0xc0004bbcc8, 0x6658b2, 0xc0003b3500)
        /usr/local/go/src/net/http/transfer.go:400 +0x6a fp=0xc0004bbc58 sp=0xc0004bbbe0 pc=0x65976a
net/http.(*transferWriter).writeBody(0xc00012a960, 0x84db80, 0xc0006c1800, 0x2, 0x2)
        /usr/local/go/src/net/http/transfer.go:359 +0x710 fp=0xc0004bbd38 sp=0xc0004bbc58 pc=0x659630
net/http.(*Request).write(0xc0000e0600, 0x84db80, 0xc0006c1800, 0x0, 0xc000064480, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:682 +0x6e5 fp=0xc0004bbe98 sp=0xc0004bbd38 pc=0x6515e5
net/http.(*persistConn).writeLoop(0xc0004eb8c0)
        /usr/local/go/src/net/http/transport.go:2343 +0x1c5 fp=0xc0004bbfd8 sp=0xc0004bbe98 pc=0x668805
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0004bbfe0 sp=0xc0004bbfd8 pc=0x46bce1
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1709 +0xcdc

**Comment by ArcturusZhang** [comment] 2021-04-07 08:00
Hi @rajdhandus thanks for this issue.

I notice that there is one line in the panic information here: 
```
/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/request.go:129
```
The azure-sdk-for-go (this repo) never uses this library in the implementation, therefore I suppose the panic should come from the storage SDK `github.com/Azure/azure-storage-blob-go`. Could you please open an issue in [that repo](https://github.com/Azure/azure-storage-blob-go)?
And since the issue is not caused by azure-sdk-for-go, I am going to close this issue and hope you do not mind. Thanks

**Closed by ArcturusZhang** 2021-04-07 08:00 UTC
Labels: customer-reported, needs-triage, question
