### ISSUE TITLE
[azblob] BlobURLParts does not support VersionID

### ISSUE THREAD

**Issue by hy3** [Azure/azure-sdk-for-go#17188] opened 2022-02-28 09:09 UTC
### Bug Report

- import path of package: `.../sdk/storage/azblob`
- SDK version: `v0.3.0`
- go version: `go1.17.6 darwin/amd64`

I'm using Azure Blob Storage with version management, and want to download old version with this SDK. So, I tried to use `BlobClient.WithVersionID()` or `BlobURLParts.VersionID` , but both of them didn't work.
Because `BlobURLParts` outputs URL without VersionID, nevertheless [preview SDK](https://github.com/Azure/azure-storage-blob-go) does it. ( [ref.](https://github.com/Azure/azure-storage-blob-go/blob/b32b5e3579400739418747a71c4bffaf8a19c4a0/azblob/parsing_urls.go#L150-L156) )

If it is as expected, please tell me how to download blob by Version ID with the SDK.
I avoiding this issue by editing URL directly, but It doesn't look smart way.

```go
u, _ := url.Parse(blobClient.URL())

q := u.Query()
q.Set("versionId", versionID)
u.RawQuery = q.Encode()

newBlobClient, _ := azblob.NewBlobClient(u.String(), cred, nil)
```

**Comment by amishra-dev** [comment] 2022-03-01 17:30
Thanks for this report @hy3. Currently there maynot be a way to do this other than edit URL @mohsha-msft to confirm.

**Comment by mohsha-msft** [comment] 2022-03-02 06:41
Hey @hy3 ,

Thanks for reaching out!

Yes this is indeed a bug at our end. Somehow it got escaped from our tests. I apologize for inconvenience. I've raised a request to fix it and added more tests to make sure this doesn't happen in future. We'll ship it in next release. In the meantime, you can pull the changes from my branch by using the command

`go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@mohsha-msft-azblob-fix-versioning-bug`

Please reach out for any clarification!

**Comment by hy3** [comment] 2022-03-03 03:55
@mohsha-msft @amishra-dev 
Thanks for your reply. I got it. I'm looking forward to next release.

**Comment by hy3** [comment] 2022-03-03 04:14
@mohsha-msft 
I found same bug in `NewBlobURLParts()` not only in `BlobURLParts.URL()` .
[Your commit](https://github.com/Azure/azure-sdk-for-go/commit/a822686cbc1f0551fc057569262847133d278af8) does not include it. Please fix it too.

This is example in `azure-storage-blob-go` .
https://github.com/Azure/azure-storage-blob-go/blob/b32b5e3579400739418747a71c4bffaf8a19c4a0/azblob/parsing_urls.go#L98-L103

**Comment by mohsha-msft** [comment] 2022-03-10 16:10
Fixed in main. Target release for next release.

@hy3, can you give it a try and let me know if the issue is persisting?

**Comment by hy3** [comment] 2022-03-14 08:58
@mohsha-msft 
It works 🎉 

However, through my trying, I found that `BlobClient.WithVersionID()` returns not `BlobClient` but `BlockBlobClient` .
Is it right ?

**Comment by mohsha-msft** [comment] 2022-03-14 09:29
Yes that's correct. It'll be fixed too.

**Comment by hy3** [comment] 2022-03-15 04:50
Thanks a lot !

The SDK is already a big help for me. I'll continue to use it and give feedback on it.
I'm looking forward to its stable release :+1:

**Comment by mohsha-msft** [comment] 2022-04-20 05:17
Hey @hy3 ,

[azblob v0.4.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is now publically available. I have fixed the issue [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#BlobURLParts) and [here](https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azblob/v0.4.0/sdk/storage/azblob/zc_parsing_urls.go#L135). 

Please reach out and reopen the issue if it still persists. 

Thanks a lot for your feedbacks!

**Closed by mohsha-msft** 2022-04-20 05:17 UTC
Labels: Storage, Client, customer-reported
