### ISSUE TITLE
pkg.go.dev not showing all API clients

### ISSUE THREAD

**Issue by jlk** [Azure/azure-sdk-for-go#14028] opened 2020-12-17 06:30 UTC
### Bug Report

Folks - I'm not positive if this is a godoc bug on the `azure-sdk-for-go` side, or an issue with the new pkg.go.dev. Either way, a heads up:

Looking at the future godoc home of https://pkg.go.dev/github.com/Azure/azure-sdk-for-go, it's currently only showing me about 48 directories. Many many API clients are missing.

If I look at https://godoc.org/github.com/Azure/azure-sdk-for-go, I'm seeing as I'd expect - in the hundreds.

The sites are switching over in "early 2021," although I'm not sure how early that is. I suspect the size of this SDK might be causing issues?

**Comment by ArcturusZhang** [comment] 2020-12-17 09:19
Hi @jlk thanks for this issue!

@jhendrixMSFT I see that `pkg.go.dev` only shows the track 2 modules, Is this issue caused by our track 1 SDK is not using modules?

**Comment by jhendrixMSFT** [comment] 2020-12-17 15:28
That's correct.  The content in `pkg.go.dev` is created by scanning the Go module mirror, and since track 1 doesn't use modules it won't show up there.

See https://go.dev/about for details.

**Comment by jhendrixMSFT** [comment] 2021-01-04 16:31
Closing as this is behaving as intended.

**Closed by jhendrixMSFT** 2021-01-04 16:31 UTC
Labels: customer-reported, docs, question
