### ISSUE TITLE
Missing Path Parameters leading to API Version error

### ISSUE THREAD

**Issue by marstr** [Azure/azure-sdk-for-go#809] opened 2017-10-11 16:07 UTC
As seen in #803 and #805, in cases where there are missing arguments to path parameters, a misleading error comes back complaining about the API Version. I believe this is due to the fact that you end up hitting an ARM Resource endpoint instead of a particular subdomain, and the ARM Resource service will have it's own API Version expectations. As evidence of that, consider that the API Versions that are reported back don't match those of [compute](https://github.com/Azure/azure-rest-api-specs/tree/453c13ca1e1eb631e6e7c44757ba2d6ab9886b48/specification/compute/resource-manager) or [network](https://github.com/Azure/azure-rest-api-specs/tree/453c13ca1e1eb631e6e7c44757ba2d6ab9886b48/specification/network/resource-manager), but do match [ARM's](https://github.com/Azure/azure-rest-api-specs/tree/453c13ca1e1eb631e6e7c44757ba2d6ab9886b48/specification/resources/resource-manager).

To prevent returning back a misleading error, we could add validation before the request is sent to ensure that Path items are not empty or at least that Resource Group is not empty.

**Comment by salameer** [comment] 2017-10-16 22:20
@jhendrixMSFT  please syncup and handoff to @vladbarosan

**Comment by vladbarosan** [comment] 2017-10-25 21:58
This issue I would say is not Go SDK specific. I opened 2 new issues for the changes I am doing ( Azure/azure-rest-api-specs#1918 and  Azure/azure-rest-api-specs#1919 ) . I would close this as a duplicate.

**Comment by vladbarosan** [comment] 2017-11-02 17:26
duplicate of Azure/azure-rest-api-specs#1918

**Closed by vladbarosan** 2017-11-02 17:26 UTC
Labels: Sprint-108
