### ISSUE TITLE
[azopenai] Not able to use ChatCompletionsJSONResponseFormat

### ISSUE THREAD

**Issue by mc-mario** [Azure/azure-sdk-for-go#22144] opened 2023-12-14 12:19 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
```
"github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai"
"github.com/Azure/azure-sdk-for-go/sdk/azcore"
"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
```
- SDK version 
`0.4.0`

- output of `go version`
`go version go1.21.1 darwin/arm64`

## - What happened?
Trying to set `ResponseFormat` in `ChatCompletionsOptions` as `ChatCompletionsJSONResponseFormat` results in a 400.

```go
resp, err := client.GetChatCompletions(context.TODO(), azopenai.ChatCompletionsOptions{
		Messages:       messages,
		MaxTokens:      to.Ptr(int32(2048)),
		Temperature:    to.Ptr(float32(0.0)),
		DeploymentName: to.Ptr(a.DeploymentName),
		ResponseFormat: to.Ptr(azopenai.ChatCompletionsJSONResponseFormat{}),
	}, nil)
```

<img width="414" alt="image" src="https://github.com/Azure/azure-sdk-for-go/assets/29338719/f0ab60c3-98b4-4f5e-9a2f-d4c23576aaf3">

## - What did you expect or want to happen?
Be able to use ResponseFormat. Works fine if you comment out ResponseFormat but need to include a prompt to force JSON output.

## - How can we reproduce it?
Use a gpt-4 deployment. Version `1106-Preview`.

**Comment by richardpark-msft** [comment] 2023-12-16 02:18
Your code looks good to me, matches (more or less) what I have here: [link](https://github.com/Azure/azure-sdk-for-go/blob/2621632e48ea508e16ce568001402f92fca4afa0/sdk/ai/azopenai/client_chat_completions_test.go#L284). 

The 400 error makes me think something's not serializing properly. I need to see the response body to get an idea of what's missing there. Can you run your test and enable logging like I've got here?

1. Set Azure's logging to log the response body:

   ```go
   co := &azopenai.ClientOptions{}
   co.Logging.IncludeBody = true
   
   // (then pass 'co' to your azopenai.NewClient*() call)
   ```

2. In the environment set `AZURE_SDK_GO_LOGGING` to `all`.

This'll give me more of an idea of what's going on.

**Comment by richardpark-msft** [comment] 2024-04-03 01:31
Closing as there hasn't been any response in awhile and I'm unable to reproduce this bug.

@mc-mario, if you have more info please reopen.

**Closed by richardpark-msft** 2024-04-03 01:31 UTC
Labels: question, customer-reported, needs-team-attention, customer-response-expected, OpenAI
