### ISSUE TITLE
Redis SDK: Schema doesn't match on Read

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#459] opened 2016-11-16 16:09 UTC
Hello Again! 👋 

I believe I've found another bug in the Redis SDK. When calling a Get request - the API returns the following JSON:
```
{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-8068841053713972281/providers/Microsoft.Cache/Redis/acctestRedis-8068841053713972281",
	"location": "West US",
	"name": "acctestRedis-8068841053713972281",
	"type": "Microsoft.Cache/Redis",
	"tags": {},
	"properties": {
		"provisioningState": "Succeeded",
		"redisVersion": "3.0",
		"sku": {
			"name": "Basic",
			"family": "C",
			"capacity": 1
		},
		"enableNonSslPort": false,
		"redisConfiguration": {
			"maxclients": "1000",
			"maxmemory-reserved": "50",
			"maxmemory-delta": "50"
		},
		"accessKeys": null,
		"hostName": "acctestRedis-8068841053713972281.redis.cache.windows.net",
		"port": 6379,
		"sslPort": 6380
	}
}
```

The SDK contains the following Schema which doesn't match - meaning that the Properties object in the ResourceProperties class is nil. This is the relevant code from the SDK:
```
// CreateProperties is properties supplied to Create redis operation.
type CreateProperties struct {
	RedisConfiguration *map[string]*string `json:"redisConfiguration,omitempty"`
	EnableNonSslPort   *bool               `json:"enableNonSslPort,omitempty"`
	TenantSettings     *map[string]*string `json:"tenantSettings,omitempty"`
	ShardCount         *int32              `json:"shardCount,omitempty"`
	SubnetID           *string             `json:"subnetId,omitempty"`
	StaticIP           *string             `json:"staticIP,omitempty"`
	Sku                *Sku                `json:"sku,omitempty"`
}

// ResourceProperties is parameters describing a redis instance
type ResourceProperties struct {
	RedisVersion      *string           `json:"redisVersion,omitempty"`
	ProvisioningState *string           `json:"provisioningState,omitempty"`
	HostName          *string           `json:"hostName,omitempty"`
	Port              *int32            `json:"port,omitempty"`
	SslPort           *int32            `json:"sslPort,omitempty"`
	Properties        *CreateProperties `json:"properties,omitempty"`
}

// ResourceType is a single redis item in List or Get Operation.
type ResourceType struct {
	autorest.Response `json:"-"`
	ID                *string             `json:"id,omitempty"`
	Name              *string             `json:"name,omitempty"`
	Type              *string             `json:"type,omitempty"`
	Location          *string             `json:"location,omitempty"`
	Tags              *map[string]*string `json:"tags,omitempty"`
	Properties        *ResourceProperties `json:"properties,omitempty"`
}

type Sku struct {
	Name     SkuName   `json:"name,omitempty"`
	Family   SkuFamily `json:"family,omitempty"`
	Capacity *int32    `json:"capacity,omitempty"`
}
```

Given the two don't marry up, Properties is nil - and fails my tests :(

I take it the response needs to be fixed, rather than the API? As a side-note - it seems odd that a Get request returns a CreateProperties in the first place (given it implies it's Created it?)

Thanks!

**Comment by colemickens** [comment] 2016-11-16 18:39
For these sorts of bugs, can you file a corresponding bug against the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) where the Swagger specifications live? Then they can be pulled and used to update this SDK. Thanks.

**Comment by TimLovellSmith** [comment] 2016-11-16 21:09
@tombuildsstuff @colemickens The response JSON looks as expected, unless you've noticed a specific issue with the swagger, I would assume this is a bug specific to the GO sdk generated code.

**Comment by colemickens** [comment] 2016-11-16 21:12
@TimLovellSmith I don't understand, the structs in the parent post are generated from Swagger and don't align with the actual response posted.

**Comment by TimLovellSmith** [comment] 2016-11-16 21:15
@colemickens Yes they're generated from swagger, but I don't see anything in the swagger [ https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json
] that looks wrong. It specifies that the response of a PUT operation returning 201 is a RedisResource... which should be correct.

**Comment by colemickens** [comment] 2016-11-16 21:18
But the OP is doing a GET operation. The structs in Go look to be properly mapped to the Swagger spec that I'm looking at. The Swagger spec for a GET just doesn't match what the OP has posted above.

**Comment by TimLovellSmith** [comment] 2016-11-16 21:20
@colemickens How doesn't it match? GET also returns a RedisResource, same as PUT.

**Comment by colemickens** [comment] 2016-11-16 21:20
For example, according to the Swagger, the "sku" and "redisConfiguration" fields are NOT supposed to be sibling fields to "provisioningState". Yet they are siblings in the real response returned and shown above.

**Comment by TimLovellSmith** [comment] 2016-11-16 21:22
@colemickens 
Ah, I think the problem is only I am interpreting the "x-ms-client-flatten": true directive in the swagger.

**Comment by colemickens** [comment] 2016-11-16 21:23
Ah-ha, thanks! In this case, I think I might agree then, it's possible the Go generator doesn't respect the `x-ms-client-flatten` field. @mcardosos can you tell us if this is the case?

**Comment by mcardosos** [comment] 2016-11-16 21:25
Flattening is not currently supported in the Go generator

**Comment by colemickens** [comment] 2016-11-16 21:47
Thanks for letting us know.

Can we get an issue to track the addition of flattening then?

**Comment by mcardosos** [comment] 2016-11-16 22:14
Looking again at this, shouldn't `Create` also return a `RedisResource`? Right now it returns an `autorest.Response`.

**Comment by tombuildsstuff** [comment] 2016-11-17 06:06
thanks @colemickens / @mcardosos / @TimLovellSmith - will do.

**Comment by marstr** [comment] 2017-02-13 23:51
We've just checked, and it seems that this has been thoroughly solved. We'll close this issue out. If there is need for further work, feel free to reopen this issue.

**Closed by marstr** 2017-02-13 23:51 UTC
Labels: External, P2
