### ISSUE TITLE
[question] proper way to list machines

### ISSUE THREAD

**Issue by raffaelespazzoli** [Azure/azure-sdk-for-go#14110] opened 2021-01-08 16:23 UTC
This is a question, not a bug report

I'm trying to get a list of VMs, I'm running this call:

```golang
i.compute.ListComplete(context, resourceGroupName)
```
and I get an empty result, not an error.

If I do the same from the command line:
```shell
az vm list -g cluster-raffa-zqh7w-rg
```
using the same resourceGroupName, I get the expected result?
What am I doing worng? Could this be a permission issue? 
What role do I need to list machines?
Currently the account used to make the call has this role: `"Virtual Machine Contributor"`.

I get the same empty result set also with:

```golang
i.compute.List(context, resourceGroupName)
```

Import package
`"github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-30/compute"`

package version
`github.com/Azure/azure-sdk-for-go v49.2.0`

go version 1.15

**Comment by ArcturusZhang** [comment] 2021-01-11 04:19
Hi @raffaelespazzoli thanks for opening this issue!

Could you also provide some request log related with this request for us to better debug this issue? You can enable the request log by exporting an environment variable `AZURE_GO_SDK_LOG_FILE=DEBUG`

**Comment by raffaelespazzoli** [comment] 2021-01-11 13:19
It turned out I didn't have enough permissions. `Contributor` was needed. It's weird and I'd like to understand why. Also one would expect the call to return 401 if not enough permissions are available, not an empty result set.

**Comment by ArcturusZhang** [comment] 2021-01-12 01:39
> It turned out I didn't have enough permissions. `Contributor` was needed. It's weird and I'd like to understand why. Also one would expect the call to return 401 if not enough permissions are available, not an empty result set.

Well, then this might turn into a service issue. Let me tag this issue so that the service team might have a look.

**Comment by Drewm3** [comment] 2021-01-13 07:40
I am pretty sure this is the right design. Consider a scenario where there is a resource group with 3 VMs, but the caller only has access to list one of the 3 VMs. You do not expect to get two errors and one VM returned successfully. Instead you should expect to only see the one VM. In fact, if the error was returned indicating not enough access to list the VM, it would be an information leak security concern if the name or URI of the VM was returned in the error.

@raffaelespazzoli, please let me know if this makes sense. If you have examples of other Azure APIs that operate differently then please let me know so that we can investigate why difference services are operating differently in this scenario.

**Comment by Drewm3** [comment] 2021-01-22 18:59
I am going to close this issue because it is the expected behavior and I believe I have answered the question. @raffaelespazzoli, please let me know if you still have questions on this one.

**Closed by Drewm3** 2021-01-22 18:59 UTC
Labels: Compute - VM, Service Attention, customer-reported, question
