### ISSUE TITLE
Required enum in Swagger model misses the enum type definition in Go SDK

### ISSUE THREAD

**Issue by magodo** [Azure/azure-sdk-for-go#14589] opened 2021-04-26 05:47 UTC
### Bug Report

There are some enums defined in Swagger, which happens to be `Required` and with only one enum value, end up being a plain `*string` in the Go SDK.

Example: `securityinsight` - `AutomationRuleTriggeringLogic` ([swagger](https://github.com/Azure/azure-rest-api-specs/blob/ad5f2295c36461875b75f83e9579eadddf73d356/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L6364-L6364), [Go SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/models.go#L3044))

**This might also impact track2**.

**Comment by ArcturusZhang** [comment] 2021-04-26 06:01
I have confirmed that this should be some logic in the modeler v1 - the modeler generated in this case will mark this field as a plain string instead of an enum type.

@jhendrixMSFT is the intention that modeler v1 is doing this because it is expecting the downstream SDKs could hard code this in the SDK?
How would modeler v4 behave in this case?

**Comment by jhendrixMSFT** [comment] 2021-04-26 14:52
In track 2 we treat such values as constants and embed them directly into the generated code.

**Comment by chamons** [comment] 2021-07-22 15:43
If this is marked wontfix, does that mean we should close it @ArcturusZhang @jhendrixMSFT?

**Comment by ArcturusZhang** [comment] 2021-08-05 06:55
Close this since we will not introduce a fix for this in track 1 SDK

**Closed by ArcturusZhang** 2021-08-05 06:55 UTC
Labels: Client, CodeGen, feature-request, wontfix
