### ISSUE TITLE
Generated Code Sets Non-Canonical Headers

### ISSUE THREAD

**Issue by Bharat-Goyal** [Azure/azure-sdk-for-go#23829] opened 2024-12-04 20:09 UTC
### Bug Report

Generated code in azdatalake directly sets http headers https://github.com/Azure/azure-sdk-for-go/blob/sdk/storage/azdatalake/v1.3.0/sdk/storage/azdatalake/internal/generated/zz_path_client.go#L1 instead of using the `req.req.Header.Set` because of which processing the request outside of azdatalake requires dealing with `Header` as a map instead of using `Set` and `Get`. 

- Package `/sdk/storage/azdatalake`
- SDK version master

The official documentation has canonicalized headers so this can lead to some confusions.

**Comment by jhendrixMSFT** [comment] 2024-12-04 20:43
This is by design and due to some unique legacy behaviors of the storage services. Specifically, this part from the [docs](https://learn.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources#Subheading1).

> Note that metadata names preserve the case with which they were created, but are case-insensitive when set or read.

Can you clarify the problem this is causing?

**Comment by Bharat-Goyal** [comment] 2024-12-06 07:09
@jhendrixMSFT I actually thought that metadata name casing is no longer preserved because when i parse the metadata headers, they are always canonicalised (eg: if I set a property `prop-name` using the go sdk, the response contains the property `Prop-Name`. Is there a way to avoid this case information loss?

**Comment by jhendrixMSFT** [comment] 2024-12-06 14:17
For responses you're correct the headers are canonicalized. This happens as part of the underlying transport in the standard library and there's no way for us to disable this behavior.

**Comment by Bharat-Goyal** [comment] 2024-12-06 19:16
@jhendrixMSFT ideally in this case then the non canonical headers would only be used for the `X-Ms-Properties` header while the others use the `Set` method, but this isn't a major issue for me so if it's a lot of effort feel free to close this issue, I'd really appreciate it if I could get some help for https://github.com/Azure/azure-sdk-for-go/issues/23841 because that's a major blocker for me.

**Comment by jhendrixMSFT** [comment] 2024-12-06 19:39
Changing the way we set headers at this point would likely break somebody so I will close this.

Regarding the other issue, I've routed it to the owners of the storage SDKs to take a look.

**Closed** 2024-12-06 19:39 UTC
Labels: question, Storage, customer-reported, needs-team-attention, needs-team-triage
