### ISSUE TITLE
Cosmos DB CheckNameExists failing with 500 (again)

### ISSUE THREAD

**Issue by jackofallops** [Azure/azure-sdk-for-go#9891] opened 2020-06-03 11:02 UTC
### Bug Report
Issue #5157 appears to have resurfaced with the same symptoms.

```
az cosmosdb check-name-exists --name doesntexist
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.DocumentDB/databaseAccountNames/doesntexist?api-version=2019-12-12 (Caused by ResponseError('too many 500 error responses'))
```

https://github.com/terraform-providers/terraform-provider-azurerm/issues/7173

**Comment by erikschlegel** [comment] 2020-06-03 12:19
JFYI, this issue is blocking my team from provisioning cosmos envionments. Verified this issue exists for eastus, centralus, westus and eastus2 regions.

**Comment by markjbrown** [comment] 2020-06-03 18:51
We have identified the root cause for this and are actively working on a hot fix to the issue. ETA should be tomorrow.

Thanks.

**Comment by markjbrown** [comment] 2020-06-03 23:48
We've deployed the fix for this and the issue is resolved.

**Comment by ArcturusZhang** [comment] 2020-06-04 02:34
Hi @jackofallops could you please have a try if the fix works or not?

**Comment by jackofallops** [comment] 2020-06-04 11:09
> Hi @jackofallops could you please have a try if the fix works or not?

A quick test suggests this is resolved, thanks for the timely action!

**Closed** 2020-06-04 11:10 UTC
Labels: Cosmos, Mgmt, customer-reported
