### ISSUE TITLE
SQLVirtualMachinesClient.Get returning 500

### ISSUE THREAD

**Issue by fnocera** [Azure/azure-sdk-for-go#11575] opened 2020-07-14 21:32 UTC
### Bug Report

- import path of package in question: `azure-sdk-for-go/services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachineapi/`
- SDK version: `github.com/Azure/azure-sdk-for-go v44.0.0`

- What happened?
We are using the `azurerm_mssql_virtual_machine` terraform provider which recently got a dependency update to `azure-sdk-for-go v44.0.0` in this [commit](https://github.com/terraform-providers/terraform-provider-azurerm/commit/6654794e18922c49fecb127221255e9bf9a3dfc3) and [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/7616). Since then we have been getting a 500 error from the 
SQLVirtualMachinesClient.Get call that happens at the end of provisioning the resource. This results in the resource being provisioned but terraform thinks this has failed. 
We have tried accessing the same provisioned resource using this [API call](https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/get#code-try-0) and it is successful so believe it might be a bug in the go sdk 
As reference we have also opened an issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/7747 on the terraform/provider/azurerm repo.

- What did you expect or want to happen? 
The call to the SQLVirtualMachinesClient.Get is supposed to return 200 to indicate the resource is successfully provisioned.
 
- Anything we should know about your environment.
We are using Terraform v0.12.25 and azurerm provider v2.11.0 (also tried with latest v2.18.0) 

cc @yutyang

**Comment by jongio** [comment] 2020-07-14 23:16
@mayurid @jhendrixMSFT - Thoughts on who could have a look at this?

**Comment by fnocera** [comment] 2020-07-15 01:22
As an update we have also tried with azurerm provider version 2.10.0 but we are getting the same error.

**Comment by mybayern1974** [comment] 2020-07-15 05:15
A service rest api issue got filed: https://github.com/Azure/azure-rest-api-specs/issues/10144. Per investigation this is not something abnormal on Terraform or GO SDK, but at the service behavior.

**Comment by fnocera** [comment] 2020-07-15 14:45
We have continued our investigation on this to understand the exact API calls being made by the go sdk. This is the exact GET request being made 
``` 
GET /subscriptions/<subscription>/resourceGroups/rpt-db-yutyang5/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/rpt-db-yutyang5?%24expand=%2A&api-version=2017-03-01-preview
```

The "expand" query params are being incorrectly encoded as `%24expand=` instead of `$expand=`. Running the above API call directly returns a 500 error `{    "error": {        "code": "InternalServerError",        "message": "An unexpected error occured while processing the request. Tracking ID: 'd0e68047-b036-4f32-b1c3-2743af943759'"    }}`

Additionally the specs state that `$expand=` should work correctly, however we also get a 500 error when using `$expand`, removing the `$` fixes the problem and we get a 200 OK with proper payload. 

This looks like a bug in both the go sdk and the spec itself. Please let me know your thoughts - it is urgent we get this addressed. 

[logs.txt](https://github.com/Azure/azure-sdk-for-go/files/4925945/logs.txt)

cc @yutyang @briangottfried

**Comment by jongio** [comment] 2020-07-15 15:58
@ArcturusZhang - Looks like this is not service issue, can you try to repro with @fnocera steps above?

**Comment by fnocera** [comment] 2020-07-15 17:16
As an update on the above @jongio and @ArcturusZhang: We have realized that the API call works correctly if the params are: `$expand="*"` but does not work if it is `$expand=*` ie without the expand being passed as a string. 

Perhaps then it is an issue with the sdk not converting this to a string. Let me know your thoughts. 

We used this to repro https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/get#code-try-0

**Comment by ArcturusZhang** [comment] 2020-07-17 05:59
Hi @fnocera the special symbol `$` is encoded to `%24` when sending the request and it should be decoded when reach the service. (actually go SDK is doing this in every package)

And I also tried to reproduce by using this https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/get#code-try-0. But I could get 200 either use `$expand=*` or `$expand="*"` and if the I use a random sql vm name it gave me 404 in both cases.

**Comment by ArcturusZhang** [comment] 2020-07-17 06:02
And I also wrote following simple code to reproduce this:
```
func getSQLVM(authorizer autorest.Authorizer) {
	client := sqlvirtualmachine.NewSQLVirtualMachinesClient(subsID)
	client.Authorizer = authorizer
	_, err := client.Get(ctx, resGroup, "non-exist", "*")
	if err != nil {
		panic(err)
	}
}
```
And I just normally get a 404
```
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.SqlVirtualMachine/SqlVirtualMachines/non-exist' under resource group 'test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
```
The request:
```
REQUEST: GET https://management.azure.com/subscriptions/85b3dbca-0000-0000-0000-67a141095a76/resourceGroups/test/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/non-exist?%24expand=%2A&api-version=2017-03-01-preview
User-Agent: Go/go1.13 (amd64-windows) go-autorest/v14.0.0 Azure-SDK-For-Go/v44.0.0 sqlvirtualmachine/2017-03-01-preview
```

**Comment by fnocera** [comment] 2020-07-23 14:43
I believe this is resolved

**Comment by nickzhums** [comment] 2020-07-23 14:54
@fnocera thanks, we'll close this issue now

**Closed** 2020-07-23 14:54 UTC
Labels: SQL - VM, Service Attention, customer-reported, question
