### ISSUE TITLE
aztables: support azidentity cred for cosmos db account 

### ISSUE THREAD

**Issue by ZetaoZhuang** [Azure/azure-sdk-for-go#21760] opened 2023-10-13 17:48 UTC
### Feature Request
I went through the aztable go sdk
[readme page](https://github.com/Azure/azure-sdk-forgo/tree/6abf6c1c17c81b659acc8b09ee12dda0f278ddd6/sdk/data/aztables#types-of-credentials)
 and saw it mentioned Storage account can use the same credentials as a Cosmos account and can use the credentials in
[azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) like azidentity.NewDefaultAzureCredential(). I personally tried and verified the  azidentity.NewDefaultAzureCredential() with my cosmos db tables and I saw this error
```
{
  "odata.error": {
    "code": "Unauthorized",
    "message": {
      "lang": "en-us",
      "value": "Authorization header doesn't confirm to the required format. Please verify and try again.\r\nActivityId: eeb9ba60-31d6-48a4-b451-6fa3153a7117, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.17763.0\nRequestID:eeb9ba60-31d6-48a4-b451-6fa3153a7117\n"
    }
  }
}
```
it would be helpful if we have this new feature. Thanks

**Comment by jhendrixMSFT** [comment] 2023-10-16 14:47
@ealsur is this due to the slightly different format of the `Authorization` header for Cosmos or is there more to it than that?

https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/data/azcosmos/cosmos_policy_bearer_token.go#L63

**Comment by ealsur** [comment] 2023-10-16 16:56
@jhendrixMSFT I sadly have no visibility on Tables API accounts and how they work. They might be using the same AAD format as SQL (azcosmos). Maybe one idea is to check the .NET Azure.Data.Tables project, and how they support AAD?

**Comment by jhendrixMSFT** [comment] 2023-10-16 21:16
It's not the same format as `azcosmos` as that doesn't work.  In addition, the C# SDK throws an exception when trying AAD auth with a Cosmos endpoint.  :(

**Comment by jhendrixMSFT** [comment] 2023-10-16 21:28
Turns out this is by design.  Table storage for Cosmos doesn't support AAD, see https://github.com/Azure/azure-sdk-for-net/issues/32058 for the same issue reported against the C# SDK.

**Comment by ZetaoZhuang** [comment] 2023-10-16 21:43
Is there any limitation that restricts the support of table storage for cosmos? would this be supported in future?

**Comment by jhendrixMSFT** [comment] 2023-10-17 15:59
@sandeep-sen do you know who can answer the above question?

**Comment by joshfree** [comment] 2023-10-17 17:26
> @sandeep-sen do you know who can answer the above question?

@kushagraThapar may know the right contact.

**Comment by kushagraThapar** [comment] 2023-10-17 18:11
@rnagpal can you please direct this to the right owner of Table API for Cosmos DB.

**Comment by sandeep-sen** [comment] 2023-10-18 01:20
@jcocchi could you confirm if this feature is available in Table API for Cosmos DB.

**Comment by jcocchi** [comment] 2023-10-18 17:04
AAD authentication isn't supported for Azure Cosmos DB for Table accounts, and it isn't currently planned.

**Comment by RickWinter** [comment] 2024-03-26 22:19
@jcocchi Can this be closed as something that isn't currently supported or planned?

**Comment by jcocchi** [comment] 2024-03-26 23:13
@RickWinter - Yes, please go ahead and close this issue as it's not on the short or long term roadmap. I don't have permissions to close it

**Comment by RickWinter** [comment] 2024-04-09 16:12
Thank for the feedback. The is no plan to add this support to cosmos. Please see this issue for further details.

Turns out this is by design. Table storage for Cosmos doesn't support AAD, see https://github.com/Azure/azure-sdk-for-net/issues/32058 for the same issue reported against the C# SDK.

**Comment by zenmiao7** [comment] 2024-05-07 06:37
@jcocchi What's the status now? We want to use managed identity to access Azure cosmos db table API with Azure.data.table SDK. Is there any timeline to support it?

**Comment by jcocchi** [comment] 2024-05-08 04:23
@zenmiao7 we've re-prioritized this issue and supporting managed identity in the Table API is now on our roadmap, but I still don't have an ETA to share. We'll continue to update this issue as the feature gets scheduled and is closer to release.

**Comment by MouseRider** [comment] 2024-06-21 20:52
@jcocchi any update on ETA?

**Comment by RickWinter** [comment] 2024-06-27 16:20
@jcocchi As this is now planned should this issue be reopened or is there a new issue tracking the work?

**Comment by jcocchi** [comment] 2024-06-27 17:52
Adding @sajeetharan who will be tracking this moving forward

**Comment by jhendrixMSFT** [comment] 2024-07-16 16:18
Reopening to track the work.

**Comment by richardpark-msft** [comment] 2024-10-18 17:24
(fix is in, I'll close this when I actually release the package)

**Comment by richardpark-msft** [comment] 2024-11-05 20:34
The package has been released!

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables@v1.3.0

**Closed by richardpark-msft** 2024-11-05 20:34 UTC
Labels: question, Client, customer-reported, Tables
