### ISSUE TITLE
ContainerRegistry data plane library

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-go#19690] opened 2022-12-12 17:01 UTC
Add the azcontainerregistry SDK to the set of data-plane libraries

**Comment by jhendrixMSFT** [comment] 2022-12-12 17:11
Looks like a dupe of https://github.com/Azure/azure-sdk-for-go/issues/19483?

**Comment by jhendrixMSFT** [comment] 2022-12-13 00:48
Closing as dupe.

**Closed by jhendrixMSFT** 2022-12-13 00:48 UTC
Labels: Container Registry, Client, feature-request

**Comment by JasonEtco** [comment] 2022-12-22 15:39
Thanks for triaging @RickWinter / @jhendrixMSFT 🙏 I'll subscribe to #19483.
