### ISSUE TITLE
RecoveryPointTierType Unmarshalling JSON Error

### ISSUE THREAD

**Issue by rogercoll** [Azure/azure-sdk-for-go#12024] opened 2020-07-30 08:24 UTC
### Bug Report - RecoveryPointTierType Unmarshalling JSON Error

- import path:  `.../services/recoveryservices/mgmt/2020-02-02/backup`
- SDK version `master`
- Go version: `go version go1.13.4 linux/amd64`

If I try to list or get a Recovery Point I get and Unmarshalling Error. One example SDK call could be:
```go
	rpClient := backup.NewRecoveryPointsClient(sess.SubscriptionID)
        ...
        rpList, err := rpClient.List(...)
```
The error produced by the previous code is: 

`2020/07/30 09:52:04 backup.RecoveryPointsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field RecoveryPointResourceList.value of type backup.RecoveryPointTierType'`

Taking a further look I saw that there is an inconsistency between what the Go SDK expects and what the GET call returns, as the http request returns an integer and the SDK expects a string for the RecoveryPointTierType value. Example output:

```
..."recoveryPointTierDetails":[{"type":1,"status":1},{"type":2,"status":1}],...
```

For the field `type` the sdk expects a string => [SDK code](https://github.com/Azure/azure-sdk-for-go/blob/master/services/recoveryservices/mgmt/2020-02-02/backup/models.go#L1274)

Is is an API version problem?

**Comment by ArcturusZhang** [comment] 2020-08-03 02:37
Hi @rogercoll thanks for this issue!

This should be a swagger issue - the swagger definition is not consistent with what the API returns.

I have tagged this issue so that the corresponding service team will have a look at this.

**Comment by pvrk** [comment] 2020-08-03 03:59
"This should be a swagger issue - the swagger definition is not consistent with what the API returns."
@ArcturusZhang : Thanks for helping to narrow down the probable root cause.

Forwarding this to my service team for investigation.

**Comment by pvrk** [comment] 2020-08-03 04:00
@pratimaupadhyay02: Can you please take a look at this issue?

**Comment by rogercoll** [comment] 2020-08-06 08:20
Hello, thank you very much for your responses. Is there any update regarding this issue? My team and I are working on a tool to automated recovery services backup restoration and this issue stop us to move on.

**Comment by rogercoll** [comment] 2020-08-26 16:41
@pvrk @ArcturusZhang is there any update regarding the issue error?

**Comment by pratimaupadhyay02** [comment] 2020-08-28 09:40
Hi @rogercoll Sorry for the delayed response. The issue seems specific to Go-SDK so we have to loop in the go-sdk team for some expertise.

**Comment by ArcturusZhang** [comment] 2020-08-31 05:17
Hi @pratimaupadhyay02 based on the swagger definition [here](https://github.com/Azure/azure-rest-api-specs/blob/e84a61630139738316ee8531960b5966e8f1baeb/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2019-06-15/bms.json#L4610), this property is meant to be not only a string, but an enum value among `Invalid`, `InstantRP` and `HardenedRP`. Therefore this issue is apparently caused by either something wrong in the swagger or some behaviour issue in the service itself. Please double check, thanks

**Comment by pvrk** [comment] 2020-09-24 10:51
We are working on the fix and will update the ETA soon. This might be fixed from a new API version to make sure older APIs are not broken if they took a dependency on existing behavior.

**Comment by cohenjo** [comment] 2021-01-14 09:13
Hi, Is there an update on this? or even some workaround to get the recovery points?
Thanks

**Comment by mepand** [comment] 2021-03-21 16:47
@cohenjo We will get back on this by end of this month

**Comment by mepand** [comment] 2021-04-29 09:38
@cohenjo the latest version of the API has the fix for this. Can you please try leveraging the API directly? Ideally API version post 2020-10-01 should work.

**Comment by ArcturusZhang** [comment] 2021-05-06 03:30
> @cohenjo the latest version of the API has the fix for this. Can you please try hitting the API directly? Ideally any API version post 2020-10-01 should work.

Also could you please open a SDK release request to either refresh the existing SDK package or introduce a new package corresponding to the new api-version so that we could unblock the customers of azure-sdk-for-go?
You can submit a release request [here](https://aka.ms/openapihub)

**Comment by adityabalaji-msft** [comment] 2021-06-24 09:54
Removing service attention label since the bug is fixed from service side

**Comment by lirenhe** [comment] 2021-09-16 06:04
@rogercoll, the latest version of GO SDK contains the fix. Close this issue and please let us know if you have this issue again.

**Closed by lirenhe** 2021-09-16 06:04 UTC
Labels: bug, Recovery Services Backup, Mgmt, customer-reported, needs-team-attention, Track1
