### ISSUE TITLE
Uploading large files to azure blob with UploadBuffer fails

### ISSUE THREAD

**Issue by 1k-off** [Azure/azure-sdk-for-go#19662] opened 2022-12-04 20:41 UTC
### Bug Report

- import path of package in question: `azure-sdk-for-go/sdk/storage/azblob`
- SDK version: `v0.5.1`
- output of `go version`: `go version go1.19.2 windows/amd64`

Hi.
I'm trying to upload files to azure blob using UploadBuffer. Small files uploads as expected, but with the large files I see an error.
For example, 2Mb pdf uploads well, but 950Mb binary causes an error.
Error: `net/http: HTTP/1.x transport connection broken: http: ContentLength=494256 with Body length 481814`
Screenshots: [1](https://i.imgur.com/pRLnv7Z.png), [2](https://i.imgur.com/hWqh7Mt.png)
Here's some code:

```go
// Storage interface that is implemented by storage providers
type Storage struct {
	client         *azblob.Client
	container      string
	requestTimeout time.Duration
	provider       string
}

// New creates a new storage
func New(config ...Config) *Storage {
	// Set default config
	cfg := configure(config...)
	// Set the azure credentials
	cred, err := azblob.NewSharedKeyCredential(cfg.Credentials.Account, cfg.Credentials.Key)
	handleError(err)
	client, err := azblob.NewClientWithSharedKeyCredential(cfg.Endpoint, cred, nil)
	handleError(err)
	_, err = client.CreateContainer(context.TODO(), cfg.Container, nil)
	if err != nil {
		if !bloberror.HasCode(err, bloberror.ContainerAlreadyExists) {
			panic(fmt.Sprintf("invalid config:, %v", err))
		}
	}
	storage := &Storage{
		client:         client,
		container:      cfg.Container,
		requestTimeout: cfg.RequestTimeout,
		provider:       storage.ProviderAzureBlob,
	}

	// Reset all entries if set to true
	if cfg.Reset {
		if err := storage.Reset(); err != nil {
			panic(err)
		}
	}

	return storage
}

func (s *Storage) Set(key string, val []byte, exp time.Duration) error {
	if len(key) <= 0 {
		return nil
	}
	ctx, cancel := s.requestContext()
	defer cancel()
	_, err := s.client.UploadBuffer(ctx, s.container, key, val, nil)
	return err
}

func (s *Storage) requestContext() (context.Context, context.CancelFunc) {
	if s.requestTimeout > 0 {
		return context.WithTimeout(context.Background(), s.requestTimeout)
	}
	return context.Background(), func() {}
}
```

**Comment by jhendrixMSFT** [comment] 2022-12-05 14:43
This is a duplicate of https://github.com/Azure/azure-sdk-for-go/issues/19651.  The fix will be released in `v0.6.0`.  Thanks for the report.

**Closed by jhendrixMSFT** 2022-12-05 14:43 UTC
Labels: question, customer-reported, needs-triage
