### ISSUE TITLE
SAS token based blob client fails to download blob due to trailing slash.

### ISSUE THREAD

**Issue by floriankramer** [Azure/azure-sdk-for-go#19318] opened 2022-10-10 09:09 UTC
### Bug Report

- import path: `"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob"`
- version: `require github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.5.0`
- output of `go version`: `go version go1.19.1 linux/amd64`

When creating a container and then a blob client as follows:
```
containerUrl := BaseUrl + "?" + sasToken
client, err := container.NewClientWithNoCredential(containerUrl, nil)
client := channelManager.azblobClient.NewBlockBlobClient(filename)
```
the clients url has a trailing slash after the filename and before the `sasToken`. As a result download requests return 404. This is caused by `JoinPaths` in `azcore@v1.1.2/runtime/request.go`, which adds a trailing slash to the path if the initial root path had query parameters. `JoinPaths` is used by the `NewBlockBlobClient` function of a `ContainerClient`.

Creating a URL with a sas token like this used to work in azblob `v0.4.1`. Is this actually the correct way to use sas tokens? I wasn't able to find any documentation on how authentication with tokens is supposed to work when using azblob.

**Comment by jhendrixMSFT** [comment] 2022-10-10 13:56
Dupe of https://github.com/Azure/azure-sdk-for-go/issues/19245. The fix is in `azcore@v1.1.4`.

**Closed by jhendrixMSFT** 2022-10-10 13:56 UTC
Labels: question, customer-reported, needs-triage
