### ISSUE TITLE
sporadic nil pointer dereference

### ISSUE THREAD

**Issue by LukeBayler** [Azure/azure-sdk-for-go#4845] opened 2019-05-21 18:05 UTC
### Bug Report

- SDK version: 	"github.com/Azure/azure-sdk-for-go/services/cognitiveservices/v2.0/computervision"

- output of `go version`: go version go1.12.5 windows/amd64

- What happened? Sporadic nil pointer dereference. Here is the output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x8d2a06]

goroutine 1 [running]:
main.main()
        C:/Users/v-lubayl/Documents/GitHub/cognitive-services-samples-pr/go/Vision/ComputerVision/RecognizeText.go:136 +0xae6
exit status 2

[RecognizeText.zip](https://github.com/Azure/azure-sdk-for-go/files/3203856/RecognizeText.zip)

**Comment by jhendrixMSFT** [comment] 2019-05-21 22:25
The problem is the `NotStarted` enum, the value sent over the wire is the string `NotStarted` however in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/ComputerVision/stable/v2.0/Ocr.json#L310) the value is defined as `Not Started`.  As a result your `for` loop exits early causing the nil pointer dereference.  I'll follow up with the RP about this.

**Comment by toothache** [comment] 2019-05-22 02:07
Thanks for reporting this issue! We've confirmed that it's a swagger issue and is now tracked by https://github.com/Azure/azure-rest-api-specs/issues/6057.

**Comment by jhendrixMSFT** [comment] 2019-07-23 20:55
This has been fixed in v31.0.0 of the SDK.

**Closed by jhendrixMSFT** 2019-07-23 20:55 UTC
Labels: customer-reported, fix available, specs
