### ISSUE TITLE
Azure CosmosDB SDK for Go support cross-partition queries?

### ISSUE THREAD

**Issue by amirvalipour-se** [Azure/azure-sdk-for-go#22090] opened 2023-12-04 09:04 UTC
### Feature Request

I am using the Azure CosmosDB SDK for Go for my application, and I need to perform a cross-partition query in Cosmos DB. However, I'm not sure if the SDK supports this or how to correctly implement it.
Do we already have this feature?????

**Comment by ealsur** [comment] 2023-12-04 15:05
Duplicate of https://github.com/Azure/azure-sdk-for-go/issues/18578

**Comment by ealsur** [comment] 2023-12-04 15:06
@KiraTheGenius Please use the existing Issue to track this feature's progress if you want. No, the SDK currently does not support cross-partition queries.

**Closed as completed by ealsur** 2023-12-04 15:06 UTC
Labels: question, Cosmos, Client, customer-reported, needs-team-triage
