### ISSUE TITLE
InterfacesClient.ListVirtualMachineScaleSetNetworkInterfaces returns empty list

### ISSUE THREAD

**Issue by kowsalyapalaniappan** [Azure/azure-sdk-for-go#6396] opened 2019-11-20 20:57 UTC
I have two VMs in the VM Scale Set. I am trying to list the network interfaces of the VMs using InterfacesClient.ListVirtualMachineScaleSetNetworkInterfaces, but it always returns empty list.
I don't get any auth error, the call is successful. What will cause it to behave in this way ?

**Comment by ArcturusZhang** [comment] 2019-12-03 07:38
Hi @kowsalyapalaniappan thanks for the issue.
I have a brief test on my machine, but it seems that I can list the network interfaces of a vmss correctly.
First I created an vmss using Azure CLI:
```
az vmss create -n MyVmss -g MyResourceGroup --instance-count 5 --image Win2016Datacenter --data-disk-sizes-gb 2
```
Then I wrote the following go code to list the network interfaces within it: 
```
var (
	ctx = context.Background()
)

func main() {
	if authorizer, err := auth.NewAuthorizerFromCLI(); err != nil {
		panic(err)
	} else {
		fmt.Println("Listing...")
		listVMSSInterfaces(authorizer)
	}
}

func listVMSSInterfaces(authorizer autorest.Authorizer) {
	client := network.NewInterfacesClient(subsID)
	client.Authorizer = authorizer
	if iterator, err := client.ListVirtualMachineScaleSetNetworkInterfacesComplete(ctx, resGroup, "MyVmss"); err != nil {
		panic(err)
	} else {
		for iterator.NotDone() {
			in := iterator.Value()
			if b, err := json.MarshalIndent(in, "", "  "); err != nil {
				panic(err)
			} else {
				fmt.Println(string(b))
			}
			if err := iterator.NextWithContext(ctx); err != nil {
				panic(err)
			}
		}
	}
}
```
The output is the same as I run cli command `az vmss nic list -g MyResourceGroup --vmss-name MyVmss`

I am closing this issue since this cannot be reproduced. Feel free to reopen and leave more information if the issue persists. Thanks!

**Closed by ArcturusZhang** 2019-12-03 07:38 UTC
Labels: Compute - VMSS, Mgmt

**Comment by kowsalyapalaniappan** [comment] 2019-12-26 17:12
I am able to list the interfaces of VMSS instances now. When I created this issue, my AD account did not have right role to access VMSS . But I did not get an 403 error , instead I was getting empty list. Thanks for looking into this. But the right way is to return 403 instead of empty list.

**Comment by ArcturusZhang** [comment] 2019-12-27 03:06
> I am able to list the interfaces of VMSS instances now. When I created this issue, my AD account did not have right role to access VMSS . But I did not get an 403 error , instead I was getting empty list. Thanks for looking into this. But the right way is to return 403 instead of empty list.

Well, that may be the service side bug I think. Sorry for the inconvenience. I will try to present this issue to the service team if they are interested.
