### ISSUE TITLE
arm: Add User-Agent header to queries

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-sdk-for-go#213] opened 2015-09-10 19:21 UTC

**Comment by brendandixon** [comment] 2015-09-10 20:27
@ahmetalpbalkan See my comments on #212

**Comment by brendandixon** [comment] 2015-10-02 17:21
@ahmetalpbalkan The issue is addressed in the latest. Please take a look.

**Comment by ahmetalpbalkan** [comment] 2015-10-02 17:23
We can close this now. Pardon my ignorance, what do we return as UA string now? :-)

**Comment by brendandixon** [comment] 2015-10-02 17:37
Changes merged from PR #221

**Comment by brendandixon** [comment] 2015-10-02 17:40
Each package sets the UA string to:

Azure-SDK-for-Go/%s;Package/%s;API/%s

With the semantic version filling the first %s, the package name the second, and the API version the third. For example:

"Azure-SDK-for-Go/0.1.0-beta;Package/authorization;API/2015-01-01

**Comment by ahmetalpbalkan** [comment] 2015-10-02 18:00
Hmm there's no mention of arm here. in this case wouldn't arm/storage potentially collide with storage/?

**Comment by brendandixon** [comment] 2015-10-02 18:05
@ahmetalpbalkan Ah, good point! I'll get a new PR ready. It'll be the same that lights up golint / govet Travis for the ARM packages.

**Comment by brendandixon** [comment] 2015-11-11 00:07
Change added a while ago. Closing.

**Closed by brendandixon** 2015-11-11 00:07 UTC
Labels: area/azureresourcemanager, enhancement
