### ISSUE TITLE
Have single Azure Resource type definition that is shared between packages.

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-sdk-for-go#2315] opened 2018-07-26 04:26 UTC
### Feature Request

We can at least try this for who is using the arm common types definitions in the specs repo to 
make sure we don't hit any compatibility issues.

**Comment by jhendrixMSFT** [comment] 2018-07-30 16:52
Looks like a dupe of https://github.com/Azure/azure-sdk-for-go/issues/1437

**Closed by jhendrixMSFT** 2018-07-30 16:52 UTC
Labels: P1, backlog
