### ISSUE TITLE
[azservicebus] unexpected error handling for "connection reset by peer"

### ISSUE THREAD

**Issue by ryepup** [Azure/azure-sdk-for-go#17194] opened 2022-02-28 23:11 UTC
### Bug Report

- import path of package in question:  `github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus`
- SDK version:  `v0.3.5`
- go version: 1.17.6

#### What happened?

Something as yet undetermined cuts the long-lived TCP connection, and leaves our `azservicebus.Client` in an unhealthy state. The error we've been seeing looks like:

> read tcp 192.168.0.7:58264->13.66.228.204:5671: read: connection reset by peer

Different parts of `azservicebus` are affected in different ways. Based on our application logs we think we're seeing these behaviors:

1. `Sender.SendMessage` retries per `ClientOptions.RetryOptions` and then returns the "connection reset by peer" error
2. `Client.AcceptNextSessionForSubscription` retries per `ClientOptions.RetryOptions` and then returns the "connection reset by peer" error
3. `Client.NewReceiverForSubscription` retries per `ClientOptions.RetryOptions` and then returns the "connection reset by peer" error
4. `SessionReceiver.ReceiveMessages` had two behaviors:
   1. some receivers returned an error:

      > *Error{Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:9cdaa7c06baf4ed6aa7d8fabe83f06a0_G29, SystemTracker:gateway7, Timestamp:2022-02-23T01:44:42, Info: map[]}

   2. some receivers did not return an error, but did not seem to be processing messages

5. `Receiver.ReceiveMessages` had two behaviors:
   1. returned the "connection reset by peer"
   2. did not return any errors, but we believe it was disconnected. We had a few servicebus subscriptions with `AutoDeleteOnIdle` enabled, and those subscriptions were not present in the azure portal. We think that means
      our `Receiver`s were completely disconnected and the auto-delete kicked in. When we restarted our service (via SIGTERM), it canceled the`context.Context` passed to `Receiver.ReceiveMessages`. _After_ the context is canceled, `Receiver.ReceiveMessages` returns the "connection reset by peer" error. It must have been stored in a struct somewhere along the way.

Restarting our applications restored our connections, but the apps existed in this broken state for hours without recovering.

#### What did you expect or want to happen?

I'd like `azservicebus`/`go-amqp` to restore the broken TCP connection. We have some retries configured around `azservicebus`, and from our logs we can see the same local ports being tried for hours and hours, (e.g. 192.168.0.7:58264). It
would be great if `azservicebus`/`go-amqp` would try to make a new TCP connection on a different port in the "connection reset by peer" case.

I'd like `Receiver.ReceiveMessages` to eagerly return the "connection reset by peer" errors.

#### How can we reproduce it?

I have not been able to find a reliable way to reproduce this.

I'm currently enabling [azsb logs](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus@v0.3.5#readme-logging) and hope to find more clues catching it in the wild.

#### Anything we should know about your environment.

We're running `azservicebus` in AKS. Our best guess there's something going wrong in the networking stack underneath the docker container, but the disconnect happens rarely and after days of uptime.

We've seen this in several azure regions:

- westcentralus
- westus2
- centraluseuap
- eastus2euap

**Comment by ryepup** [comment] 2022-03-02 22:37
I got some more logs catching this error.

My process has two goroutines, both using the same `Client`:

- loop sending a "heartbeat" message every 9m, exiting on unexpected error
- loop calling ReceiveMessages with a 30s context deadline, exiting on unexpected error

The heartbeat azsb logs looked like this:

```console
15:56:38 azsb.Retry (SendMessage) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:38 azsb.Retry (SendMessage) Attempt 1 sleeping for 5.054193995s
15:56:43 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:43 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:43 azsb.Retry (SendMessage) Attempt 1 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:43 azsb.Retry (SendMessage) Attempt 2 sleeping for 10.236996065s
15:56:53 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:53 azsb.Retry (SendMessage) Attempt 2 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:53 azsb.Retry (SendMessage) Attempt 3 sleeping for 31.140310001s
15:57:24 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:57:24 azsb.Retry (SendMessage) Attempt 3 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
```

The receiver logs looked like this, with line breaks where I think my context deadline expired and my loop started a new `ReceiveMessages`:

```console
15:53:12 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:12 azsb.Retry (receiveMessages) Attempt 1 sleeping for 4.065122248s
15:53:16 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:16 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:16 azsb.Retry (receiveMessages) Attempt 1 sleeping for 4.373481497s
15:53:16 azsb.Retry (receiveMessages) Resetting attempts
15:53:20 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:20 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:20 azsb.Retry (receiveMessages) Attempt 1 sleeping for 3.538614267s
15:53:20 azsb.Retry (receiveMessages) Resetting attempts
15:53:24 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:24 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:24 azsb.Retry (receiveMessages) Attempt 1 sleeping for 4.974986827s
15:53:24 azsb.Retry (receiveMessages) Resetting attempts
15:53:29 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:29 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:29 azsb.Retry (receiveMessages) Attempt 1 sleeping for 3.259765151s
15:53:29 azsb.Retry (receiveMessages) Resetting attempts
15:53:32 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:32 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:32 azsb.Retry (receiveMessages) Attempt 1 sleeping for 5.084735768s
15:53:32 azsb.Retry (receiveMessages) Resetting attempts
15:53:37 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:37 azsb.Retry (receiveMessages) Attempt 1 returned non-retryable error: context deadline exceeded

15:53:37 azsb.Conn failed to recreate link: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:37 azsb.Conn Recovering link for error link detached, reason: *Error(nil)
15:53:37 azsb.Receiver Failed to recover links after a failed drain: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer

15:53:37 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:37 azsb.Retry (receiveMessages) Attempt 1 sleeping for 4.243666363s
15:53:41 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:41 azsb.Retry (receiveMessages) Attempt 1 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:41 azsb.Retry (receiveMessages) Attempt 2 sleeping for 14.345590237s
15:53:56 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:56 azsb.Retry (receiveMessages) Attempt 2 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:53:56 azsb.Retry (receiveMessages) Attempt 3 sleeping for 33.926862112s
15:54:30 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:30 azsb.Retry (receiveMessages) Attempt 3 returned non-retryable error: context deadline exceeded

15:54:30 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:30 azsb.Retry (receiveMessages) Attempt 1 sleeping for 4.576737066s
15:54:34 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:34 azsb.Retry (receiveMessages) Attempt 1 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:34 azsb.Retry (receiveMessages) Attempt 2 sleeping for 13.906107532s
15:54:48 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:48 azsb.Retry (receiveMessages) Attempt 2 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:54:48 azsb.Retry (receiveMessages) Attempt 3 sleeping for 31.194865363s
15:55:19 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:19 azsb.Retry (receiveMessages) Attempt 3 returned non-retryable error: context deadline exceeded

15:55:19 azsb.Retry (receiveMessages) Attempt 0 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:19 azsb.Retry (receiveMessages) Attempt 1 sleeping for 3.228665554s
15:55:23 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:23 azsb.Retry (receiveMessages) Attempt 1 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:23 azsb.Retry (receiveMessages) Attempt 2 sleeping for 10.522749297s
15:55:33 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:33 azsb.Retry (receiveMessages) Attempt 2 returned retryable error: read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:55:33 azsb.Retry (receiveMessages) Attempt 3 sleeping for 26.88920899s
15:56:00 azsb.Conn Recovering link for error read tcp 192.168.0.42:36132->13.66.228.204:5671: read: connection reset by peer
15:56:00 azsb.Retry (receiveMessages) Attempt 3 returned non-retryable error: context deadline exceeded
```

Some notes:

- the first `receiveMessages` seemed to get stuck at attempt 0. This might explain the behavior I saw prior to logging where `ReceiveMessages` didn't return any error, but didn't seem connected
- there was one odd `*Error(nil)` issue, and I'm not sure if that was part of the first or second `ReceiveMessages` block
- at one point, `SendMessage` and `ReceiveMessages` were both retrying simultaneously. Is that safe, or should I be using more `Client`s?

**Comment by vgtswork** [comment] 2022-03-03 14:08
Same exact behavior here, but sometimes the TCP error is not "read: connection reset by peer" but "i/o timeout", example:

`"read tcp 10.116.24.21:52748->13.69.106.69:5671: i/o timeout"`

I could easly replicate this on my local, just use the old'good method of wifi/LAN disconnection while the service is running, and after a bit, if the services is listening or try to send a message, you will see all the azlogs with a lot of retries and recovery attempts.

Close and re-create the Sender or Receiver doesn't help at all, only solution is to rebuild again the Client. So, as suggested by @ryepup, the only quick solution is restart the entire application. 

Right now, as quick and dirty solution, i just implemented a simple method that performs a message Peek, and use this as k8s pod probeness - in case of Peek failure (most probably caused by this problem) the pod will get restarted.

**Comment by richardpark-msft** [comment] 2022-03-09 01:53
Hi @ryepup (and @vgtswork). 

We've just released [v0.3.6](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fmessaging%2Fazservicebus%2Fv0.3.6), which fixes this (and other) recovery errors.

This reclassifies several timeouts to be connection restart, rather than link restart. This will rebuild the internals of the client, which will properly reset the connection after it receives an error.

Thanks both of you for reporting this. Let me know if you see this issue after v0.3.6.

@ryepup, you had some other questions:

> there was one odd *Error(nil) issue, and I'm not sure if that was part of the first or second ReceiveMessages block

These are technically okay. When a link is 'detached' it's possible for the service to also send a specific error related to the detach. If there isn't an inner error then you'll see a nil there but that doesn't necessarily mean anything is incorrect. The outer envelope for that error is what we trigger off of.

> at one point, SendMessage and ReceiveMessages were both retrying simultaneously. Is that safe, or should I be using more Clients?

It's perfectly fine for them to be created from the same client. Each `Client` is basically an AMQP connection, and connections are meant to be used with several links. The Senders and Receivers do properly coordinate when recovery is needed for a shared resource, so it shouldn't be an issue.

> (from your first post): did not return any errors, but we believe it was disconnected. We had a few servicebus subscriptions with AutoDeleteOnIdle enabled, and those subscriptions were not present in the azure portal. We think that means
our Receivers were completely disconnected and the auto-delete kicked in.

There's a high likelihood this is simply related to the fact that we were not properly reconnecting (ie, the attempts to connect weren't actually attempts, just cached errors). With that said, I'll be adding in a test regardless as this is a use case that should work.

All of this aside - @ryepup , I've really appreciated your bug reports. The amount of detail you provide is super helpful - please let us know if you need anything else or have any other questions!

**Comment by vgtswork** [comment] 2022-03-09 16:00
Hi @richardpark-msft, thanks a lot for the release! I will try as soon as i have a chance on my local and also in our develop envs.

+1 thanks @ryepup for the detailed issue

**Comment by richardpark-msft** [comment] 2022-03-09 18:20
Closing as I believe we've resolved all the issues. Please re-open if you see this again.

**Closed by richardpark-msft** 2022-03-09 18:20 UTC
Labels: question, Service Bus, Client, customer-reported

**Comment by ryepup** [comment] 2022-03-10 15:56
Thanks for the new version! Our initial tests look great, and based on @vgtswork 's repro advice I was able to confirm v0.3.6 fixes it.

This sample program sends a message every 10s, during which we manually disconnect our network (pull the plug, disable wifi, whatever), and observe the behavior.

```go
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus"
)

const (
	namespace    = "TODO"
	queueOrTopic = "TODO"
)

func log(format string, a ...interface{}) {
	now := time.Now().Format("04:05.00000")
	fmt.Printf("[%s]: ", now)
	fmt.Printf(format, a...)
	fmt.Println()
}

func main() {
	azlog.SetListener(func(e azlog.Event, s string) {
		log("%v %s", e, s)
	})
	azlog.SetEvents(
		// connection/reconnect related events)
		"azsb.Conn",
		// receiver specific events
		"azsb.Receiver",
		// management link related events
		"azsb.Mgmt",
		// retry related events
		"azsb.Retry",
	)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM, syscall.SIGINT)
	defer stop()
	credential, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		panic(err)
	}
	client, err := azservicebus.NewClient(namespace, credential, &azservicebus.ClientOptions{})
	if err != nil {
		panic(err)
	}
	sender, err := client.NewSender(queueOrTopic, &azservicebus.NewSenderOptions{})
	if err != nil {
		panic(err)
	}
	go func() {
		for {
			send(ctx, sender)
			select {
			case <-ctx.Done():
				return
			case <-time.After(10 * time.Second):
			}
		}
	}()

	log("infinite sender started, mess with the network")
	<-ctx.Done()
}

func send(ctx context.Context, sender *azservicebus.Sender) {
	msg := &azservicebus.Message{
		Body: []byte("hello world"),
	}
	start := time.Now()
	err := sender.SendMessage(ctx, msg)
	duration := time.Since(start)
	log("send took %v, err: %v", duration, err)
}
```

My procedure was:

1. `go run .`
2.  watch the program send a couple of messages
3. disconnect my network
4. wait until I see a "Attempt 2" log
5. reconnect my network

With v0.3.5, we can see the bad behavior:

```shell
$ go run .
[36:20.12886]: infinite sender started, mess with the network
[36:23.58595]: send took 3.457084872s, err: <nil>
[36:33.66094]: send took 72.019858ms, err: <nil>
# manually disconnected my network
[37:33.66324]: azsb.Retry (SendMessage) Attempt 0 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[37:33.66327]: azsb.Retry (SendMessage) Attempt 1 sleeping for 4.409320575s
[37:38.07712]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[37:38.07716]: azsb.Conn Recovered, no action needed
[37:38.07723]: azsb.Retry (SendMessage) Attempt 1 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[37:38.07726]: azsb.Retry (SendMessage) Attempt 2 sleeping for 15.243054528s
# manually reconnected my network
[37:53.32305]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[37:53.32309]: azsb.Conn Recovered, no action needed
[37:53.32312]: azsb.Retry (SendMessage) Attempt 2 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[37:53.32312]: azsb.Retry (SendMessage) Attempt 3 sleeping for 31.703840745s
[38:25.03094]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:25.03108]: azsb.Conn Recovered, no action needed
[38:25.03143]: azsb.Retry (SendMessage) Attempt 3 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:25.03145]: send took 1m41.361933536s, err: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
# the default 3 retries have been spent, so my function returns an err
[38:35.03495]: azsb.Retry (SendMessage) Attempt 0 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:35.03507]: azsb.Retry (SendMessage) Attempt 1 sleeping for 4.075428374s
[38:39.11164]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:39.11167]: azsb.Conn Recovered, no action needed
[38:39.11171]: azsb.Retry (SendMessage) Attempt 1 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:39.11173]: azsb.Retry (SendMessage) Attempt 2 sleeping for 12.147824982s
[38:51.25972]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:51.25978]: azsb.Conn Recovered, no action needed
[38:51.25984]: azsb.Retry (SendMessage) Attempt 2 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[38:51.25986]: azsb.Retry (SendMessage) Attempt 3 sleeping for 32.01552302s
[39:23.27638]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[39:23.27644]: azsb.Conn Recovered, no action needed
[39:23.27650]: azsb.Retry (SendMessage) Attempt 3 returned retryable error: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
[39:23.27651]: send took 48.24228999s, err: read tcp 192.168.75.212:55731->13.78.149.209:5671: i/o timeout
# now we're stuck, unable to recover
^C
```

With v0.3.6, it's comes back no problem:

```shell
$ go run .
[31:00.73547]: infinite sender started, mess with the network
[31:03.56336]: send took 2.827912005s, err: <nil>
[31:13.64504]: send took 77.042631ms, err: <nil>
[31:23.72209]: send took 72.325814ms, err: <nil>
# manually disconnected my network
[31:59.41289]: azsb.Retry (SendMessage) Attempt 0 returned retryable error: read tcp 192.168.75.212:55570->13.78.149.209:5671: read: can't assign requested address
[31:59.41294]: azsb.Retry (SendMessage) Attempt 1 sleeping for 4.409320575s
[32:03.82646]: azsb.Conn Recovering link for error read tcp 192.168.75.212:55570->13.78.149.209:5671: read: can't assign requested address
[32:03.82652]: azsb.Conn Recovering connection (and links)
[32:03.82654]: azsb.Conn Creating a new client (rev:1)
[32:03.82860]: azsb.Conn Recover connection failure: dial tcp: lookup nalb-int-tests.servicebus.windows.net: no such host
[32:03.82865]: azsb.Conn failed to recreate connection: dial tcp: lookup nalb-int-tests.servicebus.windows.net: no such host
[32:03.82867]: azsb.Retry (SendMessage) Attempt 1 returned retryable error: dial tcp: lookup nalb-int-tests.servicebus.windows.net: no such host
[32:03.82868]: azsb.Retry (SendMessage) Attempt 2 sleeping for 15.243054528s
# manually reconnected my network
[32:19.08198]: azsb.Conn Recovering link for error dial tcp: lookup nalb-int-tests.servicebus.windows.net: no such host
[32:19.08212]: azsb.Conn Recovering connection (and links)
[32:19.08213]: azsb.Conn Creating a new client (rev:1)
[32:20.93990]: azsb.Conn New client created, (rev: 2)
[32:20.93994]: azsb.Conn recreating link: c: true, current:{1 1}, old:{1 1}
[32:24.61772]: azsb.Conn Recovered connection and links
[32:24.94366]: send took 51.202054992s, err: <nil>
# my function never returned an error!
```

Great work @richardpark-msft!
