### ISSUE TITLE
scheduler: JobAction.RetryPolicy.RetryInterval silently fails if input is not in the correct format

### ISSUE THREAD

**Issue by katbyte** [Azure/azure-sdk-for-go#1825] opened 2018-05-10 00:10 UTC
the scheduler job property `JobAction.RetryPolicy.RetryInterval` will silently fail if not in the correct format:

https://github.com/Azure/azure-sdk-for-go/blob/56332fec5b308fbb6615fa1af6117394cdba186d/services/scheduler/mgmt/2016-03-01/scheduler/models.go#L1319

It also seems to loosely accept and return the ISO 8601 format? "00:05:00" is accepted and then returned.

**Comment by jhendrixMSFT** [comment] 2018-06-06 22:58
@pinwang81 can you help route?

**Comment by lirenhe** [comment] 2021-09-28 06:17
This item has been there for 3 years with no action from service team. Close this one and @katbyte, please let us know if the issue is still there and you need a fix for it.

**Closed by lirenhe** 2021-09-28 06:17 UTC
Labels: bug, Scheduler, Service Attention, Mgmt
