### ISSUE TITLE
[storage] Container.Delete allows for multiple deletes of the same container without returning an error

### ISSUE THREAD

**Issue by hxeml** [Azure/azure-sdk-for-go#883] opened 2017-11-28 00:23 UTC
I am using container.go in the azure-sdk-for-go/storage package version 10.0.2.

If I delete a container and then call delete on it again immediately, the second call does not return an error. 

I tried working around the problem using DeleteIfExists and checking the returned boolean parameter, but it reported "True" when I tried to delete the Container while it was already being deleted.

I understand that containers are only marked for deletion when the Delete command is issued and are not actually deleted until the next garbage collection. If I call Create on the container immediately after deleting it, however, I get back an error with the errorcode "ContainerBeingDeleted".  Isn't there a way to return this "ContainerBeingDeleted" error when I try to delete it as well?

Thanks.

**Comment by jhendrixMSFT** [comment] 2017-12-07 17:55
Hello!  First, I would like to point out that we are in process of deprecating the storage package, replacing it with new packages.  For blob storage we have a new package, azblob, that you can find here https://github.com/Azure/azure-storage-blob-go
The docs aren't clear on what the behavior is supposed to be here, however I can confirm that I observe this same behavior in the new azblob package.  So I suspect this is an issue with how the REST API works.  @jeffreyrichter can you comment on the behavior here?

**Comment by JeffreyRichter** [comment] 2017-12-08 04:34
Yes, this is the current behavior of the service itself. I would actually like to change the semantics of the service so the DeleteContainer API would be called something like EnsureContainerDeleted and have it return success if the container is there (and is now being deleted) and also have it return success if the container is marked for deletion or if it is already gone. This would turn the service API into an idempotent API semantically. Similarly, CreateContainer would turn into EnsureContainerExists to make this API idempotent too. Unfortunately, these changes are low priority when compared to many other things we are working on so I can't even begin to estimate a timeframe for them showing up.

**Comment by jhendrixMSFT** [comment] 2018-01-03 20:06
Given that this behavior is by design I'm closing this issue.

**Closed by jhendrixMSFT** 2018-01-03 20:06 UTC
Labels: service, storage
