### ISSUE TITLE
ByInspecting() is called twice 

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-sdk-for-go#9412] opened 2020-05-17 06:26 UTC
### Bug Report
I have implemented a `LogResponse()` ResponseInspector for `autorest.Client` and set it in the RP resource clients.
Example:
```
client := compute.NewImagesClient(subscriptionID)
client.ResponseInspector = LogResponse()
```
However, I have noticed that the same response logs are emitted twice. 
I believe `ByInspecting()` called once in in the `autorest.Client.Do()`. 
The other call is in the `Responder` method in the RP resource clients, if they are invoked. 
The one client I inspected:
```
func (client GroupsClient) CreateOrUpdateResponder(resp *http.Response) (result Group, err error) {
	err = autorest.Respond(
		resp,
		client.ByInspecting(),
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusCreated),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}
```
If `client.ByInspecting()` is always invoked in the `client.Do()`, maybe just keep it from the generated `Responder` code?

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
not specific client, but the one in example: 
`.../services/resources/mgmt/2019-05-01/resources/groups.go`
- SDK version e.g. `master`, `latest`, `18.1.0`
`41.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
b7d185716507a401293b9f6c303f6e9798c4cb1b
- output of `go version`
`go version go1.14.2 linux/amd64`

- What happened?
I have implemented a `LogResponse()` ResponseInspector for `autorest.Client` and set it in the RP resource clients but same response logs are emitted twice.. 
- What did you expect or want to happen?
We expect only emit the same log once.
- How can we reproduce it?
Set the ResponseInspector to log response and invoke any azure clients should do.
- Anything we should know about your environment.

**Comment by ArcturusZhang** [comment] 2020-05-18 02:41
Hi @feiyushi thanks for this issue!

This should be a duplicate of #9221 therefore i will close this issue, hope you do not mind

**Closed** 2020-05-18 02:41 UTC
Labels: customer-reported, needs-triage, question
