### ISSUE TITLE
API returns different result than what's show in the SDK.

### ISSUE THREAD

**Issue by SebRosander** [Azure/azure-sdk-for-go#6603] opened 2020-01-05 19:56 UTC
### Bug Report

- import path of package in question: 
"github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2015-04-08/documentdb"

- SDK version:
v36.3.0

- output of `go version`:
go version go1.13.5 darwin/amd64

- What happened?
The API returns "none" instead of "None"" as show in the SDK.
https://github.com/Azure/azure-sdk-for-go/blob/781d9fb592a1818cb7fb8e0855ea9c00b095a9e9/services/cosmos-db/mgmt/2015-04-08/documentdb/models.go#L145

- What did you expect or want to happen?
Expected a return of "None" not "none". 

- How can we reproduce it?

https://github.com/SebRosander/terraform-provider-azurerm/blob/cosmosdb_gremlin_graph/azurerm/internal/services/cosmos/resource_arm_cosmosdb_gremlin_graph.go

Just run the test for the code. Found here:
https://github.com/SebRosander/terraform-provider-azurerm/blob/cosmosdb_gremlin_graph/azurerm/internal/services/cosmos/tests/resource_arm_cosmosdb_gremlin_graph_test.go

**Comment by ArcturusZhang** [comment] 2020-01-06 05:04
Hi @SebRosander thanks for this issue. 
I have tagged this issue so that the corresponding service team member will see.

**Comment by shurd** [comment] 2020-01-07 23:10
Hi @SebRosander thank you for opening this issue. We are still investigating the capitalization discrepancy. It looks like our service returns the indexing mode with the first letter capitalized and at some point it gets converted to lower-case. I will update once we decide how to proceed.

**Comment by rnagpal** [comment] 2020-07-17 17:09
@shurd : Do you have any updated ETA for this?

**Comment by MehaKaushik** [comment] 2020-09-09 22:29
Hey @SebRosander @rnagpal Apologies for the delay from our side. We are still investigating the issue. It looks like somewhere in the go sdk the capitalization is not being respected, we are working towards getting this triaged.

**Comment by SebRosander** [comment] 2020-09-10 11:32
No stress for me personally, I've have a workaround in place. Please just let me know when it's fixed and I'll be able to remove that workaround. Thanks for keeping us updated @MehaKaushik

**Comment by MehaKaushik** [comment] 2020-09-30 22:09
Thanks for your understanding @SebRosander. To provide with you an update: We have reached out to the team which generates this sdk (from the specs specified azure-rest-api-specs) to look into what is causing this behavior. I will update once I have any more leads.

**Comment by MehaKaushik** [comment] 2020-10-27 21:38
We have root caused the issue, a change at service end is needed. We plan to do so in the coming months. I dont have a fixed timeline yet, once I have it I will update here.

**Comment by MehaKaushik** [comment] 2020-10-29 19:41
Hey @SebRosander  looks like our Service is coded to have Indexingmode to start with small. To remain consistent with our data plane sdks, we will not change the behavior of the Service, instead we will fix the Swagger. Strictly speaking, we made a mistake while documenting the swagger. Since this will be  a breaking change,we will make this change in the next stable apiVersion. To track this issue at one place, I will close this issue. Please track it here https://github.com/Azure/azure-rest-api-specs/issues/11222

In my opinion, as long as you don't update your SDK you would have to use the work around you are using right now, we don't want to break any existing behaviors, hence the fix would  be in the next stable apiVersion. Please feel free to ask any follow-ups you might have.

**Closed by MehaKaushik** 2020-10-29 19:41 UTC
Labels: Cosmos, Mgmt, Service Attention, customer-reported

**Comment by MehaKaushik** [comment] 2021-01-28 05:07
Just to update the fix will be released as a part of our upcoming apiVersion 2020-01-15
