### ISSUE TITLE
[KeyVault] Family type not generated

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-sdk-for-go#483] opened 2016-12-05 22:42 UTC
I don't exactly know why it is caused, but AutoRest is not generating a type for [Sku Family](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L239)

**Comment by jhendrixMSFT** [comment] 2016-12-16 18:55
I believe this is by design as this enum type is modeled as a string type.  I see the same pattern for other SDKs.  Please reopen if you disagree.

**Comment by mcardosos** [comment] 2016-12-30 21:39
Reopened (and better explained too: [AutoRest issue](https://github.com/Azure/autorest/issues/1667))

**Comment by marstr** [comment] 2017-01-20 21:27
Is there any reason to have this open as a duplicate issue to Azure/autorest#1667? If possible, I'd like to close this out.

**Comment by mcardosos** [comment] 2017-01-20 21:49
I like to have both, one explaining the "symptom" and other for the "cause". I do the same when the Swaggers are incorrect (I keep the SDK issue open until we regen, but close the issue in the swaggers repo as soon as the changes in swaggers are merged).
If you feel issues should not be added in both places, feel free to close one.

**Comment by jhendrixMSFT** [comment] 2017-03-06 20:25
This behavior is by (poor) design and manifests because the enum has only one element (see the linked issue in AutoRest for details).

**Closed by jhendrixMSFT** 2017-03-06 20:25 UTC
Labels: area/azureresourcemanager, P1
