### ISSUE TITLE
LRO: PATCH/PUT initial response of 200 is considered valid

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-sdk-for-go#2179] opened 2018-07-04 09:37 UTC
:wave:

We're using v17.4.0 of the HDInsights SDK (version 2013-05-01-preview) and when an error occurs (such as selecting an incorrect size for a cluster) - it appears that errors aren't being surfaced correctly.

When an error's returned, the API's returning a 200 status code which contains an error block; which (IMO) should be being raised as an error. Here's the full API response that we're seeing:

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Expires: -1
ETag: "d4f89bcc-370c-461d-a53d-7a1731960010"
Vary: Accept-Encoding
x-ms-hdi-matched-rule: ClusterResourcesAndSubResources
x-ms-hdi-routed-to: RegionalRp
x-ms-hdi-clusteruri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/hdinsight-resources/providers/Microsoft.HDInsight/clusters/terraform-hdi?api-version=2015-03-01-preview
Azure-AsyncOperation: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/hdinsight-resources/providers/Microsoft.HDInsight/clusters/terraform-hdi/azureasyncoperations/create?api-version=2015-03-01-preview
x-ms-request-id: 2a7b15d9-4097-4ebe-ab16-36f415261c89
x-ms-hdi-served-by: westeurope
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id: e59a0066-ac46-446e-a8dc-9fb94c1fb716
x-ms-routing-request-id: UKWEST:20180704T090814Z:e59a0066-ac46-446e-a8dc-9fb94c1fb716
X-Content-Type-Options: nosniff
Date: Wed, 04 Jul 2018 09:08:13 GMT
```
```json
{
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/hdinsight-resources/providers/Microsoft.HDInsight/clusters/terraform-hdi",
  "name": "terraform-hdi",
  "type": "Microsoft.HDInsight/clusters",
  "location": "West Europe",
  "etag": "d4f89bcc-370c-461d-a53d-7a1731960010",
  "tags": {},
  "properties": {
    "clusterVersion": "3.6.1000.65",
    "osType": "Linux",
    "clusterDefinition": {
      "blueprint": "https://blueprints.azurehdinsight.net/hadoop-3.6.1000.65.1806251927.json",
      "kind": "Hadoop",
      "componentVersion": { "Hadoop": "2.7" }
    },
    "computeProfile": {
      "roles": [
        {
          "name": "headnode",
          "targetInstanceCount": 2,
          "hardwareProfile": { "vmSize": "Medium" },
          "osProfile": { "linuxOperatingSystemProfile": { "username": "tombuildsstuff" } },
          "encryptDataDisks": false
        },
        {
          "name": "workernode",
          "targetInstanceCount": 4,
          "hardwareProfile": { "vmSize": "Medium" },
          "osProfile": { "linuxOperatingSystemProfile": { "username": "tombuildsstuff" } },
          "encryptDataDisks": false
        },
        {
          "name": "zookeepernode",
          "targetInstanceCount": 3,
          "hardwareProfile": { "vmSize": "Medium" },
          "osProfile": { "linuxOperatingSystemProfile": { "username": "tombuildsstuff" } },
          "encryptDataDisks": false
        }
      ]
    },
    "provisioningState": "Failed",
    "clusterState": "Error",
    "createdDate": "2018-07-04T09:00:00.567",
    "quotaInfo": { "coresUsed": 12 },
    "errors": [
      {
        "code": "InvalidDocumentErrorCode",
        "message": "DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'Medium' provided in the CSM document is invalid or not supported for role 'headnode''"
      }
    ],
    "tier": "standard"
  }
}
```

Would it be possible to expose this information in the error object using the `err` object returned from the Future? We're seeing this error from the CreateOrUpdate method and the Future method, fwiw.

Thanks!

**Comment by jhendrixMSFT** [comment] 2018-07-06 17:34
@tombuildsstuff I'm not sure how we can propagate this as an actual error since from the SDK's perspective the API call succeeded (i.e. this response is modeled as a success in the swagger).
@wawon-msft can we get some insight on the semantics here?  It seems very counter-intuitive that an HTTP 200 is actually an error.

**Comment by jhendrixMSFT** [comment] 2018-07-24 20:41
@tombuildsstuff sorry for the delay on this.  I just noticed that this operation is actually a long-running operation.  Which hdinsight package are you using?  The deprecated one under ```./services/hdinsight``` doesn't correctly model the operation as long-running.  The correct one is ```github.com/Azure/azure-sdk-for-go/services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight``` which models this as long-running returning a future which should properly surface the error.

**Comment by tombuildsstuff** [comment] 2018-07-25 08:05
@jhendrixMSFT we're using the `"github.com/Azure/azure-sdk-for-go/services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight"` package for both [the Cluster](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1267/files#diff-1aedf97365bdcfe0d1e6e56d89093829R11) and the Application; although we weren't seeing this raised as expected?

**Comment by jhendrixMSFT** [comment] 2018-07-26 18:43
@tombuildsstuff sorry I didn't read your initial report close enough.  :(  The non-conformant ```errors``` field is what's tripping up the SDK.  I'll work on a fix so that a ```Failed``` provisioning state returns an error however the RP needs to fix their service to be compliant.

**Comment by tombuildsstuff** [comment] 2018-07-27 08:03
@jhendrixMSFT no worries :)

FYI there's a couple of API's (e.g. Compute) where "Failed" doesn't mean Failed - but instead means "the current operation failed but it may succeed" (from #2322) - which may be good edge-cases for testing that?

**Comment by tombuildsstuff** [comment] 2018-07-31 17:52
@jhendrixMSFT I don't but I can put one together if that's helpful? From memory trying to set an invalid  number of nodes should cause this (e.g. trying to submit 1-4 head nodes, I think?)

**Comment by jhendrixMSFT** [comment] 2018-08-02 22:50
Finally got my repro working (I was missing some fields), investigating further...

**Comment by jhendrixMSFT** [comment] 2018-08-03 16:05
OK, the initial PUT to create the cluster returns an HTTP 200 with a provisioning state of ```InProgress```.  It's during polling that we get a response with a provisioning state of ```Failed```; this does return an error object from ```future.WaitForCompletionRef()``` however the ```Code``` and ```Message``` fields are nil since the error object isn't OData v4.  At present the best we can do is to include the entire response body in the error object (stuffing it into the ```AdditionalInfo``` field) but this is not ideal (you have to read through a wall of JSON to understand the error).  I'm following up with the RP to see if we can do better.

**Comment by jhendrixMSFT** [comment] 2018-08-06 21:30
More peeling (last I hope!).  I believe the problem is due to the initial 200 response to the PUT; it should be a 201.  I hacked up my repro to turn the 200 into a 201 and everything worked as expected.

**Comment by jhendrixMSFT** [comment] 2018-08-06 22:10
The remaining work is in the swagger and RP which is tracked in https://github.com/Azure/azure-rest-api-specs/issues/3590.

**Comment by tombuildsstuff** [comment] 2018-08-07 07:46
cool thanks @jhendrixMSFT :)

**Comment by jhendrixMSFT** [comment] 2018-08-14 22:29
The initial response of 200 is valid for PATCH/PUT so the LRO state machine needs to be updated.

**Comment by jhendrixMSFT** [comment] 2018-08-30 19:45
Fixed in https://github.com/Azure/go-autorest/releases/tag/v10.15.3 which will be included in the v20 SDK.

**Comment by jhendrixMSFT** [comment] 2018-08-30 21:45
Fixed in https://github.com/Azure/azure-sdk-for-go/releases/tag/v20.0.0

**Closed by jhendrixMSFT** 2018-08-30 21:45 UTC
Labels: P1, Sprint-120, Sprint-121, Sprint-122, customer, fix available, in progress
