### ISSUE TITLE
Budgets API is not maintaining case on dictionary keys

### ISSUE THREAD

**Issue by andysworkshop** [Azure/azure-sdk-for-go#5418] opened 2019-08-02 09:41 UTC
### Bug Report

Using [this SDK](https://github.com/Azure/azure-sdk-for-go/tree/master/services/consumption/mgmt/2019-01-01/consumption).

Budget `PUT` operation from client logs:
```
{
  "properties": {
    "amount": "100.65",
    "category": "Cost",
    "filters": {
      "meters": [
        "00000000-0000-0000-0000-000000000000"
      ],
      "resources": [
        "/subscriptions/{subscription-id}/resourceGroups/MYDEVTESTRG/providers/Microsoft.Compute/virtualMachines/MYVM2",
        "/subscriptions/{subscription-id}/resourceGroups/MYDEVTESTRG/providers/Microsoft.Compute/virtualMachines/platformcloudplatformGeneric1"
      ],
      "tags": {
        "CATEGORY": [
          "Dev",
          "Prod"
        ],
        "DEPARTMENT": [
          "engineering",
          "sales"
        ]
      }
    },
    "notifications": {
      "TEST_NOTIFICATION": {
        "enabled": true,
        "operator": "GreaterThan",
        "threshold": "80.12",
        "contactEmails": [
          "andrew.brown@nowhere.com"
        ]
      }
    },
    "timeGrain": "Monthly",
    "timePeriod": {
      "startDate": "2019-08-01T00:00:00Z",
      "endDate": "2022-10-31T00:00:00Z"
    }
  }
}
```
Immediately followed by GET operation from client logs:
```
{
  "id": "providers/Microsoft.Management/managementGroups/plat-dev-innovation-1/providers/Microsoft.Consumption/budgets/MyBudget",
  "name": "MyBudget",
  "type": "Microsoft.Consumption/budgets",
  "eTag": "\"1d5491626ce6f97\"",
  "properties": {
    "timePeriod": {
      "startDate": "2019-08-01T00:00:00Z",
      "endDate": "2022-10-31T00:00:00Z"
    },
    "timeGrain": "Monthly",
    "amount": 100.65,
    "currentSpend": {
      "amount": 0.0,
      "unit": "USD"
    },
    "category": "Cost",
    "notifications": {
      "tesT_NOTIFICATION": {
        "enabled": true,
        "operator": "GreaterThan",
        "threshold": 80.1200,
        "contactEmails": [
          "andrew.brown@nowhere.com"
        ],
        "contactRoles": [],
        "contactGroups": [],
        "thresholdType": "Actual"
      }
    },
    "filters": {
      "resourceGroups": [],
      "resources": [
        "/subscriptions/{subscription-id}/resourceGroups/MYDEVTESTRG/providers/Microsoft.Compute/virtualMachines/MYVM2",
        "/subscriptions/{subscription-id}/resourceGroups/MYDEVTESTRG/providers/Microsoft.Compute/virtualMachines/platformcloudplatformGeneric1"
      ],
      "meters": [
        "00000000-0000-0000-0000-000000000000"
      ],
      "tags": {
        "category": [
          "Dev",
          "Prod"
        ],
        "department": [
          "engineering",
          "sales"
        ]
      }
    }
  }
}
```

Note how the first 3 letters of the notification key have been mutated to lower case and the filter tag keys have been completely mutated. 

This breaks state comparison when using tools such as Terraform.

**Comment by loarabia** [comment] 2019-08-02 22:18
Hi @andysworkshop  I've tagged this so the right person on the team can find it.

**Comment by ArcturusZhang** [comment] 2020-01-17 12:40
Hi @andysworkshop sorry for this very late reply.
I have tested with the pure rest api with similar request body, and totally reproduced your issue.
The root cause of this is from the service side, therefore I submit a new issue in the azure-rest-api-specs repo [here](https://github.com/Azure/azure-rest-api-specs/issues/8183).
We could track this issue there since that is where the root cause lies. In the mean time, I will close this issue.

**Closed by ArcturusZhang** 2020-01-17 12:40 UTC
Labels: Consumption, Mgmt, Service Attention, customer-reported
