### ISSUE TITLE
Provide costmanagement version 2019-11-01 

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-sdk-for-go#12571] opened 2020-09-22 04:59 UTC
### Feature Request
Please update the SDK to add cost management version, _2019-11-01_  to SDK. The most latest version available is _2019-10-01_

**Comment by ArcturusZhang** [comment] 2020-09-27 03:21
Duplicate of https://github.com/Azure/azure-sdk-for-go/issues/12452

**Closed by ArcturusZhang** 2020-09-27 03:21 UTC
Labels: customer-reported, needs-triage, question
