### ISSUE TITLE
azblob storage SDK | Functions should accept io.ReadSeeker instead of io.ReadSeekCloser

### ISSUE THREAD

**Issue by mohsha-msft** [Azure/azure-sdk-for-go#18252] opened 2022-05-26 05:12 UTC
A few of the customers have raised the request to make body io.ReadSeeker instead of io.ReadSeekCloser.  Closing should be done IF body supports it but it is not mandatory that body support it. So we can let go of this. I think the changes are required in the Autorest Golang generator

**Comment by mohsha-msft** [comment] 2022-05-26 05:22
https://github.com/Azure/azure-sdk-for-go/issues/16714

**Comment by jhendrixMSFT** [comment] 2022-05-26 14:23
The requirement for `io.Closer` comes from the [`Request.Body`](https://pkg.go.dev/net/http#Request) field so we can't remove it.

**Comment by jhendrixMSFT** [comment] 2022-08-17 19:24
Closing as this is by design.

**Closed by jhendrixMSFT** 2022-08-17 19:24 UTC
Labels: CodeGen, Client, Azure.Core
