### ISSUE TITLE
The resource type 'roleAssignments' could not be found in the namespace.

### ISSUE THREAD

**Issue by TomerHeber** [Azure/azure-sdk-for-go#16699] opened 2021-12-22 22:55 UTC
### Bug Report

- https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/authorization/armauthorization/zz_generated_roleassignments_client.go
- SDK version: latest.
- go version go1.17.5 darwin/amd64

The error message is:
`InvalidResourceType","message":"The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2020-10-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2017-10-01-preview,2018-01-01-preview,2018-07-01,2018-09-01-preview,2018-12-01-preview,2019-04-01-preview,2020-03-01-preview,2020-04-01-preview,2020-08-01-preview,2021-04-01-preview'.`

It looks like the version the SDK is using is not listed for roleAssignments.
It would be useful to allow users to override the api version.

At the moment it's hard-coded: `reqQP.Set("api-version", "2020-10-01-preview")`

**Comment by TomerHeber** [comment] 2021-12-22 23:03
Seems to be a duplicate of:
https://github.com/Azure/azure-sdk-for-go/issues/15624

**Comment by lirenhe** [comment] 2021-12-24 08:54
@TomerHeber, we are contacting service team for the service update but currently, there is no ETA of that.
We will close this one as it is duplicate of https://github.com/Azure/azure-sdk-for-go/issues/15624.
Let me know if you have further questions. Thanks

**Comment by TomerHeber** [comment] 2021-12-29 14:48
Closing as duplicate.

**Closed** 2021-12-29 14:48 UTC
Labels: question, Authorization, Mgmt, customer-reported
