### ISSUE TITLE
Error = 'json: cannot unmarshal number into Go struct field JobResourceList.value of type backup.JobSupportedAction'

### ISSUE THREAD

**Issue by jkrajniak** [Azure/azure-sdk-for-go#5339] opened 2019-07-25 09:18 UTC
### Bug Report

I would like to list the backup jobs, therefore I am using call `backup.JobsClient.ListComplete`. However, this cause the following error:
`backup.JobsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field JobResourceList.value of type backup.JobSupportedAction'`

Indeed, in the JSON file that is reported in the error, 
```
{
    "value": [
        {
            "id": "...",
            "name": "...",
            "type": "Microsoft.RecoveryServices/vaults/backupJobs",
            "properties": {
                "jobType": "AzureIaaSVMJob",
                "duration": "PT2H1M21.2577606S",
                "actionsInfo": [
                    1
                ],
               ...
            }
        }
   ]
}
```
`actionsInfo` field is a number, not any of the values defined here:
https://github.com/Azure/azure-sdk-for-go/blob/master/services/recoveryservices/mgmt/2017-07-01/backup/models.go#L568

Minimal example to reproduce the error: https://gist.github.com/jkrajniak/a3717b6afa441cd3c6f41d84d614c779

Not sure where is the problem. the documentation for the API (https://docs.microsoft.com/en-us/rest/api/backup/backupjobs/list#mabjob) defines that field as a `string`.

**Comment by pvrk** [comment] 2019-07-29 10:53
@AdityaTulasi, @TAdityaAnirudh: can you please take a look at this?

**Comment by metrue** [comment] 2019-09-19 07:29
met same issue, 

```
 --- PASS: TestClientSuite/TestClients (0.00s)
    --- FAIL: TestClientSuite/TestGetOperationStatus (2.08s)
        client_test.go:70:
            	Error Trace:	client_test.go:70
            	Error:      	Received unexpected error:
            	            	backup.JobsClient#List: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field JobResourceList.value of type backup.JobSupportedAction' JSON = '{"value":[{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/c5529980-4735-4a7b-b360-5073cdef7185","name":"c5529980-4735-4a7b-b360-5073cdef7185","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT1H9M58.9495507S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-19T03:07:26.0228043Z","endTime":"2019-09-19T04:17:24.972355Z","activityId":"535f4731-0a1b-4dd6-8139-01f66d258ce5"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/cac9d958-c953-4863-a081-f8ae09025840","name":"cac9d958-c953-4863-a081-f8ae09025840","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT51M17.2611476S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-18T03:05:48.4990038Z","endTime":"2019-09-18T03:57:05.7601514Z","activityId":"df7c0fc5-1cb6-44cb-81bd-9f38ad4d2ae2"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/0a599218-033f-4d3c-8ad8-bbd8111af351","name":"0a599218-033f-4d3c-8ad8-bbd8111af351","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT41M17.1287143S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-17T03:05:10.2373432Z","endTime":"2019-09-17T03:46:27.3660575Z","activityId":"c41e116c-1d47-4bd9-bce2-1ff67055c8e3"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/e0b5751b-1fc0-4d8c-a91e-6520e3aec6fc","name":"e0b5751b-1fc0-4d8c-a91e-6520e3aec6fc","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT0.4092717S","errorDetails":[{"errorCode":134607754,"errorTitle":"BMSUserErrorObjectLocked","errorString":"Another operation is in progress on the selected item.","recommendations":["If there is an in-progress operation, please retry after it has finished."]}],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"ConfigureBackup","status":"Failed","startTime":"2019-09-17T00:58:44.2368639Z","endTime":"2019-09-17T00:58:44.6461356Z","activityId":"d4f75510-8839-40d1-ab65-726fa5448641"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/30a00235-e49e-471a-87c0-422be1a41187","name":"30a00235-e49e-471a-87c0-422be1a41187","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT11.6938589S","virtualMachineVersion":"Compute","entityFriendlyName":"democ","backupManagementType":"AzureIaasVM","operation":"ConfigureBackup","status":"Completed","startTime":"2019-09-17T00:58:42.4601096Z","endTime":"2019-09-17T00:58:54.1539685Z","activityId":"59a5a5ba-5282-483c-b58d-955c38b9cf9b"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/471e1336-9421-4a2a-9c3a-6b92f54d5b40","name":"471e1336-9421-4a2a-9c3a-6b92f54d5b40","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT11.7137541S","virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"ConfigureBackup","status":"Completed","startTime":"2019-09-17T00:58:42.444488Z","endTime":"2019-09-17T00:58:54.1582421Z","activityId":"59a5a5ba-5282-483c-b58d-955c38b9cf9b"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/a50cbdc1-d969-4f33-88d6-0a1762c98472","name":"a50cbdc1-d969-4f33-88d6-0a1762c98472","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT2H41M24.1171941S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-16T03:32:48.5753373Z","endTime":"2019-09-16T06:14:12.6925314Z","activityId":"0dcd22b8-4f79-450d-8db9-b99f51e99c24"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/f5686e24-5acb-4fe4-8b7b-ff311346003d","name":"f5686e24-5acb-4fe4-8b7b-ff311346003d","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT3H11M21.5033472S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-15T03:43:25.8321677Z","endTime":"2019-09-15T06:54:47.3355149Z","activityId":"6c4886f7-d7ec-4267-ba86-fa68c55ca19b"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/7357df8f-0bec-4155-8bfc-f51f48f7aefb","name":"7357df8f-0bec-4155-8bfc-f51f48f7aefb","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT4H21M23.7997244S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-14T03:37:40.0401516Z","endTime":"2019-09-14T07:59:03.839876Z","activityId":"5b03c9b8-0f75-4ed6-96cc-3bea68a1b225"}},{"id":"/Subscriptions/fc51e62f-aef2-49c3-b154-5b313db3f379/resourceGroups/Minghe_test/providers/Microsoft.RecoveryServices/vaults/backupvaultMinghetestdemo/backupJobs/b4315780-5760-4f6d-9ad1-8f52c6e95cc2","name":"b4315780-5760-4f6d-9ad1-8f52c6e95cc2","type":"Microsoft.RecoveryServices/vaults/backupJobs","properties":{"jobType":"AzureIaaSVMJob","duration":"PT4H21M23.2197762S","actionsInfo":[1],"virtualMachineVersion":"Compute","entityFriendlyName":"demo","backupManagementType":"AzureIaasVM","operation":"Backup","status":"Completed","startTime":"2019-09-13T03:18:57.9085514Z","endTime":"2019-09-13T07:40:21.1283276Z","activityId":"6253060a-b49d-40f7-aa08-7e191dad80c9"}}]}'
            	Test:       	TestClientSuite/TestGetOperationStatus
```

**Comment by metrue** [comment] 2019-09-19 09:49
Create a PR here https://github.com/Azure/azure-sdk-for-go/pull/5831

**Comment by ArcturusZhang** [comment] 2019-09-20 02:20
I create a new [issue](https://github.com/Azure/azure-rest-api-specs/issues/7268) in the swagger repo.
The service team will take care of this.

**Comment by pvrk** [comment] 2019-12-26 13:29
@ArcturusZhang : I see that the new issue you created in swagger repo is now closed. So, should I track this issue there or continue here?

**Comment by ArcturusZhang** [comment] 2019-12-27 03:04
> @ArcturusZhang : I see that the new issue you created in swagger repo is now closed. So, should I track this issue there or continue here?

I suggest you track this issue at the [swagger repo](https://github.com/Azure/azure-rest-api-specs/issues/7268), since the root cause is in rest api.

**Comment by pvrk** [comment] 2020-09-24 10:08
Closing this issue since the original issue is being tracked in the swagger repo.

**Closed by pvrk** 2020-09-24 10:08 UTC
Labels: Mgmt, Recovery Services Backup, Service Attention, customer-reported
