### ISSUE TITLE
ARM as a code does not work

### ISSUE THREAD

**Issue by mjudeikis** [Azure/azure-sdk-for-go#5603] opened 2019-08-23 08:27 UTC
`Goal`:

To be able to construct all `Azure` objects in code and Marsal/Unmarshal them in a transparent way while interacting with ARM API and constructing versioned payload for ARP API to consume

1. We would like to be able to construct versioned JSON from Objects and interact with ARM Templates instead of individual versioned APIS.
2. We would like to be able to generate ARM Templates from code without the need to manipulate JSON files before we produce the files. 

`Use-case`: 
We are using `SDK` to create ARM templates as a code. We are using `v24` SDK version for now due to internal dependencies.  We managed our ARM templates as a code in the form of:

```
func (g *generator) vnet() *network.VirtualNetwork {
	return &network.VirtualNetwork{
		....
		Name:     to.StringPtr(vnetName),
		Type:     to.StringPtr("Microsoft.Network/virtualNetworks"),
		Location: to.StringPtr(g.cs.Location),
	}
}
```
And later on:

```
t := arm.Template{
		Schema:         "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
		ContentVersion: "1.0.0.0",
		Resources: []interface{}{
			g.vnet(),
			g.ipAPIServer(),
			.....
		},
	}
```
After this, we have `object` representation of ARM template. 

*Challenges:*
1. SDK representation does not contain `Version` field[1] (and it is mandatory in JSON payload when sending to API server), so we have to do some hacking to inject them. We do this based on Type and `map` we maintain. But to do this we need to do[2]:
a) marshal to bytes
b) Marshal back to `var azuretemplate map[string]interface{}` to keep values
c) Do manipulation and inject required fields (version)
d) work with `azuretemplate map[string]interface{}` instead of more native object.

2. A newer version of SDK does not contain `Type` field too in the struct[3], so our model does not work as there is no way to map objects to the version anymore.

*Suggestion*:

Remove `// Type - READ-ONLY; Resource type.` types from the SDK, so enabling usage SDK object in more code native way.

Potentially introduce the ability to construct ARM code as a code with all subfields required by ARM to accept the payload.

[1] Due to the big file you might need to go `RAW` on github.
 https://github.com/Azure/azure-sdk-for-go/blob/v27.0.0/services/network/mgmt/2018-07-01/network/models.go#L19030-L19053

[2]
```
b, err := json.Marshal(template)
	if err != nil {
		return nil, err
	}

	var azuretemplate map[string]interface{}
	err = json.Unmarshal(b, &azuretemplate)
	if err != nil {
		return nil, err
	}

	err = arm.FixupAPIVersions(azuretemplate, versionMap)
	if err != nil {
		return nil, err
	}
```

[3]
https://github.com/Azure/azure-sdk-for-go/blob/v28.0.0/services/network/mgmt/2018-07-01/network/models.go#L18798-L18814 

/cc @amanohar @jim-minter @serbrech @ritazh

**Comment by bwplotka** [comment] 2019-08-25 11:51
> Potentially introduce the ability to construct ARM code as a code with all subfields required by ARM to accept the payload.

I would vote for this. (e g adding those Version fields to structs). It makes internal data model structs an external API, but that would help a lot users who use Go to automate/define their infrastructure.

**Comment by mybayern1974** [comment] 2019-09-14 06:36
@jhendrixMSFT to possibly comment

**Comment by jhendrixMSFT** [comment] 2019-09-14 15:07
The SDK is generated from swagger files, so removing any fields would require them to be removed from the swagger definition which I think is unlikely (it's also likely that somebody depends on them anyways).  Is it just the `Type` field that's causing problems?  The fact it's `READ-ONLY`?  Something else?
Regarding missing version info, I could update the codegen to add an `APIVersion()`, possibly on client types.  It will require some more thought as composite packages (i.e. packages made up of multiple swagger files) usually contain multiple API versions so it's not as simple as adding an exported `const`.  Would this work?  Open to suggestions.
Generally speaking, any codegen enhancements that introduce breaking changes are pretty much out of the question so please keep that in mind when coming up with ideas.

**Comment by m1kola** [comment] 2019-09-16 12:26
@jhendrixMSFT I think, the summary of the issue is: there is currently no *official* way to build an [ARM template](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates) as code using Azure SDK and a workaround gets broken after upgrading SDK version.

The workaround is to use types from the SDK that were designed to work with REST API, but not with ARM. As a result there are few issues:

* Types get changed based on swagger definitions without taking ARM into account. The `Type` field is one of the examples: the older versions of SDK were marshaling it into JSON, but newer version do not. Not marshaling this field makes sense for REST API, because type can be received from the endpoint URL, but not for ARM where type needs to be explicitly specified.
* Some fields are not present in REST types: for example, ARM expects to receive `apiVersion` field in JSON, but in REST API it's [a URL parameter](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/virtualnetworks/createorupdate#uri-parameters), so it's not present in the type definition generated from the swagger spec. Another example is `dependsOn`: it's not a thing in the REST API, but it's an important field in the ARM template.

>  Is it just the `Type` field that's causing problems? The fact it's `READ-ONLY`? Something else?

It's `Name` and `Type` on most of the types that represent resources in Azure SDK: these fields are present in the structs and [they get unmarshaled from JSON](https://github.com/Azure/azure-sdk-for-go/blob/v33.2.0/services/network/mgmt/2018-01-01/network/models.go#L14308-L14325), but becasue they are read only [they don't get marshaled into JSON](https://github.com/Azure/azure-sdk-for-go/blob/v33.2.0/services/network/mgmt/2018-01-01/network/models.go#L14252-L14270). In some other types apart from `Name` and `Type` similar issue can be found with other fields: for example, [storage `Account` doesn't marshal `Sku`, `Kind` into JSON](https://github.com/Azure/azure-sdk-for-go/blob/v33.2.0/services/storage/mgmt/2019-04-01/storage/models.go#L581-L597), but ARM expects these fields.

Also [ARM API supports `apiVersion`, `dependsOn`, `condition`, `resources` and some other fields](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#resources) in the resource section. Existing REST types simply do not have these fields.

> Generally speaking, any codegen enhancements that introduce breaking changes are pretty much out of the question so please keep that in mind when coming up with ideas.

It's hard to suggest something specific, because I didn't manage to find any code or API specs for the ARM API publicly available. Maybe having separate types for the ARM API and for the REST API would help us to achieve what we need without breaking backward compatibility? OR wrap REST types in a structure with extra fields and custom marshaling? ARM API types to include `apiVersion`, `dependsOn`, `resources` (to accept child resources), `condition`, etc in the JSON.

**Comment by tombuildsstuff** [comment] 2019-09-16 16:57
I vaguely recall API's within Azure (maybe AKS/App Service?) that will return a BadRequest when some of these fields (e.g. Type or Kind) are set - as such I'd suggest against serialising the `kind` and `type` fields in the SDK Structs. Instead it might be better for the SDK to expose a struct containing the common properties needed for resources within an ARM Template, which can then take the inner 'Properties' structs exposed in the SDK - for example:

```
type TemplateDeploymentObject struct {
  Version string `json:"apiVersion"
  Type string `json:"type"
  Location string `json:"location"
  // ..
  InnerObject interface{} `json:"properties"`
  Resources *[]TemplateDeploymentObject `json:"resources"
}
```

It's worth noting the Swagger definitions are sharing the same Request/Response Definitions for the Create/Update and Read methods in most cases to reduce total LOC - as a consumer of the SDK it'd be really nice for these to be split up in the Swagger so it's possible to determine which fields can be updated without trying every field and seeing what works, since the documentation doesn't reflect this in most circumstances.

@mjudeikis @m1kola out of interest since you're importing the SDK to build up the structs anyway - have you considered using the SDK's Clients (and associated waiters) rather than generating an ARM Template?

**Comment by mjudeikis** [comment] 2019-09-17 14:31
@tombuildsstuff I think `type TemplateDeploymentObject struct` would not work as proposed as each resource is versioned individually, and is treated as a separate object in the payload.

We already wrapping this in the work of:
```
t := arm.Template{
		Schema:         "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
		ContentVersion: "1.0.0.0",
		Resources: []interface{}{
			g.vnet(),
			g.loadBalancer(), 
		},
	}
```
| out of interest since you're importing the SDK to build up the structs anyway - have you considered using the SDK's Clients (and associated waiters) rather than generating an ARM Template?

When operating with big numbers of objects it would cause a separate set of problems (which would require much more maintenance to keep up). In an example, our code currently handles dependencies, `arm.FixupDepends` so we can just pre-append multiple objects into the `Resources` slice and don't care about ordering and creation flow. ARM will do this for us. Updates of the objects become seamless too.

Overall it makes our code base testable. As not we have defined the output of our "Infrastructure" which we can version between releases, and we can use hash'es, mocking, etc to test our code behavior. If we use clients directly, we don't have defined view of our Object without high-level API mocking for each endpoint.
And lack of mock clients in the codebase we would need to mock each and every client * version to have extensive testing.

And finally - constructing code this way is so much nicer :)

**Comment by jhendrixMSFT** [comment] 2019-09-18 15:49
Tom is right; some services will reject REST calls that provide properties marked as R/O, and this pattern will become more prevalent over time.
I think generating separate types used solely for constructing a template is the likely solution; it would probably go in a sub-package to keep all template-specific code grouped together, e.g. `github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network/networkdeployment`.
For next steps, what would be great to see is a hand-written prototype of what this deployment package might look like.  It doesn't have to be the entire content for a service but enough to distill the general pattern so it can be implemented in the code generator.  Is somebody on this thread willing to take a stab at it?

**Comment by mjudeikis** [comment] 2019-09-18 15:51
Any pointers where this should be "stabbed" ? Where do the definitions are located and hw generations works? :)

**Comment by m1kola** [comment] 2019-09-18 16:04
I was thinking about it today. I think I have an idea how to make something like `TemplateDeploymentObject` (from https://github.com/Azure/azure-sdk-for-go/issues/5603#issuecomment-531864556) work. I'm happy to do the hand-written prototype.

@jhendrixMSFT could you please point me into the direction of ARM API specs? Are the specs public? They are not necessary for me to do the prototype, but they will be helpful. I can't find anything in the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repo. I found docs ([structure and syntax of Azure Resource Manager templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates) and [template reference](https://docs.microsoft.com/en-us/azure/templates/)), but not specs.

**Comment by jhendrixMSFT** [comment] 2019-09-24 16:52
Sorry for the delay.  I'm not sure which ARM APIs you're looking for, do you mean [these](https://docs.microsoft.com/en-us/rest/api/resources/deployments)?

**Comment by m1kola** [comment] 2019-09-26 16:33
@jhendrixMSFT Thanks. I was looking for [this](https://github.com/Azure/azure-resource-manager-schemas).

> I think generating separate types used solely for constructing a template is the likely solution; it would probably go in a sub-package to keep all template-specific code grouped together, e.g. `github.com/Azure/azure-sdk-for-go/services/network/mgmt/2019-06-01/network/networkdeployment`.

I think, having separate types will work for use cases when you construct template from scratch. But, will be tricky for use cases when you want to get some existing resource from the REST API and create a template based on it: there will be type mismatch and the SDK user will have to do a lot of manual data copying.

I'm currently looking into options ot solve this using type embeding. Hopefully will come back to you with something early next week.

**Comment by m1kola** [comment] 2019-09-30 16:20
Hi @jhendrixMSFT. After several discussions with my collegues and some experiments, I see the following solutions and potential issues with them.

I'm happy to arrange a call to discuss ways forward with you (with posting an update here for visibility, after the call).

Termenology I use below:

* REST types - structs that already exist in the SDK (`VirtualNetwork`, `PublicIPAddress`, etc).
* ARM types - structs that will be defined or generated for use with the ARM API.

## Generating separate types used solely for ARM templates

There are two options in this solution:

* Generate only top-level types (e.g. `VirtualNetwork`, but not `VirtualNetworkPropertiesFormat`).
* Generate all types.

Both options have a common set of issues:

* It will work for use cases when you construct a template from scratch. But, will be tricky for use cases when you want to get some existing resource from the REST API and create a template based on it: there will be type mismatch and SDK users will have to do a lot of manual data copying from existing REST types to ARM types (e.g. from existing `VirtualNetwork` to newly generated type "`VirtualNetworkForARM`" or whatever we call it).
    * I think, It will be harder if we decide to generate all types vs generating only top-level types.
* If I understand [the ARM spec correctly](https://github.com/Azure/azure-resource-manager-schemas/blob/048e6544da46d05531f7821144f1bd6cd72164d8/schemas/2019-04-01/deploymentTemplate.json), all the types consist of combination of REST types + ARM-specific fields, so the difference between existing REST types and new types will only be in ARM-specific fields.
* It will significantly increase number of type in the SDK: `apiVersion`, `dependsOn` and other ARM-specific fields come from the [ARM schema which also has multiple versions](https://github.com/search?utf8=%E2%9C%93&q=repo%3AAzure%2Fazure-resource-manager-schemas+filename%3AdeploymentTemplate.json&type=Code&ref=advsearch&l=&l=). This means that we will have to generate the same type multiple times to statisfy different ARM versions.

The above issues bring us to the following solution.

## Embeding REST API types with ARM-specific fields

We can solve some of the above issues with embeding. Embeding will make it easier to use instances of REST types in ARM templates and will reduce code repetition in the SDK.

So type definitions will be something like:

<details>
<summary>Click to see ARM template types</summary>

**Note:** this is based on `2019-04-01` version of ARM deployment template, but it's not complete. Just enough for our examples.

```go
type Template struct {
    Schema         string        `json:"$schema,omitempty"`
    ContentVersion string        `json:"contentVersion,omitempty"`
    APIProfile     string        `json:"apiProfile,omitempty"`
    Parameters     struct{}      `json:"parameters,omitempty"`
    Variables      struct{}      `json:"variables,omitempty"`
    Resources      []interface{} `json:"resources,omitempty"`
    Outputs        struct{}      `json:"outputs,omitempty"`
}

type ARMResource struct {
    Condition  *bool            `json:"condition,omitempty"`
    APIVersion *string          `json:"apiVersion,omitempty"`
    DependsOn  []string         `json:"dependsOn,omitempty"`
    Comments   *string          `json:"comments,omitempty"`
    Copy       *ARMResourceCopy `json:"copy,omitempty"`
}

type ARMResourceCopy struct {
    Name      string `json:"name,omitempty"`
    Count     int    `json:"count,omitempty"`
    Mode      string `json:"mode,omitempty"`
    BatchSize int    `json:"batchSize,omitempty"`
}
```

</details>

<details>
<summary>Click to see `VirtualNetwork` definition</summary>

**Note:** see comments in code

```go
package armembeding

import (
	"encoding/json"

	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-07-01/network"
)

type VirtualNetwork struct {
	network.VirtualNetwork
	ARMResource
}

func (vn VirtualNetwork) MarshalJSON() ([]byte, error) {
	objectMap := make(map[string]interface{})

	// Copy from network.VirtualNetwork with some modifications for read-only fields
	if vn.VirtualNetworkPropertiesFormat != nil {
		objectMap["properties"] = vn.VirtualNetworkPropertiesFormat
	}
	if vn.Etag != nil {
		objectMap["etag"] = vn.Etag
	}
	if vn.ID != nil {
		objectMap["id"] = vn.ID
	}
	if vn.Name != nil {
		// NOTE: REST type network.VirtualNetwork doesn't marshal
		// this field in latest versions of SDK, but we need it in ARM. 
		// https://github.com/Azure/azure-sdk-for-go/blob/v34.0.0/services/network/mgmt/2018-07-01/network/models.go#L18826-L18845
		objectMap["name"] = vn.Name
	}
	if vn.Type != nil {
		// NOTE: same issue as with Name
		objectMap["type"] = vn.Type
	}
	if vn.Location != nil {
		objectMap["location"] = vn.Location
	}
	if vn.Tags != nil {
		objectMap["tags"] = vn.Tags
	}

	// ARM-specific fields
	if vn.Condition != nil {
		objectMap["condition"] = vn.Condition
	}
	if vn.APIVersion != nil {
		objectMap["apiVersion"] = vn.APIVersion
	}
	if vn.Comments != nil {
		objectMap["comments"] = vn.Comments
	}
	if vn.Copy != nil {
		objectMap["copy"] = vn.Copy
	}
	return json.Marshal(objectMap)
}
```
</details>


This reduces code repetition in SDK a bit and makes use of REST instances in ARM templates easier. For example, you can do something like:

```go
vnet, err := vnetClient.Get(ctx, "myRG", "myVNet", "")
if err != nil {
    return err
}

vnetForARM := armembeding.VirtualNetwork{
    VirtualNetwork: network.VirtualNetwork{
        VirtualNetworkPropertiesFormat: vnet.VirtualNetworkPropertiesFormat,
        Name:     to.StringPtr("myNewVNet"),
        Type:     to.StringPtr(vnet.Type),
        Location: to.StringPtr("eastus"),
    },
    ARMResource: ARMResource{
        APIVersion: to.StringPtr("2018-07-01"),
    },
}
```

However, we still have one of the issue we had in the previous solution:

* We need to generate a lot of extra types for ARM: each REST type will have copies for every ARM version because `ARMResource` contains versions specific ARM fields.


## Get rid of custom marshaling in REST types

It's very easy to define own ARM types and use the embeding approach (see `Template`, `ARMResource` and `ARMResourceCopy` above), so it probably make sense to leave this task for users.

But the fact that REST types have custom marshaling makes it harder. Users have to define own implementation of `MarshalJSON` with a copy of generated code from SDK and add some code that marshals read only fields (`Type`, `Name`, etc) and ARM-specific fields. For users who use a lot of types from SDK it will be cumbersome.

I think we can solve this issue and keep SDK backward compatible, so we don't break things for users who set values in the read-only fields before sending requests to the API. We can do that by changing where readonly cleanup happens. Currently it's in `MarshalJSON`. The high level idea is to:

* Get rid of `MarshalJSON` and `UnmarshalJSON`, but keep `json` tags on fields in the REST types.
* Cleanup data before sending to the API (somewhere in clients or is there more suitable place?).



---

Not directly related to the above, but for ARM users it would be great to have a constant with a version in the package, so instead of `APIVersion: to.StringPtr("2018-07-01")` we can do something like `APIVersion: network.APIVersion`. Should I create a separate issue for this?

**Comment by m1kola** [comment] 2019-10-08 09:23
@jhendrixMSFT, any feedback on the above? Please, let me know if you would like to have a call to discuss it.

**Comment by jhendrixMSFT** [comment] 2019-10-08 16:36
Sorry for the delay.  This is a great write-up, thanks for putting it together.

We won't be able to get rid of at least some of the custom marshalling/unmarshalling as we use it to support discriminated types in swagger.  While we could potentially change the implementation it's a fragile part of the code so I'd prefer to not do this unless there was no other choice.

Out of the three options I prefer the embedding solution.  I don't really see the generation of extra ARM types as a huge problem, and I really like the fact that it isolates template code from API code.  Do you feel this solution would meet your needs?

**Comment by m1kola** [comment] 2019-10-14 12:08
@jhendrixMSFT sorry for the delay on my side now :)

Yes, this approach will work for our use case and hopefully for other SDK users. But I worry about it's maintainability in the SDK itself. Going this route means that SDK will have `N * Z` copies of the same top-level type just for ARM consumption (where `N` is the version of the REST API type and `Z` is the version of ARM schema).

For example, we currently seem to have 25 versions of the `network` package (`github.com/Azure/azure-sdk-for-go/services/network/mgmt/*/network`) and 4 ([or 7?](https://github.com/search?utf8=%E2%9C%93&q=repo%3AAzure%2Fazure-resource-manager-schemas+filename%3AdeploymentTemplate.json&type=Code&ref=advsearch&l=&l=)) version of ARM schema. So we will have 96 (`25 * 4`) copies of a struct that is present in each of these 25 `network` packages. Add a new version of the the ARM scheme and it will be 125 copies, etc. The more combinations the more things to worry about when changing something in the code generation.

> We won't be able to get rid of at least some of the custom marshalling/unmarshalling as we use it to support discriminated types in swagger.

I'm not sure that I understand what you mean. Could you please give more details on this?

**Comment by jhendrixMSFT** [comment] 2019-10-21 22:39
In swagger, a discriminator is used to define polymorphic types (see [here](https://swagger.io/specification/v2/) for more details, search for the word `discriminator`).  For an example see the [BasicEventSourceCreateOrUpdateParameter](https://github.com/Azure/azure-sdk-for-go/blob/master/services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights/models.go#L1207) type.  In the func [unmarshalBasicEventSourceCreateOrUpdateParameters](https://github.com/Azure/azure-sdk-for-go/blob/master/services/timeseriesinsights/mgmt/2017-11-15/timeseriesinsights/models.go#L1223) it will look at the discriminator field `kind` and unmarshal the response into the appropriate type.

**Comment by jhendrixMSFT** [comment] 2019-10-21 22:49
You bring up a good point about the code explosion.  Is `MarshalJSON` the only problematic method?  Perhaps we can come up with a way to toggle the behavior; by default the R/O fields would be excluded.  Easiest place to put it would be a toggle on the clients, but then you have to set it for each client.

**Closed** 2022-04-08 22:02 UTC
Labels: Mgmt, customer-reported, ARM - Templates, issue-addressed
