### ISSUE TITLE
Backup Long Term Retention Policies model update

### ISSUE THREAD

**Issue by WackPenguin** [Azure/azure-sdk-for-go#7823] opened 2020-03-10 14:38 UTC
### Feature Request

SDK models don't seem to match to what can be passed to the backup long term retention policies api. As per [documentation](https://docs.microsoft.com/en-us/rest/api/sql/backuplongtermretentionpolicies/createorupdate#backuplongtermretentionpolicy) you should be able to pass through:
![image](https://user-images.githubusercontent.com/3824689/76322668-95defc00-62db-11ea-9471-2636af171cab.png)

But the SDK models for the policy creation require you to pass Recovery service ID.

![image](https://user-images.githubusercontent.com/3824689/76323514-b78cb300-62dc-11ea-9fa9-90045bad06e3.png)

Looking at the api specs, the properties I'm looking for are there. [spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/longTermRetention.json)

Could this part of SDK get re-generated?

**Comment by ArcturusZhang** [comment] 2020-03-12 11:30
Hi @WackPenguin thanks for this issue!
The api-version you are looking at do have an unresolved problem on this field. I am still investigating this. But there is another api-version `v3.0` for the `sql` service which is a super set of every valid api-versions for `sql`. I recommend you switch to this api-version.

**Comment by WackPenguin** [comment] 2020-03-12 14:41
@ArcturusZhang Thank you! I will switch to using v3

**Comment by jhendrixMSFT** [comment] 2020-03-12 16:32
I took a look,  the swagger longTermRetention.json isn’t in tag package-2017-03-preview which is used to build that package; it is in package-composite-* tags though which is why you see it.

**Comment by ArcturusZhang** [comment] 2020-03-13 04:24
And @WackPenguin this issue is caused by the `2017-03-preview` api-version is not including the swagger you mentioned. But it is not practical for us to change the `input-files` in swagger, and since `v3` could solve your issue, therefore I will close this, thanks!

**Closed by ArcturusZhang** 2020-03-13 04:24 UTC
Labels: Mgmt, SQL - Backup & Restore, codegen, customer-reported
