### ISSUE TITLE
ContainerPager loops forever

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-go#19901] opened 2023-01-31 08:43 UTC
### Bug Report
I face currently an Issue that under certain Circumstances the `containerPager` loops for ever.

I saw for a Storage Account the first `ListContainersSegmentResponse` of `NextPage()` contains `ContainerItems` as empty Array, `MaxResults` is nil, `Marker` is nil and `NextMarker` is pointing to something like `<storageAccount>/$accountmetadata`.
In the next Iteration of the Loop, the Markers didn't get updated and the `NextPage()` Result contains still the same Informations as before. And so it loops forever.
I observed it happens only when the first Result points to a Container starting with `$` like `$accountmetadata` or `$blobchangefeed`.
For some Storage Accounts it just works fine.

I expected to update the Markers within the `NextPage()` Call or am I wrong?

The Code I use:
 ```
containerPager := client.NewListContainersPager(&azblob.ListContainersOptions{
    Include: azblob.ListContainersInclude{
	    Metadata: true, Deleted: false,
    },
    Marker: new(string),
})

for containerPager.More() {
    page, pageErr := containerPager.NextPage(context.Background())
    if pageErr != nil {
	    log.Fatal(pageErr.Error())
    }
    for _, container := range page.ContainerItems {
	    // DO SOMETHING
    }
}
```

I work around like this at the moment:
```
containerPager := client.NewListContainersPager(&azblob.ListContainersOptions{
    Include: azblob.ListContainersInclude{
	    Metadata: true, Deleted: false,
    },
    Marker: new(string),
})

for containerPager.More() {
    page, pageErr := containerPager.NextPage(context.Background())
    if pageErr != nil {
	    log.Fatal(pageErr.Error())
    }
    for _, container := range page.ContainerItems {
	    // DO SOMETHING
    }

   // create a new ContainersPager with updated Marker
    if page.NextMarker != nil && len(*page.NextMarker) != 0 {
			    containerPager = client.NewListContainersPager(&azblob.ListContainersOptions{
				    Include: azblob.ListContainersInclude{
					    Metadata: true, Deleted: false,
				    },
				    Marker: page.NextMarker,
			    })
		    }
}
```

I used `v0.5.1`, `v0.6.0` and `v0.6.1` of `azblob`

**Comment by siminsavani-msft** [comment] 2023-02-02 23:25
Hi @the-mod ! Since creating containers with invalid name is not possible (i.e. having `$` is actually not possible without the changefeed feature), the listing API won't recognize that the container starting with `$` like `$accountmetadata` or `$blobchangefeed`. 

From the documentation: https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names 
> Container names must start or end with a letter or number, and can contain only letters, numbers, and the dash (-) character.

The expected behavior should be that the containers with `$` would be ignored and the rest of the containers would be listed as per normal.

**Comment by siminsavani-msft** [comment] 2023-02-02 23:27
Alternatively, if you want to access the containers with `$` you can do the following:

`containerName := "$blobchangefeed"
containerClient := client.NewContainerClient(containerName)
resp, err := containerClient.GetProperties(context.Background(), nil)
`

Since this is not a bug, I will close this issue. Please feel free to reopen as needed!

**Closed by siminsavani-msft** 2023-02-02 23:27 UTC
Labels: question, Storage, Client, customer-reported, needs-team-attention

**Comment by vibhansa-msft** [comment] 2023-02-03 03:31
"NextMarker is pointing to something like <storageAccount>/$accountmetadata" : how did you decipher that nextMarker is pointing to $accontmetadata?

**Comment by the-mod** [comment] 2023-02-03 15:45
> "NextMarker is pointing to something like /$accountmetadata" : how did you decipher that nextMarker is pointing to $accontmetadata?

I debugged my application and saw its looping forever. I checked the Markers during the loops.

**Comment by siminsavani-msft** [comment] 2023-02-03 16:12
> Maybe its impossible by User to create Names starting with $, but other Azure Service could do? How else should I have such a Container in my Storage Account?

As I mentioned, the changefeed feature is enabled which creates the $blobchangefeed container via Azure Service.

**Comment by the-mod** [comment] 2023-02-03 17:31
> > Maybe its impossible by User to create Names starting with $, but other Azure Service could do? How else should I have such a Container in my Storage Account?
> 
> As I mentioned, the changefeed feature is enabled which creates the $blobchangefeed container via Azure Service.

Sure and if such a Container exists in a Storage Account the provided snippet won't work (which is also taken from the offical Examples)

**Comment by siminsavani-msft** [comment] 2023-02-03 17:35
> Sure and if such a Container exists in a Storage Account the provided snippet won't work (which is also taken from the offical Examples). Maybe you quickly validate it

Could you point out to which code snippet are you referring to? Thanks!

**Comment by the-mod** [comment] 2023-02-03 17:38
> > Sure and if such a Container exists in a Storage Account the provided snippet won't work (which is also taken from the offical Examples). Maybe you quickly validate it
> 
> Could you point out to which code snippet are you referring to? Thanks!

The first one I added in the initial posting or the one from the examples [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#example-package-Client_NewListContainersPager).

Just try to loop over all available Containers in a Storage Account containing Containers with `$` in the Names.

**Comment by siminsavani-msft** [comment] 2023-02-03 17:40
> The first one I added in the initial posting or the one from the examples [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#example-package-Client_NewListContainersPager).

> Just try to loop over all available Containers in a Storage Account containing Containers with $ in the Names.

Thanks for including the link! So yes, I have tried to test the example code with containers in my account with `$` and it does not list the `$` containers at all. Totally understand that this is weird since the container technically exists, but this is the expected behavior as of now. 

I am not experiencing any looping or hanging with the example code.

**Comment by the-mod** [comment] 2023-02-03 17:43
okay that is strange 😢 but thanks for checking anyway

**Comment by the-mod** [comment] 2023-02-03 17:49
Maybe try the Release `1.0.6` of this [Project](https://github.com/azure-open-tools/storage-explorer).
It contains the Code Piece of the Example to iterate over all Containers.
It should loop forever.
`1.0.7` contains already a Fix to avoid this behavior.
