### ISSUE TITLE
Failing to parse JSON response from Cosmos ListSQLRoleDefinitions

### ISSUE THREAD

**Issue by jarrodd07** [Azure/azure-sdk-for-go#15295] opened 2021-08-15 06:31 UTC
### Bug Report
I am trying to retrieve a list of SQL Role Definitions setup against a Cosmos DB. When I call ListSQLRoleDefinitions I'm getting the following error:
`documentdb.SQLResourcesClient#ListSQLRoleDefinitions: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field SQLRoleDefinitionListResult.value of type documentdb.RoleDefinitionType'`

I'm assuming this is a similar issue to #14509 where the Swagger spec has an issue.

The JSON returned is 
```json
{
  "value": [
    {
      "id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.DocumentDB/databaseAccounts/.../sqlRoleDefinitions/00000000-0000-0000-0000-000000000001",
      "name": "00000000-0000-0000-0000-000000000001",
      "properties": {
        "roleName": "Cosmos DB Built-in Data Reader",
        "type": 0,
        "assignableScopes": [
          "/subscriptions/.../resourceGroups/.../providers/Microsoft.DocumentDB/databaseAccounts/..."
        ],
        "permissions": [
          {
            "dataActions": [
              "Microsoft.DocumentDB/databaseAccounts/readMetadata",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/readChangeFeed",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/read"
            ],
            "notDataActions": []
          }
        ]
      },
      "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions"
    },
    {
      "id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.DocumentDB/databaseAccounts/.../sqlRoleDefinitions/00000000-0000-0000-0000-000000000002",
      "name": "00000000-0000-0000-0000-000000000002",
      "properties": {
        "roleName": "Cosmos DB Built-in Data Contributor",
        "type": 0,
        "assignableScopes": [
          "/subscriptions/.../resourceGroups/.../providers/Microsoft.DocumentDB/databaseAccounts/..."
        ],
        "permissions": [
          {
            "dataActions": [
              "Microsoft.DocumentDB/databaseAccounts/readMetadata",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/*",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/*"
            ],
            "notDataActions": []
          }
        ]
      },
      "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions"
    }
  ]
}
```

Here's the code I'm using to generate the error
```go
package main

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/cosmos-db/mgmt/2021-06-15/documentdb"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
	ctx := context.Background()
	client := documentdb.NewSQLResourcesClient(<subscription_id>)
	authorizer, err := auth.NewAuthorizerFromEnvironment()
	client.Authorizer = authorizer
	defs, err := client.ListSQLRoleDefinitions(ctx, <resource_group>, <cosmos_account>)
	if err != nil {
		fmt.Println(err.Error())
	}
	fmt.Println(defs)
}
```
- import path of package `.../services/cosmos-db/mgmt/2021-06-15/documentdb`
- SDK version v56.2.0

**Comment by jarrodd07** [comment] 2021-08-25 07:14
Hey @lirenhe I'm assuming it's this line that's causing us issues [rbac.json](https://github.com/Azure/azure-rest-api-specs/blob/44017a20d8c022217b31e15643595fc7aff87926/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/rbac.json#L407). 
The swagger spec defines the type as a string, but the API is actually returning an integer. What do we need to do to get this fixed?

**Comment by jarrodd07** [comment] 2021-09-02 21:03
Hey @lirenhe, should I be raising this as in issue in the azure-rest-api-specs github repo instead?

**Comment by ArcturusZhang** [comment] 2021-09-10 08:37
> Hey @lirenhe, should I be raising this as in issue in the azure-rest-api-specs github repo instead?

Hey @jarrodd07 , since this is caused by mismatch between swagger and actual response, this should be an issue of the swaggers instead of our SDK. Could you please open an issue in the azure-rest-api-spec repo?

**Comment by lirenhe** [comment] 2021-09-13 05:28
Close this item as this is a Swagger issue. After the swagger is fixed, the new release of CosmosDB would contain the fix.
@jarrodd07, feel free to reopen it if you have further questions. Thanks

**Closed by lirenhe** 2021-09-13 05:28 UTC
Labels: bug, Cosmos, Mgmt, customer-reported, needs-team-attention
