### ISSUE TITLE
Consumption related properties should be updated.

### ISSUE THREAD

**Issue by AmoebaCell** [Azure/azure-sdk-for-go#8132] opened 2020-04-02 07:51 UTC
### Bug Report

- import path of package in question, e.g. `.../services/compute/mgmt/2018-06-01/compute`
- SDK version e.g. `master`, `latest`, `18.1.0`
  - Specify the exact commit if possible; one way to get this is the REVISION
    column output by `dep status "github.com/Azure/azure-sdk-for-go`.
- output of `go version`

https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/costmanagement/mgmt/2019-10-01/costmanagement/models.go

- What happened?
While try to call related API for fetching the usage data, there is a filter error happened on model validation.

- What did you expect or want to happen?
- How can we reproduce it?
The code and related document have a problem on property name. For document, have created an issue to request updating. (The filter property - "tag" and "dimension" should be "tag**s**" and "dimension**s**". )

We can verify the information by:
1. Open portal 
2. navigate to subscription - usage 
3. Press F12, click the usage. 
4. Check the request related payload.  

in models.go, line 827-830, ugly but workable fix is append s in the json conversion.
// Dimension - Has comparison expression for a dimension
Dimension *QueryComparisonExpression `json:"dimensions,omitempty"`
// Tag - Has comparison expression for a tag
Tag *QueryComparisonExpression `json:"tags,omitempty"`

- Anything we should know about your environment.
N/A

**Comment by ArcturusZhang** [comment] 2020-04-03 05:08
Hi @AmoebaCell thanks for this issue.
Since go SDK is generated from the azure-rest-api-specs, I just checked the rest api definitions corresponding to the code you are looking at [here](https://github.com/Azure/azure-rest-api-specs/blob/7070ddd988a69c63d0ea593d48d5512473accdb4/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-10-01/costmanagement.json#L1131) and find out that in the swagger, these two fields are defined as `dimension` and `tag`. 
If what you observed from the portal is caused by the service, the service team of cost management should update their swagger accordingly.

Therefore I have tagged this issue, the service team may have a look at this issue.

And additionally, the go SDK package you are referencing (preview/2019-10-01) has been deprecated, please use `github.com/Azure/azure-sdk-for-go/services/costmanagement/mgmt/2019-10-01/costmanagement` instead. The preview package should have been removed when it comes to stable. I will remove the preview package in the next major version. Thanks for pointing this out.

**Comment by ms-premp** [comment] 2020-05-11 15:41
Thanks for bringing this to attention.
We wlill be fixing this by end of this month.

**Comment by ramaganesan-rg** [comment] 2020-05-11 17:11
Updated milestone date as per comments from Prem.

**Comment by ramaganesan-rg** [comment] 2020-06-29 16:59
closing the issue. please feel free to reopen if you still see the issue.

**Closed by ramaganesan-rg** 2020-06-29 16:59 UTC
Labels: Cost Management, Mgmt, Service Attention, customer-reported

**Comment by sylashsu** [comment] 2022-03-11 06:33
Hi, guys

We found  same issue in models.go, line 1339-1365, struct  QueryFilter and MarshalJSON():
"tag" and "dimension" should be "tag**s**" and "dimension**s**"

Thanks.
