### ISSUE TITLE
[Blob] Clients should be returned by pointer

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-go#17263] opened 2022-03-09 19:00 UTC
Joshua Duffney pointed out that all of the clients are returning by value, this should be changed to returning by reference.

**Comment by jhendrixMSFT** [comment] 2022-04-15 17:37
Dupe of https://github.com/Azure/azure-sdk-for-go/issues/16972

**Closed by jhendrixMSFT** 2022-04-15 17:37 UTC
Labels: Storage
